name: generics
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  aone_common:
    path: ../../packages/common
  aone_widget:
    path: ../../packages/aone_widget

  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.0.3
  extended_image: ^6.0.2+1
  dropdown_button2: ^1.4.0
  tuple: ^2.0.0
  carousel_slider: ^4.1.1
  carousel_indicator: ^1.0.6
  flutter_swipe_action_cell: ^2.2.0
  getwidget: ^2.1.1
  flutter_spinkit: ^5.1.0
  flutter_inappwebview: ^5.7.2+3
  card_swiper: ^2.0.3
  keframe: ^2.0.6
  flutter_staggered_animations: ^1.0.0
  gif: ^2.2.0
  flutter_easyrefresh: ^2.2.2
  infinite_scroll_pagination: 3.1.0
  flutter_widget_from_html: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:

  assets:
    - assets/images/
    - assets/
    - assets/images/betback/
    - assets/images/user/
    - assets/images/betback/b97/
    - assets/images/app_update/
    - assets/images/game/
    - assets/images/landscape/
    - assets/images/common/
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
