name: leisure_games
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #Widget国际化支持
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.1.0
  expansion_datagrid: ^1.0.8
  rxdart: ^0.27.7
  event_bus: ^2.0.0
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.2.4
  flutter_easyloading: ^3.0.5
  get: ^4.6.6
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  common_utils: ^2.1.0
  #  webview_flutter: ^2.8.0
  getwidget: ^4.0.0
  flutter_inappwebview: ^6.0.0
  flutter_screenutil: ^5.9.0
  convex_bottom_bar: ^3.2.0
  marquee: ^2.2.3
  qr_flutter: ^4.1.0
#  pinput: ^3.0.1
  numeric_keyboard: ^1.1.0
  synchronized: ^3.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.9
  data_table_2: ^2.5.8
  syncfusion_flutter_charts: ^23.1.41
  scratcher: ^2.4.0
  luckywheel: ^1.0.0
  sprintf: ^7.0.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  android_id: ^0.3.6
  popover: ^0.2.8+2
  custom_pop_up_menu: ^1.2.4
  crypto: ^3.0.3
  #  azlistview: ^2.0.0
  image_gallery_saver: ^2.0.3
  scrollable_positioned_list: ^0.3.8
  web_socket_channel: ^2.4.0
  uuid: ^4.3.0
  url_launcher: ^6.2.2
#  open_filex: ^4.3.4
  flutter_form_builder: ^9.2.1
  flutter_aliyun_captcha: ^1.0.5
  flutter_tencent_captcha: ^0.1.2
  gesture_password_widget: ^2.0.1
  flutter_barrage: ^0.5.5
  just_audio: ^0.9.36
  flutter_oss_aliyun: ^6.4.1
  cached_network_image: ^3.3.1
  lifecycle: ^0.8.0
  flutter_html: 3.0.0-alpha.5
  flutter_svg: ^2.0.9
  install_plugin: ^2.1.0

#  ota_update: ^6.0.0
#  amplify_auth_cognito: ^1.7.2
#  amplify_flutter: ^1.7.0
#  amplify_storage_s3: ^1.7.0


dependency_overrides:
  meta: ^1.10.0 # 替换为你需要的meta库的版本号



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.3
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  json_serializable: ^6.6.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/images/
    - assets/font/
    - assets/music/
    - assets/json/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: ITCAvantGardeStd
      fonts:
        - asset: assets/font/ITCAvantGardeStd-Bk.otf
          weight: 600
        - asset: assets/font/ITCAvantGardeStd-Demi.otf
          weight: 400
        - asset: assets/font/ITCAvantGardeStd-Md.otf
          weight: 500
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true


