
import 'dart:ui';

import 'package:get/get.dart';
import 'package:leisure_games/app/app_data.dart';
import 'package:leisure_games/app/intl/luangage/vi.dart';

import 'luangage/cn.dart';
import 'luangage/en.dart';

class Intr extends Translations{
  Intr._internal();

  static Intr? instance;

  static getInstance() {
    instance ??= Intr._internal();
    return instance;
  }

  factory Intr() => getInstance();


  //中文 英文 越南语
  var locales = [const Locale('zh','ZH'),const Locale('en','US'),const Locale("vi","VI")];

  ///当前语言环境
  Locale currentLocale(){
    return locales[AppData.localeIndex()];
  }

  ///当前语言环境
  Locale fallbackLocale(){
    return locales[1];
  }

  String get theme => 'theme'.tr;
  String get home => 'home'.tr;
  String get mine => 'mine'.tr;
  String get preferential => 'preferential'.tr;
  String get customer_service => 'customer_service'.tr;
  String get charge => 'charge'.tr;
  String get tixian => 'tixian'.tr;
  String get choujiang => 'choujiang'.tr;
  String get zoushi => 'zoushi'.tr;
  String get remen => 'remen'.tr;
  String get zuijin => 'zuijin'.tr;
  String get shoucang => 'shoucang'.tr;
  String get gaunyuwomen => 'gaunyuwomen'.tr;
  String get guanwangjieshao => 'guanwangjieshao'.tr;
  String get xiazhaiyingyong => 'xiazhaiyingyong'.tr;
  String get pingtaifuwu => 'pingtaifuwu'.tr;
  String get yonghuzhongxin => 'yonghuzhongxin'.tr;
  String get huiyuan => 'huiyuan'.tr;
  String get chongzhijilu => 'chongzhijilu'.tr;
  String get qiandaochoujiang => 'qiandaochoujiang'.tr;
  String get jishuzhichi => 'jishuzhichi'.tr;
  String get fangjiechijiaocheng => 'fangjiechijiaocheng'.tr;
  String get fangjiechi => 'fangjiechi'.tr;
  String get shiyongbangzhu => 'shiyongbangzhu'.tr;
  String get shedingyuyan => 'shedingyuyan'.tr;
  String get morenyuyan => 'morenyuyan'.tr;
  String get tiaoguo => 'tiaoguo'.tr;
  String get queren => 'queren'.tr;
  String get xuanzeyuyan => 'xuanzeyuyan'.tr;
  String get xuanzeqianbao => 'xuanzeqianbao'.tr;
  String get morenqianbao => 'morenqianbao'.tr;
  String get shedingqianbao => 'shedingqianbao'.tr;
  String get rmb => 'rmb'.tr;
  String get dollar => 'dollar'.tr;
  String get thb => 'thb'.tr;
  String get vnd => 'vnd'.tr;
  String get hyld => 'hyld'.tr;
  String get qqzlxd => 'qqzlxd'.tr;
  String get register => 'register'.tr;
  String get login => 'login'.tr;
  String get grzx => 'grzx'.tr;
  String get rmbqb => 'rmbqb'.tr;
  String get yue_ => 'yue_'.tr;
  String get edzh => 'edzh'.tr;
  String get pcxq => 'pcxq'.tr;
  String get tzjl => 'tzjl'.tr;
  String get jymm => 'jymm'.tr;
  String get dyy => 'dyy'.tr;
  String get bjyy => 'bjyy'.tr;
  String get tsy => 'tsy'.tr;
  String get wgys => 'wgys'.tr;
  String get qs => 'qs'.tr;
  String get dx => 'dx'.tr;
  String get qk => 'qk'.tr;
  String get fxghy => 'fxghy'.tr;
  String get ycfx => 'ycfx'.tr;
  String get xzapp => 'xzapp'.tr;
  String get lxjbhb => 'lxjbhb'.tr;
  String get logout => 'logout'.tr;
  String get xzndyy => 'xzndyy'.tr;
  String get sszcbz => 'sszcbz'.tr;
  String get zxndbz => 'zxndbz'.tr;
  String get bbdh => 'bbdh'.tr;
  String get lxkf => 'lxkf'.tr;
  String get yhm => 'yhm'.tr;
  String get qsryhm => 'qsryhm'.tr;
  String get mm => 'mm'.tr;
  String get qsrmm => 'qsrmm'.tr;
  String get wjmm => 'wjmm'.tr;
  String get cjygzxh => 'cjygzxh'.tr;
  String get kfzx => 'kfzx'.tr;
  String get xszxkf => 'xszxkf'.tr;
  String get qthwnfw => 'qthwnfw'.tr;
  String get djjr => 'djjr'.tr;
  String get dxtxsz => 'dxtxsz'.tr;
  String get fpdx => 'fpdx'.tr;
  String get cksl => 'cksl'.tr;
  String get kjjgdx => 'kjjgdx'.tr;
  String get djsdx => 'djsdx'.tr;
  String get wgsz => 'wgsz'.tr;
  String get qzb => 'qzb'.tr;
  String get kxh => 'kxh'.tr;
  String get cjzh => 'cjzh'.tr;
  String get wszhzm => 'wszhzm'.tr;
  String get zsxm => 'zsxm'.tr;
  String get yzm => 'yzm'.tr;
  String get qsrzcyzm => 'qsrzcyzm'.tr;
  String get wywdbty => 'wywdbty'.tr;
  String get yhtk => 'yhtk'.tr;
  String get and => 'and'.tr;
  String get ysxy => 'ysxy'.tr;
  String get yyzh => 'yyzh'.tr;
  String get tab_pcfj => 'tab_pcfj'.tr;
  String get tab_cp => 'tab_cp'.tr;
  String get tab_zr => 'tab_zr'.tr;
  String get tab_ty => 'tab_ty'.tr;
  String get tab_by => 'tab_by'.tr;
  String get tab_dz => 'tab_dz'.tr;
  String get ytxyhkhmyz => 'ytxyhkhmyz'.tr;
  String dangqianzaixian(List<String> args) => 'dangqianzaixian'.trArgs(args);
  String get peilvshuoming => 'peilvshuoming'.tr;
  String get wanfaguizhe => 'wanfaguizhe'.tr;
  String get youxishuyu => 'youxishuyu'.tr;
  String get xiazhujiqiao => 'xiazhujiqiao'.tr;
  String get wanfaguizhe_jieshao => 'wanfaguizhe_jieshao'.tr;
  String get youxishuyu_jieshao => 'youxishuyu_jieshao'.tr;
  String get xiazhujiqiao_jieshao => 'xiazhujiqiao_jieshao'.tr;
  String get card_ptf => 'card_ptf'.tr;
  String get card_gjf => 'card_gjf'.tr;
  String get card_gbf => 'card_gbf'.tr;
  String get haoyuan => 'haoyuan'.tr;
  String get zhudan => 'zhudan'.tr;
  String get mipai => 'mipai'.tr;
  String get qushi => 'qushi'.tr;
  String dixqi(List<String> args) => 'dixqi'.trArgs(args);
  String juelidixqi(List<String> args) => 'juelidixqi'.trArgs(args);

  String get zongyue => 'zongyue'.tr;
  String get touzhu => 'touzhu'.tr;
  String get bet_da => 'bet_da'.tr;
  String get bet_xiao => 'bet_xiao'.tr;
  String get bet_dan => 'bet_dan'.tr;
  String get bet_shuang => 'bet_shuang'.tr;
  String get di => 'di'.tr;
  String get qi => 'qi'.tr;
  String get zhudan_ => 'zhudan_'.tr;
  String get zongji_ => 'zongji_'.tr;
  String get qiehuanfangjian => 'qiehuanfangjian'.tr;
  String get confirm => 'confirm'.tr;
  String get cancel => 'cancel'.tr;
  String get tema => 'tema'.tr;
  String get diyiqiu => 'diyiqiu'.tr;
  String get dierqiu => 'dierqiu'.tr;
  String get disanqiu => 'disanqiu'.tr;
  String get qingshurujine => 'qingshurujine'.tr;
  String get zongji => 'zongji'.tr;
  String get end => 'end'.tr;
  String get xiazhuxiangqing => 'xiazhuxiangqing'.tr;
  String get quanbujilu => 'quanbujilu'.tr;
  String get xiazhujine => 'xiazhujine'.tr;
  String get keyingjine => 'keyingjine'.tr;
  String get xiaoji => 'xiaoji'.tr;
  String xbi(List<String> args) => 'xbi'.trArgs(args);
  String qihao_(List<String> args) => 'qihao_'.trArgs(args);
  String get wallet_cny => 'wallet_cny'.tr;
  String get wallet_usdt => 'wallet_usdt'.tr;
  String get danhao => 'danhao'.tr;
  String get neirong => 'neirong'.tr;
  String get guanfanghaoyuan => 'guanfanghaoyuan'.tr;
  String get jianghaozhanshi => 'jianghaozhanshi'.tr;
  String get jianghaoshuoming => 'jianghaoshuoming'.tr;
  String get gongjujiaoyan => 'gongjujiaoyan'.tr;
  String get daojishi => 'daojishi'.tr;
  String get qihao => 'qihao'.tr;
  String get kaijianghaoma => 'kaijianghaoma'.tr;
  String get haoyuanjinqi => 'haoyuanjinqi'.tr;
  String get wanzhenghaoyuanzhanshi => 'wanzhenghaoyuanzhanshi'.tr;
  String zhuaqushijian(List<String> args) => 'zhuaqushijian'.trArgs(args);
  String get shuominghaoyuan => 'shuominghaoyuan'.tr;
  String get bitebipc28quhaojizhi => 'bitebipc28quhaojizhi'.tr;
  String get zhuahaoyuan => 'zhuahaoyuan'.tr;
  String get sha256zhuanhua => 'sha256zhuanhua'.tr;
  String get shijinzhizhuanhua => 'shijinzhizhuanhua'.tr;
  String get shengchengzuihzhonghaoma => 'shengchengzuihzhonghaoma'.tr;
  String get zhuahaoyuan_jieshao => 'zhuahaoyuan_jieshao'.tr;
  String get sha256zhuanhua_jieshao => 'sha256zhuanhua_jieshao'.tr;
  String get shijinzhizhuanhua_jieshao => 'shijinzhizhuanhua_jieshao'.tr;
  String get shengchengzuihzhonghaoma_jieshao => 'shengchengzuihzhonghaoma_jieshao'.tr;
  String get shuruduiyinghaoyuan => 'shuruduiyinghaoyuan'.tr;
  String get jiaoyan => 'jiaoyan'.tr;
  String get jiaoyanjieguo => 'jiaoyanjieguo'.tr;
  String get sha256zhuanhuahzi => 'sha256zhuanhuahzi'.tr;
  String get quqianshiliuwei => 'quqianshiliuwei'.tr;
  String get shijinweizhuanhuan => 'shijinweizhuanhuan'.tr;
  String get chuyierde64cifang => 'chuyierde64cifang'.tr;
  String get shuoming => 'shuoming'.tr;
  String get shuoming_jieshao => 'shuoming_jieshao'.tr;
  String get haoyuanchaxun => 'haoyuanchaxun'.tr;
  String get dianjifuzhi => 'dianjifuzhi'.tr;
  String get nowChat => 'nowChat'.tr;
  String get jiaoyanshuoming => 'jiaoyanshuoming'.tr;
  String get jiaoyanshuoming1 => 'jiaoyanshuoming1'.tr;
  String get jiaoyanshuoming2 => 'jiaoyanshuoming2'.tr;
  String get jiaoyanshuoming3 => 'jiaoyanshuoming3'.tr;
  String get jiaoyanshuoming4 => 'jiaoyanshuoming4'.tr;
  String get zuizhongkaijianghaoma => 'zuizhongkaijianghaoma'.tr;
  String dixqitouzhu(List<String> args) => 'dixqitouzhu'.trArgs(args);
  String dixqikaijiang(List<String> args) => 'dixqikaijiang'.trArgs(args);
  String get fengpanzhong => 'fengpanzhong'.tr;
  String get shuaxin => 'shuaxin'.tr;
  String get kaijiangjieguo => 'kaijiangjieguo'.tr;
  String get shujufenxi => 'shujufenxi'.tr;
  String get shuangmianchanglong => 'shuangmianchanglong'.tr;
  String get danshuangluzhu => 'danshuangluzhu'.tr;
  String get daxiaoluzhu => 'daxiaoluzhu'.tr;
  String get haomazhoushi => 'haomazhoushi'.tr;
  String lx_tongji(List<String> args) => 'lx_tongji'.trArgs(args);
  String xianshiqishu_(List<String> args) => 'xianshiqishu_'.trArgs(args);
  String get zhi => 'zhi'.tr;
  String get jixiao => 'jixiao'.tr;
  String get jida => 'jida'.tr;
  String get dalu => 'dalu'.tr;
  String get zhupanlu => 'zhupanlu'.tr;
  String get hao_value => 'hao_value'.tr;
  String get qingshuruyouximingcheng => 'qingshuruyouximingcheng'.tr;
  String get xuanzhe => 'xuanzhe'.tr;
  String get xuanzhexl => 'xuanzhe'.tr;
  String get quanbuyouxi => 'quanbuyouxi'.tr;
  String get shoucangla => 'shoucangla'.tr;
  String get qiandaoyouli => 'qiandaoyouli'.tr;
  String get jifen => 'jifen'.tr;
  String benyueyiqian(List<String> args) => 'benyueyiqian'.trArgs(args);
  String get zongjifen => 'zongjifen'.tr;
  String get lijiqiandao => 'lijiqiandao'.tr;
  String get day_yi => 'day_yi'.tr;
  String get day_er => 'day_er'.tr;
  String get day_san => 'day_san'.tr;
  String get day_si => 'day_si'.tr;
  String get day_wu => 'day_wu'.tr;
  String get day_liu => 'day_liu'.tr;
  String get day_ri => 'day_ri'.tr;
  String get jifenyaojiang => 'jifenyaojiang'.tr;
  String jifenmeici(List<String> args) => 'jifenmeici'.trArgs(args);
  String get lianyao5 => 'lianyao5'.tr;
  String get lianyao10 => 'lianyao10'.tr;
  String get lianyao15 => 'lianyao15'.tr;
  String get lianyao20 => 'lianyao20'.tr;
  String get huodongguizhe => 'huodongguizhe'.tr;
  String get jiangjintiqu => 'jiangjintiqu'.tr;
  String get nianyueri => 'nianyueri'.tr;
  String get bencijiangli => 'bencijiangli'.tr;
  String get gongxiwancheng => 'gongxiwancheng'.tr;
  String xiaciqiandao(List<String> args) => 'xiaciqiandao'.trArgs(args);
  String get mingtianjixue => 'mingtianjixue'.tr;
  String get gongxininhuode => 'gongxininhuode'.tr;
  String get jiangjin => 'jiangjin'.tr;
  String get cishu => 'cishu'.tr;
  String get lishikaijiang => 'lishikaijiang'.tr;
  String get kaijiangzhoushi => 'kaijiangzhoushi'.tr;
  String get qugoucai => 'qugoucai'.tr;
  String get goucai => 'goucai'.tr;
  String get xiaoxi => 'xiaoxi'.tr;
  String get gonggao => 'gonggao'.tr;
  String get gonggaoxiangqing => 'gonggaoxiangqing'.tr;
  String get youhuizhongxin => 'youhuizhongxin'.tr;
  String get chongzhi => 'chongzhi'.tr;
  String get quanbu => 'quanbu'.tr;
  String get qita => 'qita'.tr;
  String get fanhui => 'fanhui'.tr;
  String get wenxintishi_fuzhi => 'wenxintishi_fuzhi'.tr;
  String get chongzhizhongxin => 'chongzhizhongxin'.tr;
  String chongzhizhanghu_(List<String> args) => 'chongzhizhanghu_'.trArgs(args);
  String dangqianmoren(List<String> args) => 'dangqianmoren'.trArgs(args);
  String get xianshang => 'xianshang'.tr;
  String get xianxia => 'xianxia'.tr;
  String get diyibu_chakanshoukuanxinxi => 'diyibu_chakanshoukuanxinxi'.tr;
  String get wenxintishi_zhifuyoushijian => 'wenxintishi_zhifuyoushijian'.tr;
  String get dierbu_tianchongdingdan => 'dierbu_tianchongdingdan'.tr;
  String get chongzhizhanghu => 'chongzhizhanghu'.tr;
  String get huikuanxingming => 'huikuanxingming'.tr;
  String get huikuanjine => 'huikuanjine'.tr;
  String get qingshuruhuikuanren => 'qingshuruhuikuanren'.tr;
  String get qingshuruhuikuanjine => 'qingshuruhuikuanjine'.tr;
  String get tijiao => 'tijiao'.tr;
  String get bibiduihuan => 'bibiduihuan'.tr;
  String get eduzhuanhuan => 'eduzhuanhuan'.tr;
  String get zhifushuoming_rmb => 'zhifushuoming_rmb'.tr;
  String get zhifushuoming_wallet => 'zhifushuoming_wallet'.tr;

  String get kahao => 'kahao'.tr;
  String get cikaren => 'cikaren'.tr;
  String get beizhu => 'beizhu'.tr;
  String get dianjixiafangzhifu => 'dianjixiafangzhifu'.tr;
  String get wenxintishi_ => 'wenxintishi_'.tr;
  String get wenxintishi_1 => 'wenxintishi_1'.tr;
  String wenxintishi_2(List<String> args) => 'wenxintishi_2'.trArgs(args);
  String wenxintishi_3(List<String> args) => 'wenxintishi_3'.trArgs(args);
  String get tianrujine => 'tianrujine'.tr;
  String get shoudongshuruhuoxuanzhe => 'shoudongshuruhuoxuanzhe'.tr;
  String get diyibu_xuanzhezhifuxieyi => 'diyibu_xuanzhezhifuxieyi'.tr;
  String get dierbu_chakanshoukuanxinxi => 'dierbu_chakanshoukuanxinxi'.tr;
  String get shoukuanzhanghu => 'shoukuanzhanghu'.tr;
  String get disanbu_tianxierukuanxinxi => 'disanbu_tianxierukuanxinxi'.tr;
  String get fanhuishouye => 'fanhuishouye'.tr;
  String get zhifushuoming_ => 'zhifushuoming_'.tr;
  String get zhifushuoming_1 => 'zhifushuoming_1'.tr;
  String get zhifushuoming_2 => 'zhifushuoming_2'.tr;
  String nicheng_(List<String> args) => 'nicheng_'.trArgs(args);
  String get wodeqianbao => 'wodeqianbao'.tr;
  String get tixianmima => 'tixianmima'.tr;
  String get zijinmingxi => 'zijinmingxi'.tr;
  String get bangdingyinhangka => 'bangdingyinhangka'.tr;
  String get bangdingusdt => 'bangdingusdt'.tr;
  String get wodetouzhu => 'wodetouzhu'.tr;
  String get touzhujilu => 'touzhujilu'.tr;
  String get jifenjilu => 'jifenjilu'.tr;
  String get huiyuanfanshui => 'huiyuanfanshui'.tr;
  String get hongbaohejiangjin => 'hongbaohejiangjin'.tr;
  String get wodeyinli => 'wodeyinli'.tr;
  String get tuiguangzhuanqian => 'tuiguangzhuanqian'.tr;
  String get dializhuce => 'dializhuce'.tr;
  String get tongyongshezhi => 'tongyongshezhi'.tr;
  String get bangzhuzhongxin => 'bangzhuzhongxin'.tr;
  String get guanyuwomen => 'guanyuwomen'.tr;
  String tixianzhanghu_(List<String> args) => 'tixianzhanghu_'.trArgs(args);
  String get congcnyqianbaotichu => 'congcnyqianbaotichu'.tr;
  String get congusdtqianbaotichu => 'congusdtqianbaotichu'.tr;
  String get tixianxinxi => 'tixianxinxi'.tr;
  String get querentixianxinxi => 'querentixianxinxi'.tr;
  String get tixianjine => 'tixianjine'.tr;
  String get qingshurutixianmima => 'qingshurutixianmima'.tr;
  String get qingshurutixianjine => 'qingshurutixianjine'.tr;
  String get querenjine => 'querenjine'.tr;
  String get shouxufei => 'shouxufei'.tr;
  String get kedaozhangjine => 'kedaozhangjine'.tr;
  String get qingxuanzhetixianzhanghu => 'qingxuanzhetixianzhanghu'.tr;
  String get querenjihexinxi => 'querenjihexinxi'.tr;
  String zitixianhouzongtouzhu_(List<String> args) => 'zitixianhouzongtouzhu_'.trArgs(args);
  String meiyoutongguoyouhui_(List<String> args) => 'meiyoutongguoyouhui'.trArgs(args);
  String get tongguoyouhuijihe => 'tongguoyouhuijihe'.tr;
  String get changtaixingjihe => 'changtaixingjihe'.tr;
  String get tongguochangtaixing => 'tongguochangtaixing'.tr;
  String meiyoutongguochangtaixing_(List<String> args) => 'meiyoutongguochangtaixing'.trArgs(args);
  String get duocitixian => 'duocitixian'.tr;
  String yixiaoshineimian_(List<String> args) => 'yixiaoshineimian'.trArgs(args);
  String xukouchushouxufei_(List<String> args) => 'xukouchushouxufei'.trArgs(args);
  String get shixiaoshouxufei => 'shixiaoshouxufei'.tr;
  String get mianshoushouxufei => 'mianshoushouxufei'.tr;
  String get cichijiheshijian => 'cichijiheshijian'.tr;
  String meidongshijian_(List<String> args) => 'meidongshijian_'.trArgs(args);
  String get jixutixian => 'jixutixian'.tr;
  String get tijiaochenggong => 'tijiaochenggong'.tr;
  String get tixianxiangqing => 'tixianxiangqing'.tr;
  String get tijiaoshijian => 'tijiaoshijian'.tr;
  String shouxufei_(List<String> args) => 'shouxufei_'.trArgs(args);
  String get daozhangjine => 'daozhangjine'.tr;
  String get zhanghuyue => 'zhanghuyue'.tr;
  String get wancheng => 'wancheng'.tr;
  String get shezhi => 'shezhi'.tr;
  String get gerenziliao => 'gerenziliao'.tr;
  String get shezhidenglumima => 'shezhidenglumima'.tr;
  String get shezhijianyimima => 'shezhijianyimima'.tr;
  String get zhongwen => 'zhongwen'.tr;
  String get quankai => 'quankai'.tr;
  String get tuichudenglu => 'tuichudenglu'.tr;
  String get wanshanziliao => 'wanshanziliao'.tr;
  String get nicheng => 'nicheng'.tr;
  String get shoujihaoma => 'shoujihaoma'.tr;
  String get qqhaoma => 'qqhaoma'.tr;
  String get weixin => 'weixin'.tr;
  String get shuruweixinhao => 'shuruweixinhao'.tr;
  String get shuruqqhaoma => 'shuruqqhaoma'.tr;
  String get shuruzhenshiyouxiao => 'shuruzhenshiyouxiao'.tr;
  String get shurudianziyouxiang => 'shurudianziyouxiang'.tr;
  String get shurunicheng => 'shurunicheng'.tr;
  String get shezhitixianmima => 'shezhitixianmima'.tr;
  String get yuanmima => 'yuanmima'.tr;
  String get shuruyuantixianmima => 'shuruyuantixianmima'.tr;
  String get xinmima => 'xinmima'.tr;
  String get shuruxintixianmima => 'shuruxintixianmima'.tr;
  String get zaiciqueren => 'zaiciqueren'.tr;
  String get chongfushuru => 'chongfushuru'.tr;
  String get querenjianyimima => 'querenjianyimima'.tr;
  String get shurujianyimima => 'shurujianyimima'.tr;
  String get shezhichenggong => 'shezhichenggong'.tr;
  String get shuruneirongbuyizhi => 'shuruneirongbuyizhi'.tr;
  String get wenxintishi_jianyimima => 'wenxintishi_jianyimima'.tr;
  String get shuruyuandenglumima => 'shuruyuandenglumima'.tr;
  String get shuruxindenglumima => 'shuruxindenglumima'.tr;
  String get chongfushuruxindenglumima => 'chongfushuruxindenglumima'.tr;
  String get tixianzhongxin => 'tixianzhongxin'.tr;
  String get youhuijihe => 'youhuijihe'.tr;
  String get tixianzhanghu => 'tixianzhanghu'.tr;
  String get genghuantouxiang => 'genghuantouxiang'.tr;
  String get moren => 'moren'.tr;
  String get qq => 'qq'.tr;
  String get jingxuan => 'jingxuan'.tr;
  String get gezhanghumingxi => 'gezhanghumingxi'.tr;
  String get huazhuanjilu => 'huazhuanjilu'.tr;
  String get dailizhuce => 'dailizhuce'.tr;
  String get querenmima => 'querenmima'.tr;
  String get dianziyouxiang => 'dianziyouxiang'.tr;
  String get wenxintishi_zhuce => 'wenxintishi_zhuce'.tr;
  String get jieshaorenxinxi => 'jieshaorenxinxi'.tr;
  String get daima => 'daima'.tr;
  String get fuzhi => 'fuzhi'.tr;
  String get lianjie => 'lianjie'.tr;
  String get tuiguangerweima => 'tuiguangerweima'.tr;
  String get baocuntupian => 'baocuntupian'.tr;
  String get fuzhilianjie => 'fuzhilianjie'.tr;
  String get huiyuanliebiao => 'huiyuanliebiao'.tr;
  String get riqi => 'riqi'.tr;
  String get xiaxiancunkuan => 'xiaxiancunkuan'.tr;
  String get zhuanquhongli => 'zhuanquhongli'.tr;
  String get xianxiayonghu => 'xianxiayonghu'.tr;
  String get zhu_beijingshijian => 'zhu_beijingshijian'.tr;
  String get riqi_meidong => 'riqi_meidong'.tr;
  String get jiaoyileibie => 'jiaoyileibie'.tr;
  String get jiaoyiedu => 'jiaoyiedu'.tr;
  String get xianyouedu => 'xianyouedu'.tr;
  String get xiazhujifenjiangli => 'xiazhu_jifenjiangli'.tr;
  String get fuyinglifanshui => 'fuyinglifanshui'.tr;
  String get youxileixing => 'youxileixing'.tr;
  String get youxiaotouzhu => 'youxiaotouzhu'.tr;
  String get shuying => 'shuying'.tr;
  String get fanshui => 'fanshui'.tr;
  String get touzhuliangfanshui => 'touzhuliangfanshui'.tr;
  String get jinrizuhezhanbilv => 'jinrizuhezhanbilv'.tr;
  String qitayouxi_(List<String> args) => 'qitayouxi_'.trArgs(args);
  String get huishui => 'huishui'.tr;
  String get yinlifanshui => 'yinlifanshui'.tr;
  String get zuhezhanbilv => 'zuhezhanbilv'.tr;
  String get jinri => 'jinri'.tr;
  String get day_7 => 'day_7'.tr;
  String get day_15 => 'day_15'.tr;
  String get day_30 => 'day_30'.tr;
  String get youxipingtai => 'youxipingtai'.tr;
  String get bishu => 'bishu'.tr;
  String get touzhue => 'touzhue'.tr;
  String youxiaotouzhu_(List<String> args) => 'youxiaotouzhu_'.trArgs(args);
  String get touzhuriqi => 'touzhuriqi'.tr;
  String wodeyinhangka_(List<String> args) => 'wodeyinhangka_'.trArgs(args);
  String wodeshuzhiqianbao_(List<String> args) => 'wodeshuzhiqianbao_'.trArgs(args);
  String get tianjiayinhangka => 'tianjiayinhangka'.tr;
  String get wenxintixing_yinhangka => 'wenxintixing_yinhangka'.tr;
  String get tianjiashuziqianbao => 'tianjiashuziqianbao'.tr;
  String get wenxintixing_usdt => 'wenxintixing_usdt'.tr;
  String get dizhi => 'dizhi'.tr;
  String get suoshuxieyi => 'suoshuxieyi'.tr;
  String zuiduoketianjia_(List<String> args) => 'zuiduoketianjia_'.trArgs(args);
  String get hongbao => 'hongbao'.tr;
  String get jine => 'jine'.tr;
  String get youxiaoqi => 'youxiaoqi'.tr;
  String get xuyaodamaliang => 'xuyaodamaliang'.tr;
  String get yitiqu => 'yitiqu'.tr;
  String get weijihuo => 'weijihuo'.tr;
  String get yijihuo => 'yijihuo'.tr;
  String get yishixiao => 'yishixiao'.tr;
  String get tiqu => 'tiqu'.tr;
  String get tiquchenggong => 'tiquchenggong'.tr;
  String get duihuan => 'duihuan'.tr;
  String huilv_(List<String> args) => 'huilv_'.trArgs(args);
  String get cong_from => 'cong_from'.tr;
  String get zhi_to => 'zhi_to'.tr;
  String get zhuanru => 'zhuanru'.tr;
  String get huazhuanjine => 'huazhuanjine'.tr;
  String get querenhuazhuan => 'querenhuazhuan'.tr;
  String get yijianguiji => 'yijianguiji'.tr;
  String get xuanzheriqi => 'xuanzheriqi'.tr;
  String get shaixuan => 'shaixuan'.tr;
  String get cunqukuan => 'cunqukuan'.tr;
  String get zhuanzhang => 'zhuanzhang'.tr;
  String get zhichu => 'zhichu'.tr;
  String get shouru => 'shouru'.tr;
  String get qingxuanzhe => 'qingxuanzhe'.tr;
  String get qing3fenzhonghoushuaxin => 'qing3fenzhonghoushuaxin'.tr;
  String get chongzhixiangqing => 'chongzhixiangqing'.tr;
  String get dingdanbianhao => 'dingdanbianhao'.tr;
  String get chongzhijine => 'chongzhijine'.tr;
  String get chongzhixingming => 'chongzhixingming'.tr;
  String get zhongwenjianti => 'zhongwenjianti'.tr;
  String get yingyu => 'yingyu'.tr;
  String get yuenanyu => 'yuenanyu'.tr;
  String get jintian => 'jintian'.tr;
  String get zuijin7tain => 'zuijin7tain'.tr;
  String get zuijin30tian => 'zuijin30tian'.tr;
  String get quanbuzhuangtai => 'quanbuzhuangtai'.tr;
  String get chenggong => 'chenggong'.tr;
  String get chulizhong => 'chulizhong'.tr;
  String get yiquxiao => 'yiquxiao'.tr;
  String get quanbufangshi => 'quanbufangshi'.tr;
  String get changyongduanyu => 'changyongduanyu'.tr;
  String get qitaduanyu => 'qitaduanyu'.tr;
  String get biaoqing => 'biaoqing'.tr;
  String get gif => 'gif'.tr;
  String get shifoutuichudenglu => 'shifoutuichudenglu'.tr;
  String get shifouchongxinhuizhi => 'shifouchongxinhuizhi'.tr;
  String get fuzhichenggong => 'fuzhichenggong'.tr;
  String get qiehuanquanjuqianbao => 'qiehuanquanjuqianbao'.tr;
  String get tuijianyouli => 'tuijianyouli'.tr;
  String get zanwuyouxi => 'zanwuyouxi'.tr;
  String get qianghongbao => 'qianghongbao'.tr;
  String get fangwenluxian => 'fangwenluxian'.tr;
  String get kuai => 'kuai'.tr;
  String get yiban => 'yiban'.tr;
  String get henman => 'henman'.tr;
  String get bukeyong => 'bukeyong'.tr;
  String get fanshuishuoming => 'fanshuishuoming'.tr;
  String get jiazaizhong => 'jiazaizhong'.tr;
  String get weikaishi => 'weikaishi'.tr;
  String get jinxingzhong => 'jinxingzhong'.tr;
  String get yijieshu => 'yijieshu'.tr;
  String get hongbaohuodong => 'hongbaohuodong'.tr;
  String get xiangqing => 'xiangqing'.tr;
  String get qingxiandenglu => 'qingxiandenglu'.tr;
  String get jingqingqidai => 'jingqingqidai'.tr;
  String get denglugengjingcai => 'denglugengjingcai'.tr;
  String get gengduo => 'gengduo'.tr;
  String get huishou => 'huishou'.tr;
  String get sishiershuzihuozimu => 'sishiershuzihuozimu'.tr;
  String get bashiershuzihuozimu => 'bashiershuzihuozimu'.tr;
  String get zhenshixingmingbunengkong => 'huishou'.tr;
  String get yanzhengmabunengkong => 'yanzhengmabunengkong'.tr;
  String get mimashurubuyizhi => 'mimashurubuyizhi'.tr;
  String get usdt_coin => 'usdt_coin'.tr;
  String get lianxizaixiankefu => 'lianxizaixiankefu'.tr;
  String get shuruzhuanzhangqianbao => 'shuruzhuanzhangqianbao'.tr;
  String get yiwanchengtijiaorukuan => 'yiwanchengtijiaorukuan'.tr;
  String get qianbaodizhi => 'qianbaodizhi'.tr;
  String get shifoujinxingzhuanzhang => 'shifoujinxingzhuanzhang'.tr;
  String get tishi => 'tishi'.tr;
  String get yinhangmingcheng => 'yinhangmingcheng'.tr;
  String get xuanzhezhifuyinhang => 'xuanzhezhifuyinhang'.tr;
  String zhifutiaozhuan_(List<String> args) => 'zhifutiaozhuan'.trArgs(args);
  String get quedingtijiaodingdan => 'quedingtijiaodingdan'.tr;
  String get caozuochenggong => 'caozuochenggong'.tr;
  String get zhuzhanghao => 'zhuzhanghao'.tr;
  String get qingxuanzhezhuanru => 'qingxuanzhezhuanru'.tr;
  String get qingxuanzhezhuanchu => 'qingxuanzhezhuanchu'.tr;
  String shixiaokouchu_(List<String> args) => 'shixiaokouchu'.trArgs(args);
  String shixiaomianshou_(List<String> args) => 'shixiaomianshou'.trArgs(args);
  String get qingxuanzhetikuanzhanghu => 'qingxuanzhetikuanzhanghu'.tr;
  String get dianjitianjiazhanghu => 'dianjitianjiazhanghu'.tr;
  String get ninhaimeibangdingyhkzhanghu => 'ninhaimeibangdingyhkzhanghu'.tr;
  String get ninhaimeibangdingusdtzhanghu => 'ninhaimeibangdingusdtzhanghu'.tr;
  String get ninhaimeibangdingqianbao => 'ninhaimeibangdingqianbao'.tr;
  String get qubangding => 'qubangding'.tr;
  String get chukuanzhanghu => 'chukuanzhanghu'.tr;
  String get kaihudizhi => 'kaihudizhi'.tr;
  String get yanzhengchukuanmima => 'yanzhengchukuanmima'.tr;
  String get shuruyinhangkakaihudizhi => 'shuruyinhangkakaihudizhi'.tr;
  String get liudao12weishuzihuozimu => 'liudao12weishuzihuozimu'.tr;
  String get yigezhanghaosanzhangyinhangka => 'yigezhanghaosanzhangyinhangka'.tr;
  String get qingshuruqukuanmima => 'qingshuruqukuanmima'.tr;
  String get qianbaoxieyi => 'qianbaoxieyi'.tr;
  String get yanzhengzijinmima => 'yanzhengzijinmima'.tr;
  String get qingshuruqianbaodizhi => 'qingshuruqianbaodizhi'.tr;
  String get chukuanyinhang => 'chukuanyinhang'.tr;
  String get shuruyinhangzhanghao => 'shuruyinhangzhanghao'.tr;
  String get qingxuanzhechukuanyinhang => 'qingxuanzhechukuanyinhang'.tr;
  String get qingshuruchukuanmima => 'qingshuruchukuanmima'.tr;
  String get trc20_show => 'trc20_show'.tr;
  String get erc20_show => 'erc20_show'.tr;
  String get omni_show => 'omni_show'.tr;
  String get tuiguanghongli => 'tuiguanghongli'.tr;
  String get sidao12shuzihuozimu => 'sidao12shuzihuozimu'.tr;
  String get mimacuowu => 'mimacuowu'.tr;
  String get zhanghaomimadenglu => 'zhanghaomimadenglu'.tr;
  String get chongzhijymm => 'chongzhijymm'.tr;
  String get chongzhijymmtishi => 'chongzhijymmtishi'.tr;
  String get qingzaiciyanzhenghaxizhi => 'qingzaiciyanzhenghaxizhi'.tr;
  String get baocunchenggong => 'baocunchenggong'.tr;
  String get geshangqi => 'geshangqi'.tr;
  String get jinrikai => 'jinrikai'.tr;
  String get wodeshoucang => 'wodeshoucang'.tr;
  String get lianxiwomen => 'lianxiwomen'.tr;
  String get guojizhan2023 => '2023guojizhan'.tr;
  String get yingyongneijiazai => 'yingyongneijiazai'.tr;
  String get liulanqidakai => 'liulanqidakai'.tr;
  String get biaozhunshijian => 'biaozhunshijian'.tr;
  String get yiqiandao => 'yiqiandao'.tr;
  String get zhuninxiacizdj => 'zhuninxiacizdj'.tr;
  String get jiangjinfengfu => 'jiangjinfengfu'.tr;
  String get dengdaikaipan => 'dengdaikaipan'.tr;
  String get weihuzhong => 'weihuzhong'.tr;
  String get yiguanpan => 'yiguanpan'.tr;
  String get yixiushi => 'yixiushi'.tr;
  String get huizhijiesuo => 'huizhijiesuo'.tr;
  String yichenggongqiehuan_(List<String> args) => 'yichenggongqiehuan_'.trArgs(args);
  String get jifenbuzu => 'jifenbuzu'.tr;
  String get chonxinshezhi => 'chonxinshezhi'.tr;
  String get huizhisige => 'huizhisige'.tr;
  String get huizhibuyiyang => 'huizhibuyiyang'.tr;
  String get zaicihuizhi => 'zaicihuizhi'.tr;
  // String get yingyongneijiazai => 'yingyongneijiazai'.tr;
  String get bangdingqitaqianbao => 'bangdingqitaqianbao'.tr;
  String wodeqitaqianbao_(List<String> args) => 'wodeqitaqianbao'.trArgs(args);
  String zuiduoketianjiaqianbao_(List<String> args) => 'zuiduoketianjiaqianbao'.trArgs(args);
  String get qitaqianbaowenxintis => 'qitaqianbaowenxintis'.tr;
  String get qianbaoleixing => 'qianbaoleixing'.tr;
  String get tixianfangshi => 'tixianfangshi'.tr;
  String get yhk => 'yhk'.tr;
  String xqianbao_(List<String> args) => 'xqianbao'.trArgs(args);
  String xianlu_(List<String> args) => 'xianlu_'.trArgs(args);
  String get entry => 'entry'.tr;
  String julifengpanshijian(List<String> args) => 'julifengpanshijian'.trArgs(args);
  String get no => "no".tr;
  String get fengpanxinxi => "fengpanxinxi".tr;
  String get kaishifengpan => "kaishifengpan".tr;
  String get lianjiefuwushibai => "kaishifengpan".tr;
  String get kaijiangzhong => "kaijiangzhong".tr;
  String get agent_password_tip => "agent_password_tip".tr;














  @override
  Map<String, Map<String, String>> get keys => {
    'zh_ZH':CN.map,
    'en':EN.map,
    'vi':VI.map,
  };
  Map<String,String> initEn(){
    Map<String,String> map={};

    return map;
  }

  Map<String,String> initCN(){
    Map<String,String> map={};

    return map;
  }
  Map<String,String> initVI(){
    Map<String,String> map={};

    return map;
  }
}

