name: app04
description: nothing to say.

version: 1.0.6

environment:
  sdk: ">=2.16.1 <3.3.6"

dependencies:
  aone_common:
    path: ../../packages/common
  fortune_wheel:
    path: ../../packages/fortune_wheel
  red_task:
    path: ../../packages/red_task
  scrollable_positioned_list:
    path: ../../packages/scrollable_positioned_list
  aone_locales:
    path: ../../packages/aone_locales
  aone_widget:
    path: ../../packages/aone_widget
  generics:
    path: ../../modules/generics

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  animations: 2.0.1
  flutter_datetime_picker: 1.5.1
  carousel_indicator: ^1.0.6
  get: ^4.6.1
  flutter_screenutil: ^5.5.3+2
  tuple: ^2.0.0
  flutter_star: ^1.0.2
  extended_image: ^6.0.2+1
  flutter_form_builder: ^7.1.1
  #form_builder_validators: ^7.8.0
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  flutter_swipe_action_cell: ^2.2.0
  flutter_svg: ^1.0.3
  sticky_headers: ^0.2.0
  flutter_smart_dialog: ^3.4.2+2
  hidden_drawer_menu: ^3.0.1
  webview_flutter: ^3.0.2
  getwidget: ^2.0.5
  dropdown_button2: ^1.4.0
  
  # toast 通知 hud 等
  flutter_easyloading: ^3.0.5
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  flutter_easyrefresh: ^2.2.2
  flutter_advanced_drawer: ^1.3.2
  lottie: ^1.2.2
  infinite_scroll_pagination: 3.1.0
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  dokit: ^0.8.0-nullsafety.0
  flutter_html: ^3.0.0-alpha.6
  cached_network_image: ^3.2.0
  expandable: ^5.0.1
  keframe: ^2.0.6
  flutter_staggered_animations: ^1.0.0
  popup_window: ^1.0.0+3
  auto_size_text: ^3.0.0
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.2
  card_swiper: ^2.0.3
  flutter_spinkit: ^5.1.0
  gif: ^2.2.0
  sentry_flutter: ^6.15.1
  flutter_widget_from_html: ^0.9.1
  flutter_inappwebview: ^5.7.2+3



dev_dependencies:
  flutter_lints: ^1.0.0
  
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/home/
    - assets/images/common/
    - assets/images/tabbar/
    - assets/images/login/
    - assets/images/promocenter/
    - assets/images/promocenter/h09/
    - assets/images/promocenter/h18/
    - assets/images/user/
    - assets/json/
    - assets/images/activity/
    - assets/images/activity/task_center/
    - assets/images/activity/task_center/h09/
    - assets/images/activity/task_center/h18/
    - assets/images/activity/vip_center/
    - assets/images/activity/sign/
    - assets/images/game_init/
    - assets/images/game_help/
    - assets/images/register/
    - assets/images/recharge/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
