class EN {
  static const Map<String, String> map = {
    "home_home": "Home",
    "home_discount": "Promos",
    "home_recharge": "Deposit",
    "home_kefu": "Customer",
    "home_mine": "Account",
    "mine_name": "Personal Account",
    "mine_eduzhuanhuanu": "Balance Convert",
    "mine_zijinjiaoyi": "Transaction History",
    "mine_touzhujilu": "Bet History",
    "mine_jifenjilu": "Credit Records",
    "mine_huiyuanfanshui": "Rebate History",
    "mine_hongbaohejiangjin": "Red Pocket & Bonus",
    "mine_tuiguangzhuanqian": "Earn With Us",
    "mine_setting": "Settings",
    "mine_tixian": "Withdraw",
    "mine_rukuan": "Deposit",
    "mine_tixian_other": "Withdraw From %s",
    "mine_tixian_usdt": "Withdraw From USDT",
    "mine_main_account": "Main Currency",
    "mine_jiangjin": "Bonus",
    "mine_jifen": "Credit",
    "kefu_kefu": "Customer Support",
    "discount_discount": "Promotions",
    "discount_discount_detail": "优惠内容",
    "discount_coming": "Enter",
    "discount_back": "Back",
    "sure": "Submit",
    "nick": "Nickname:",
    "phone": "Mobile:",

    "qq_number": "QQ:",
    "wx_number": "Wechat:",
    "e_mail": "Email:",
    "e_mail_tip": "Enter Email address",
    "wx_number_tip": "Enter Wechat ID",
    "qq_number_tip": "Enter QQ number",
    "phone_tip": "Enter mobile number",
    "home_show_game": "Show All",
    "home_start_game": "Play Now",
    "game_room_odds_message": "Game Odds",
    "dialog_see_more": "Submit",
    "dialog_text_switch_money": "选择要切换的钱包",
    "back": "Back",
    "no_more": "- You've reached the end -",
    "empty_no_data": "空空如也",
    "account_setting": "Settings",
    "setting_banding_bank_str": "Enroll Bank Card",
    "setting_banding_usdt_str": "Enroll USDT",
    "setting_banding_cgp_str": "绑定CGPay",
    "setting_set_tixian_password_str": "Set Withdrawal Password",
    "setting_set_login_password_str": "Set Login Password",
    "account_please_input_bank_name": "请输入银行卡姓名",
    "account_bank_account_acc": "Bank Card Number:",
    "account_bank_account_bank": "Bank Name:",
    "account_please_input_bank_number": "Enter the card number",
    "account_bank_address": "Bank Address:",
    "account_please_select": "Select",
    "account_bank_password": "Withdrawal Password：",
    "account_bank_chukuan_password": "请输入出款密码",
    "account_usdt_trc20": "USDT-TRC20(TRON):",
    "account_usdt_ERC20": "USDT-ERC20:",
    "account_usdt_Omini": "USDT-Omini:",
    "account_banding_cgp": "CGPay:",
    "account_banding_cgp_tip": "Enter the Wallet address",
    "account_set_password_old": "Current Withdrawal Password:",
    "account_set_password_old_tip": "Enter current password",
    "account_set_password_old_tip_2": "Enter current password",
    "account_set_password_new": "New Password:",
    "account_set_password_new_tip": "输入6-12位新提现密码",
    "account_set_password_new_tip_2": "8-12 letters and numbers",
    "account_set_password_new_sure": "Confirm New Password:",
    "account_set_password_new_sure_tip": "Re-enter new password",
    "account_set_password_new_sure_tip_2": "Re-enter new password",
    "message_center": "News",
    "message_notice": "Notifications",
    "message_message": "Messages",
    "sp_daima": "Code:",
    "sp_link": "Link:",
    "sp_user_message": "Referrer Profile",
    "sp_promotion_qr": "QR Code",
    "qur_promotion_recode": "Check Earning Statement",
    "copy_link": "Copy Link",
    "save_img": "Save Image",
    "down_which_qur_time": "Please select date & time below",
    "pro_time_tip": " * Current Time (CST)= Eastern Time (EST)+12:00",
    "time_meifong": "日期（美东）",
    "time_meifong_2": "投注日期（美东时间）",
    "jiaoyi_leibie": "Transaction Type",
    "jiaoyi_edu": "Credit Amount",
    "xianyou_edu": "Available Balance",
    "mine_fu_return_water": "Loss Rebate",
    "mine_fu_water_tip": "Rebate Instructions",
    "game_type": "Game Type",
    "effective_tz": "Valid Bet",
    "win_or_fail": "Win",
    "return_water": "Rebate",
    "other_game_type": "其他游戏",
    "mine_tz_return_water": "Bet Rebate",
    "todata_tz_zh": "Today's Bet Combo Rate",
    "pc_28": "PC28蛋蛋",
    "agent_user_name": "Username:",
    "agent_user_password": "Password:",
    "really_name": "Full Name:",
    "really_name2": "Full Name:",
    "agent_user_tip": "4-12 letters and numbers",
    "agent_password_tip": "8-12 letters and numbers",
    "agent_really_tip": "Same as per your bank account",
    "agent_phone_tip": "Enter a verified mobile number",
    "agent_qq_tip": "Enter QQ number",
    "agent_email_tip": "Enter Email address",
    "agent_bank_tip": "Please select",
    "agent_bank_address_tip": "Please select",
    "cny_money_type": "CNY",
    "into_money": "IN",
    "recycling_money": "OUT",
    "game_th": "TH",
    "game_ag": "AG",
    "show_all_type": "Show All",
    "close_all_type": "Hide Panel",
    "game_bbin": "BBIN",
    "edu_all_type_tip": "All Accounts Balance",
    "edu_into_and_out_tip": "选择转账账户 和 输入转账金额",
    "input_chance_money": "输入转换金额",
    "start_chance": "Start Convert",
    "start_chance2": "Start Convert",
    "yijina_guiji": "Collect All to Main Currency",
    "xiaz_detail": "Bet Details",
    "night_theme": "Dark Mode",
    "day_theme": "Light Mode",
    "out_app": "Log out",
    "china_str": "中文",
    "vi_str": "Việt Nam",
    "open_music": "Music",
    "close_music": "Music is turned off",
    "open_tip_misic": "Tones",
    "close_tip_misic": "Tones is turned off",
    "online": "Automatic",
    "downline": "Manual",
    "zf_cz_account": "Username:",
    "zf_normal_online_edt_tip": "Enter manually or select from below amounts",
    "zf_cz_history": "Deposit History",
    "zf_huikuan_name": "Remitter's Name:",
    "zf_huikuan_name_tip": "Enter the name of the Remitter",
    "zf_huikuan_money": "Amount of deposit:",
    "zf_huikuan_money_tip": "Enter the amount to deposit",
    "zf_yinhang_name": "Bank Name:",
    "zf_yinhang_name_tip": "Please select the bank of deposit",
    "zf_yinhang_huikuan_type": "Deposit Method:",
    "zf_yinhang_huikuan_type_tip": "Please select a method to deposit",
    "bill_detail": "Transaction Info",
    "zf_commit_ok_tip": "Please wait up to 3 mins then refresh the page for the transaction status",
    "zf_cz_name": "Username",
    "zf_cz_name2": "Username",
    "zf_cz_bill_number": "Transaction Number",
    "zf_cz_commit_time": "Submit Date/Time",
    "zf_cz_money_number": "Amount of Deposit",
    "commit_ok": "Submitted successfully",
    "all_way": "All Methods",
    "all_status": "All Status",
    "today": "Today",
    "fast": "Fast",
    "normal": "Normal",
    "slow": "Slow",
    "do_no_use": "Unavailable",
    "entry": "Enter",
    "please_game_name": "Search for games",
    "modify_data": "Complete Profile",
    "sure_jihe_message": "Audit Info Confirmation",
    "sure_tixian_message": "确认提现账户信息",
    "continue_tixian": "Continue",
    "tx_money": "Amount of Withdraw",
    "tx_password": "Withdrawal Password",
    "tx_input_money": "Withdrawal Amount",
    "sure_money": "Confirm Amount",
    "tx_money_tip": "Enter amount of withdraw",
    "other_money": "Convenience Fee",
    "realy_get_money": "Actual Amount of Withdraw",
    "change_avater": "Edit Profile Image",
    "about_us": "About Us",
    "play_tip_message": "Game Rules",
    "mine_tuiguanghistory": "Earning Statement",
    "downline_user": "Downline Distributor",
    "downline_user_money": "Distributor Deposit",
    "gethongli": "Commission",
    "huiyuanlist": "Distributor List",
    "up_page": "Prev",
    "down_page": "Next",
    "nodata_promation": "No one in here",
    "mine_agent": "Join Affiliate",
    "kaijiang_trend": "Tendency",
    "sign_in_get_money": "Reward",
    "point_lot": "Spin to Win",
    "go_play": "Bet Now",
    "trend_chart": "Tendency",
    "history_result": "Results",
    "point_sign_in": "Daily Login Reward",
    "point_wheel": "Spin to Win",
    "loading": "加载中...",
    "please_input_old_password": "请输入旧密码",
    "please_input_new_password": "请输入新密码",
    "please_input_new_again_password": "请输入确认密码",
    "new_err_password": "The two entered passwords do not match",
    "notice_please": "敬请注意",
    "wallet": " wallet",
    "plan_close": "Bet closed",
    "plan_waiting": "Start soon",
    "select_in_acc": "Select an account to convert in",
    "rate": "Exchange rates：",
    "account": "Account",
    "record_all": "All records",
    "record_cun_ti": "Deposit/Withdraw",
    "record_zhuanzhang": "Transfer",
    "yesterday": "Yesterday",
    "seven_day": "Last 7 days",
    "shi_wu_day": "Last 15 days",
    "app_brvah_loading": "正在加载中...",
    "app_brvah_load_end": "没有更多数据",
    "app_brvah_load_failed": "加载失败...",
    "app_brvah_load_complete": "点击加载更多",
    "en_str": "英文",
    "ko_str": "韩国",
    "ind_str": "印度",
    "with_sys_str": "跟随系统",
    "hello_welcome": "您好，欢迎光临",
    "please_input_addr": "请输入开户地址",
    "please_sele_bank": "请选择银行卡",
    "please_hua_dong": "请滑动验证",
    "user_mess_is_empty": "用户信息不能为空",
    "please_login": "Please log in first.",
    "card_number": "Card Number",
    "has_card_user": "Cardholder's Name",
    "click_bank_band": "Add Card",
    "max_three_card": "(Maximum up to 3)",
    "bank_message_tip": "  ",
    "wallet_addr": "Wallet Address",
    "xieyi_o": "Network",
    "us_message_tip": " ",
    "wa_yixie": "Wallet Network:",
    "xieyi": "Network",
    "click_bank_band_us": "Add USDT Wallet",
    "wa_mu": "钱包额度互转",
    "change_money": "Amount of Exchange:",
    "input_money_change": "Enter the amount",
    "rate_maybe": "Reference Exchange Rate：",
    "realy_get_money_2": "Actual Amount of Exchange:",
    "copy_suc": "Copied",
    "all_day_service": "Serving you for more fun!",
    "hello": "Hi ",
    "defult_av": "Default",
    "ava_qq": "QQ",
    "ava_good": "Featured",
    "pay_to": "充值到",
    "zf_jump": "Click here if done with the transaction",
    "pa_tip": "Payment Instructions：",
    "mark": "Remark",
    "bank_branch": "Bank Branch",
    "has_card_name": "Card Holder",
    "password_no_same": "The two entered passwords do not match",
    "promotion_sp_tip": " ",
    "sele_wa_agreement": "Please select network",
    "look_message_and_pay": "Check the Receiver's INFO, and proceed to transfer",
    "need_input_message_about_me": "Please complete the info after transaction",
    "hongbao_ad": "红包活动",
    "reminder": "Reminder",
    "online_remark_tip_one": "1.APP会自动打开一个页面，请按提示继续操作。",
    "online_remark_tip_two_or_three": "2.Convenience fee %1\$s,Speed Withdraw",
    "down_tip_one": "1. Please complete the transfer within the time limit.",
    "sure_commit_order": "Ready to submit?",
    "com_tip": "Reminder",
    "com_cancel": "Cancel",
    "sure2": "Submit",
    "sure_zhuangzhang": "Transaction completed?",
    "switch_zf_way": "Change deposit method",
    "wheel_fail": "摇奖失败",
    "point_wheel_integral": "  ",
    "cur_m_has_num": "本月已签到%1\$s次，剩余积分%2\$s",
    "with_bank_tip": "提现银行卡",
    "click_to_bank": "点击绑定银行卡",
    "sele_tix_wa": "选择提现钱包",
    "sele_tix_bank": "选择提现银行卡",
    "click_to_usdt": "点击绑定钱包地址",
    "with_u_tip": "提现钱包：",
    "date": "Date",
    "effective_betting_water": "Valid Bet",
    "win_or_lose_water": "Win",
    "hui_water": "Rebate",
    "combinbetradio": "Bet Combo Rate",
    "h_hui_water": "Rebate History",
    "hasCardUser": "Card Holder",
    "my_fav": "Favorites",
    "game_name": "Game Name",
    "num_all": "No. of Entries",
    "tz_num": "Bet Amount",
    "tz_time": "Bet Date",
    "all": "All",
    "hongbao_number": "Amount",
    "need_dama": "Minimum Bet Amount",
    "has_av_time": "Validity",
    "status": "Status",
    "jiangjin_number": "bonus",
    "open_plat": "Activate",
    "main_money": "Main Currency",
    "mine_about": "About Us",
    "about": "About Us",
    "home_show_game_hide": "Hide panel",
    "home_mianze_notice": "Terms and Conditions",
    "home_jishu_sur": "Technical Support",
    "home_fang_jijie": "Anti-Hijacking Guide",
    "copy_number": "Copy",
    "once_to_chat": "Chat now",
    "go_banding": "Enroll",
    "please_banding_bank": "You have not enrolled for a Bank Card yet",
    "please_banding_usdt": "You have not enrolled for a USDT Wallet yet",
    "houdong_longtime": "Ongoing",
    "houdong_off": "Expired by",
    "tourist": "Guest",
    "hongbao_weijihuo": "Inactivated",
    "hongbao_tiqu": "Activated",
    "hongbao_tiqu2": "Claim",
    "hongbao_yitiqu": "Claimed",
    "hongbao_yishixiao": "Expired",
    "home_hongbao_no_login": "Please log in to win Red pocket, good luck!",
    "home_hongbao_wei_kaishi": "Start soon",
    "homn_hongbao_jinxing": "On-going",
    "home_hongbao_yijishu": "Over",
    "home_huiodong_rule": "Spin Guide",
    "home_jiangjin_tiqu": "Claim Bonus",
    "jihe_tip1": "Valid bet amount after withdraw and the first deposit：",
    "jihe_tip_2_1": "Clear, no deposit bonus to be deducted！",
    "jihe_tip_2_2": "Faild to pass promotion audit, bonus will be deducted ",
    "jihe_tip_3_1": "Clear, no administration fee to be charged！",
    "jihe_tip_3_2": "Fail to pass normal audit, adminstration fee will be deducted ",
    "jihe_changtai": "Promotion audit:",
    "jihe_youhui": "Promotion audit:",
    "jihe_duocitixian": "Multi- withdraw convenience fee:",
    "jihe_shixiao": "Timeliness Service Charge:",
    "jihe_tip_4_1": "Free of charge",
    "jihe_tip_5": "Withdraw Audit Time:Eastern Time (EST)",
    "jihe_tip_7_1": "Withdraw within %1\$s H from the latest deposit,the withdrawal amount will be deducted %2\$s Convenience Fee",
    "jihe_tip_6_1": "%1\$s Hours %2\$s times withdraw,convenience fee will be deducted: %3\$s",
    "jihe_tip_6_2": "%1\$s Hours %2\$s times withdraw,free of charge",
    "tikuan_tip_1": "请输入提款金额",
    "tikuan_tip_2": "请输入提款密码",
    "tikuan_tip_3": "请选择提款账号",
    "tikuan_tip_4": "可到账金额必须大于0",
    "zf_yh_down_tip_2": "Please complete the remmittance details once the transaction has been made",
    "zf_shuoming": "Payment Instructions：",
    "zf_shuoming_content": "\\n 1. Please enter the amount to deposit or other amounts, select the bank and click to submit \\n2.The system will automatically redirect to the payment webpage, please follow the instructions and select payment method \\n3.You can pay by means of Online Banking, Scan to Pay, etc \\n 4.Once the transaction was sucessfully proceeded, please back in the APP manually \\n5.The deposit amount will be automatically added to your account. Should you have any inquiry or meet any failure, please contact Customer Support at any time",
    "zf_online_tip_1": "Please click the link below and follow the instructions",
    "zf_online_tip_2": "Enter the amount ( %1\$s -  %2\$s ) click to submit",
    "user_password_resure": "Confirm Password:",
    "agent_reg_tip_1": "1.* The field is required",
    "agent_reg_tip_2": "2.By submitting above, you agree to our Terms and Conditions, privacy policy, and cookies.",
    "agent_reg_tip_3": "Terms and Conditions",
    "ust_tip_1": "Each user can enroll maximum up to 3 USDT Wallets (Up to 1 wallet per Network.)",
    "link_kefu": "Customer Support",
    "tingyong_termi": "Terminated",
    "bank_tip_1": "Cardholder's name should be exactly same as the full name submitted when sign up, otherwise the withdraw will be denied.",
    "bank_tip_2": "Each user can enroll maximum up to 3 bank cards",
    "bank_tip_3": "Cannot be changed once enrolled,For any modification, please kindly approach %1\$s",
    "bank_tip_3_2": "Cannot be changed once enrolled,For any modification, please kindly approach %1\$s",
    "bank_set_passw": "Set Withdrawal Password：",
    "bank_yanz_passw": "Withdrawal Password：",
    "bank_chukuan_mima_tip": "6-12 characters (accept only numbers and letters)",
    "long_pre_to_copy": "1.长按号码可以复制到剪切板；",
    "checkin_tip_1": "The days of this month sucessfully logged in %1\$s times,+ %2\$s credits",
    "mod_user_tip1": 'Please refer to feature "Account - Settings - Enroll Bank Card" to complete bank profile and withdrawal password setting before withdraw',
    "mod_user_tip2": "Should you have any inquiry, please contact Cutomer Support at any time",
    "edu_main_money": "Main Currency",
    "select_out_acc": "Select an account to convert out",
    "us_shoukuan_a": "Receiver's Account",





    "day_yi":"Mon",
    "day_er":"Tue",
    "day_san":"Wed",
    "day_si":"Thur",
    "day_wu":"Fri",
    "day_liu":"Sat",
    "day_ri":"Sun",
    "bet_da":"Big",
    "bet_xiao":"Small",
    "bet_dan":"Odd",
    "bet_shuang":"Even",
    "di":"No.",
    "qi":"",
    "shifoutuichudenglu":"Confirm Logout",

    "huizhijiesuo":"Draw unlock pattern",
    "chonxinshezhi":"Reset",
    "huizhisige":"Please draw at least four points",
    "huizhibuyiyang":"Please redraw if it is inconsistent with the last drawing",
    "zaicihuizhi":"Draw the unlock pattern again",
    "shifouchongxinhuizhi":"Do you want to redraw the unlock pattern?",


    "fangwenluxian":"Select an access",
    "kuai":"Fast",
    "yiban":"Normal",
    "henman":"Slow",
    "bukeyong":"Unavailable",





    "gaunyuwomen": "About Us",
    "guanwangjieshao": "官网介绍",
    "xiazhaiyingyong": "Download App",
    "pingtaifuwu": "平台服务",
    "yonghuzhongxin": "User Center",
    "huiyuan": "会员",
    "chongzhijilu": "Deposit History",
    "qiandaochoujiang": "Reward",
    "jishuzhichi": "Technical Support",
    "fangjiechijiaocheng": "Anti-Hijacking Guide",
    "fangjiechi": "Anti-Hijacking",
    "shiyongbangzhu": "Help",
    "xuanzeyuyan":"Select language",
    "duanyu":"短语",
    "changyong":"Often",
    "zayu":"杂语",
    "biaoqing":"Emoji",
    "gif":"GIF",

    "yue_":"Balance：",
    "home": "Home",
    "mine": "Account",
    "preferential": "Promos",
    "charge": "Deposit",
    "tixian": "Withdraw",
    "choujiang": "Spin",
    "zoushi": "Tendency",
    "customer_service": "Customer",
    "theme": "主题",
    "pick_time": "Select Time",
    "remen": "Popular",
    "zuijin": "Recent",
    "shoucang": "Favourite",
    "shedingyuyan":'*Please select the default language, you can set it later in "More" or "My-Settings',
    "morenyuyan":"Default language",
    "tiaoguo":"Skip",
    "queren":"Confirm",
    "xuanzeqianbao":"Select a wallet",
    "morenqianbao":"Default wallet",
    "shedingqianbao":'*Please select the default wallet, you can set it later in "More" or "My Wallet"',
    "rmb":"人民币（CNY）",
    "dollar":"美元（US）",
    "thb":"泰铢（Thai Baht）",
    "vnd":"越南盾（VND）",
    "hyld_boya":"Welcome to BOYA CASINO",
    "hyld_dw":"Welcome to DW International",
    "hyld_shouxin":"Welcome to SHOUXIN CASINO",
    "hyld_aomen":"Welcome to MACAU CASINO",
    "hyld_fuyuan":"Welcome to FUYUAN CASINO",
    "hyld_gdvip":"Welcome to Guangdong Club",
    "hyld_leyou":"Welcome to Leyou Casino",
    "hyld_jsgj":"Welcome to JIANGSHAN CASINO",
    "hyld_longmen":"Welcome to LONGMEN CASINO",
    "qqzlxd":"The world's leading entertainment platform",
    "register":"Register",
    "login":"Login",
    "grzx":"Personal Account",
    "rmbqb":"人民币钱包",
    "edzh":"Balance Convert",
    "pcxq":"PC details",
    "tzjl": "Betting details",
    "jymm":"Simple password",
    "dyy":"Multi-Language",
    "bjyy":"Background music",
    "tsy":"Notification sounds",
    "wgys":"Appearance color",
    "qs":"Light color",
    "dx":"Animation",
    "qk":"On all",
    "fxghy":"Share to friends",
    "ycfx":"One share, unlimited commissio",
    "xzapp":"Download APP",
    "lxjbhb":"Enjoy 888 Red envelope immediately",
    "logout":"Exit",
    "xzndyy":"Select your language",
    "sszcbz":"搜索支持币种",
    "zxndbz":"选择您的币种",
    "bbdh":"Exchange",
    "lxkf":"Customer Service",
    "yhm":"Username:",
    "qsryhm":"请输入用户名",
    "mm":"Password",
    "qsrmm":"请输入密码",
    "wjmm":"Forgot your password?",
    "cjygzxh":"创建一个新账户",
    "kfzx":"Customer Support",
    "xszxkf":"24小时在线客服",
    "qthwnfw":"Serving you for more fun!",
    "djjr":"点击进入",
    "dxtxsz":"Reminder settings",
    "fpdx":"Closing animation",
    "cksl":"View Example",
    "kjjgdx":"Lottery result animation",
    "djsdx":"Countdown animation",
    "wgsz":"Appearance Settings",
    "qzb": "White",
    "kxh":"Black",
    "cjzh":"创建账户",
    "hyzc":"SIGN UP",
    "wszhzm":"8-12 letters and numbers",
    "zsxm":"Full Name:",
    "yzm":"Verification Code:",
    "qsrzcyzm":"Verification Code",
    "wywdbty":"By submitting above, you agree to our Terms and Conditions, privacy policy, and cookies.",
    "yhtk":"《用户条款》",
    "and":"和",
    "ysxy":"《隐私协议》",
    "yyzh":"已有账户?",
    "ytxyhkhmyz":"Same as per your bank account",
    "tab_pcfj":"PC房间",
    "tab_cp":"彩票",
    "tab_zr":"真人",
    "tab_ty":"体育",
    "tab_by":"捕鱼",
    "tab_dz":"电子",
    "card_ptf":"普通房",
    "card_gjf":"高级房",
    "card_gbf":"贵宾房",
    "dangqianzaixian":"%s|%s",
    "peilvshuoming":"Game Odds",
    "wanfaguizhe":"Game Rules",
    "youxishuyu":"Gaming Terminology",
    "xiazhujiqiao":"Betting Tips",
    "wanfaguizhe_jieshao":"给大家介绍下玩法规则,为了游…",
    "youxishuyu_jieshao":"了解常用的术语后提高游戏效…",
    "xiazhujiqiao_jieshao":"以下是一些下注的技巧,例如…",
    "haoyuan":"Source",
    "zhudan":"Bet Slip",
    "mipai":"Squeeze",
    "qushi":"Tendency",
    "juelidixqi":" No.%s",
    "zongyue":"Balance",
    "touzhu":"Bet",
    "zhudan_":"Bet Slip",
    "zongji_":"，Total：",
    "qiehuanfangjian":"切换房间",
    "confirm":"Confirm",
    "cancel":"Cancel",
    "tema":"Special No.",
    "diyiqiu":"1st",
    "dierqiu":"2nd",
    "disanqiu":"3rd",
    "qingshurujine":"Enter the amount",
    "zongji":"Total",
    "end":"Over",
    "xiazhuxiangqing":"Bet Details",
    "quanbujilu":"All records",
    "xiazhujine":"Bet Amount",
    "keyingjine":"Prize",
    "xiaoji":"Subtotal",
    "xbi":"%s No. of Entries",
    "qihao_":"Draw Number:%s",
    "wallet_cny":"CNY",
    "wallet_usdt":"USDT",
    "danhao":"Bet Slip",
    "neirong":"Details",
    "guanfanghaoyuan":"Result Source",
    "jianghaozhanshi":"Result Display",
    "jianghaoshuoming":"Result Details",
    "gongjujiaoyan":"Validator",
    "daojishi":"Countdown",
    "qihao":"Draw Number",
    "kaijianghaoma":"Result",
    "haoyuanjinqi":"Source(Recent",
    "wanzhenghaoyuanzhanshi":"Full Source Display",
    "zhuaqushijian":"Grab Time：%s",
    "shuominghaoyuan":"Reminder: you can click the source unit to copy.",
    "bitebipc28quhaojizhi":"Bitcoin PC28 Result Instruction",
    "zhuahaoyuan":"Grab the account source and get unconfirmed transactions (random seed)",
    "sha256zhuanhua":"SHA256 conversion",
    "shijinzhizhuanhua":"Decimal conversion",
    "shengchengzuihzhonghaoma":"Generated final lottery numbers",
    "zhuahaoyuan_jieshao":"In the world's largest blockchain public network chain Bitcoin node, transactions occur every second. Before a new block is generated, these transactions are stored in the memory pool of each node for confirmation. In this memory pool, the digital information of each transaction: the remittance address, the remittance amount, and the receiving address are all represented by a 64-bit hexadecimal hash value. Because of the randomness of the trading market itself, the aggregation of all transaction information every second, that is, the aggregation of all hash values, is also random. This is the random seed of the bitcoin lottery, which is the unconfirmed transaction.",
    "sha256zhuanhua_jieshao":"The random seed obtained through step one is a summary of all transaction information at a certain point in time, that is, a combination of N 64-digit hexadecimal numbers. (Assuming X is the total amount of transactions that occurred at a certain point in time),After combining these numbers through the string combination operation, we can get a 64-bit hexadecimal number, which is counted as Y.Y is transformed by the SHA256 algorithm, which can be transformed into a new 64-bit hash value Z, and used for the next step of mathematical operations.",
    "shijinzhizhuanhua_jieshao":"After obtaining Z in step 2, take the first 16 digits, we can get a number A in the range of 0-2^64 through the decimal conversion formula, which is used to generate the final lottery number.",
    "shengchengzuihzhonghaoma_jieshao":"After obtaining A through step three, divide it by 2^64. Take the first 3 digits after the decimal point of the result to be the winning number.",
    "shuruduiyinghaoyuan":"Enter the related source",
    "jiaoyan":"Verify",
    "jiaoyanjieguo":"Result Verify",
    "sha256zhuanhuahzi":"SHA256 conversion value",
    "quqianshiliuwei":"Take the first 16 digits",
    "shijinweizhuanhuan":"Decimal conversion",
    "chuyierde64cifang":"divide it by 2^64",
    "zuizhongkaijianghaoma": "Final result",
    "shuoming":"Instruction",
    "shuoming_jieshao":"Users can query the website through the relevant online SHA256 function, copy all the hash value strings mentioned above, and make a query. The query URL is provided below:",
    "haoyuanchaxun":"Source Query",
    "dianjifuzhi":"Click to copy",
    "nowChat":"Chat now",
    "jiaoyanshuoming":"Verification Instructions",
    "jiaoyanshuoming1":"1.Grab the hash value collection of transactions in the latest time period, and spell it into a long digit string",
    "jiaoyanshuoming2":"2.Convert the above string to SHA256",
    "jiaoyanshuoming3":"3.TConvert through mathematical formulas, the conversion rules are as follows：",
    "jiaoyanshuoming4":"4.According to the conversion result, select 3 digits after the decimal point as the draw result",
    "dixqitouzhu":"No.%s,Bet: %s",
    "dixqikaijiang":"No.%s,Result: %s",
    "fengpanzhong":"Bet closed",
    "dengdaikaipan":"Start soon",
    "shuaxin":"Refresh",
    "kaijiangjieguo":"Result",
    "xitongxiaoxi":"Notification",
    "shujufenxi":"Analysis",
    "shuangmianchanglong":"Dragon Tail",
    "danshuangluzhu":"O/E Road",
    "daxiaoluzhu":"B/S Road",
    "haomazhoushi":"Tendency",
    "lx_tongji":"%s Total",
    "xianshiqishu_":"Draw Number Display：%s",
    "zhi":"Value",
    "jixiao":"Min",
    "jida":"Max",
    "bet_long":"Dragon",
    "bet_hu":"Tiger",
    "bet_he":"Tie",
    "dalu":"Big Road",
    "zhupanlu":"Bead Plate",
    "hao_value":"No.{value}",
    "qingshuruyouximingcheng":"Search for games",
    "xuanzhe":"Please select",
    "xuanzhexl":"选择线路",
    "quanbuyouxi":"All",
    "shoucangla":"收藏啦",
    "qiandaoyouli":"Reward",
    "jifen":"Credit",
    "benyueyiqian":"days logged in.%s",
    "zongjifen":"Total credits:",
    "lijiqiandao":"Reward",
    "yiqiandao":"Claimed",
    "jifenyaojiang":"Spin to Win",
    "jifenmeici":"Credits：%s(5 Credits/Spin)",
    "lianyao5":"5x",
    "lianyao10":"10x",
    "lianyao15":"15x",
    "lianyao20":"20x",
    "huodongguizhe":"Spin Guide",
    "jiangjintiqu":"Claim Bonus",
    "nianyueri":"yyyy-MM-dd",
    "bencijiangli":"This reward",
    "gongxiwancheng":"恭喜你完成任务",
    "xiaciqiandao":"下次签到奖励%s,可获得%s积分",
    "mingtianjixue":"明天继续",
    "gongxininhuode":"Congratulations, you have won",
    "jiangjin":"Bonus",
    "cishu":"Spin",
    "lishikaijiang":"Results",
    "kaijiangzhoushi":"Tendency",
    "qugoucai":"Bet Now",
    "goucai":"Bet Now",
    "xiaoxi":"Messages",
    "gonggao":"Notifications",
    "gonggaoxiangqing":"Notifications",
    "youhuizhongxin":"Promotions",
    "chongzhi":"Deposit",
    "quanbu":"All",
    "qita":"Others",
    "fanhui":"Back",
    "wenxintishi_fuzhi":"Reminder：\nLong press to copy",
    "chongzhizhongxin":"Recharge Center",
    "chongzhizhanghu_":"Recharge account: %s",
    "dangqianmoren":"%s(Current default)",
    "xianshang":"Automatic",
    "xianxia":"Manual",
    "diyibu_chakanshoukuanxinxi":"Check the Payee's INFO, and proceed to transfer",
    "wenxintishi_zhifuyoushijian":"Reminder: Please complete the transfer within the time limit.",
    "dierbu_tianchongdingdan":"Please complete the remmittance details once the transaction has been made",
    "chongzhizhanghu":"Username:",
    "huikuanxingming":"Remitter's Name:",
    "huikuanjine":"Amount of deposit:",
    "qingshuruhuikuanren":"Enter the name of the Remitter",
    "qingshuruhuikuanjine":"Enter the amount to deposit",
    "tijiao":"Submit",
    "bibiduihuan":"Exchange",
    "eduzhuanhuan":"Balance Convert",
    "zhifushuoming_rmb":"支付说明:\n1.公司帐户资金如何领取到个人帐户 人民币银行结算账户管理方法规定\n2.公司帐户资金如何领取到个人帐户 人民币银行结算账户管理方法规定",
    "zhifushuoming_wallet":"Payment Instructions:\n1.Please enter the amount to deposit or other amounts, select the bank and click to submit\n2.The system will automatically redirect to the payment webpage, please follow the instructions and select payment method\n3.You can pay by means of Online Banking, Scan to Pay, etc\n4.Once the transaction was sucessfully proceeded, please back in the APP manually\n5.The deposit amount will be automatically added to your account. Should you have any inquiry or meet any failure, please contact Customer Support at any time",
    "kahao":"Card Number",
    "cikaren":"Card Holder",
    "beizhu":"Remark",
    "dianjixiafangzhifu":"Please click the link below and follow the instructions",
    "wenxintishi_":"Reminder",
    "wenxintishi_1":"Click the link and follow the instructions",
    "wenxintishi_2":"Convenience fee %s%,Speed Withdraw!",
    "wenxintishi_3":"%s、%s",
    "tianrujine":"Enter the amount (%s-%s) click to submit",
    "shoudongshuruhuoxuanzhe":"Enter manually or select from below amounts",
    "diyibu_xuanzhezhifuxieyi":"Please select network",
    "dierbu_chakanshoukuanxinxi":"Check the Receiver's INFO, and proceed to transfer",
    "shoukuanzhanghu":"Receiver's Account",
    "disanbu_tianxierukuanxinxi":"Please complete the info after transaction",
    "fanhuishouye":"Return to homepage",
    "zhifushuoming_":"Payment Instructions:",
    "zhifushuoming_1":"1.Min Deposit Amount:1USDT，Max Deposit Amount: 10000 USDT;\n2.Please proceed with ",
    "zhifushuoming_2":"to deposit to Receiver's account. Capital loss may occur to loss when paying with other digital currencies;\n3.This address has been generated exclussively to you which can be used repeatedly. It is recommended to save the address for the convenience",
    "nicheng_":"Nickname：%s",
    "wodeqianbao":"My Wallet",
    "tixianmima":"Withdrawal Password",
    "zijinmingxi":"Transactions History",
    "bangdingyinhangka":"Enroll Bank Card",
    "bangdingusdt":"Enroll USDT Wallet",
    "wodetouzhu":"My betting details",
    "touzhujilu":"Bet History",
    "jifenjilu":"Credit Records",
    "huiyuanfanshui":"Rebate History",
    "hongbaohejiangjin":"Red Pocket & Bonus",
    "wodeyinli":"My Profit",
    "tuiguangzhuanqian":"Earn With Us",
    "dializhuce":"Join Affiliate",
    "tongyongshezhi":"General setting",
    "bangzhuzhongxin":"Help Center",
    "guanyuwomen":"About Us",
    "tixianzhongxin":"Withdraw center",
    "tixianzhanghu_":"Withdraw account: %s",
    "congcnyqianbaotichu":"Withdraw From CNY",
    "congusdtqianbaotichu":"Withdraw From USDT",
    "tixianxinxi":"Withdraw Details",
    "querentixianxinxi":"Confirm withdrawal details",
    "tixianjine":"Amount of Withdraw",
    "qingshurutixianmima":"Enter Withdrawal Password",
    "qingshurutixianjine":"Enter amount of withdraw",
    "querenjine":"Confirm Amount",
    "shouxufei":"Convenience Fee",
    "kedaozhangjine":"Actual Amount of Withdraw",
    "qingxuanzhetixianzhanghu":"Select withdrawal account",
    "querenjihexinxi":"Audit Info Confirmation",
    "zitixianhouzongtouzhu_":"Valid bet amount after withdraw and the first deposit: %s",
    "youhuijihe":"Promotion audit:",
    "meiyoutongguoyouhui":"Faild to pass promotion audit, bonus will be deducted %s",
    "tongguoyouhuijihe":"Clear, no deposit bonus to be deducted！",
    "changtaixingjihe":"Promotion audit:",
    "tongguochangtaixing":"Clear, no administration fee to be charged！",
    "meiyoutongguochangtaixing":"Fail to pass normal audit, adminstration fee will be deducted%s",
    "duocitixian":"Multi- withdraw convenience fee:",
    "yixiaoshineimian":"%s Hours %s times withdraw %s",
    "xukouchushouxufei":"Convenience fee will be deducted %s",
    "shixiaoshouxufei":"Timeliness Service Charge:",
    "mianshoushouxufei":"Free of charge",
    "shixiaokouchu":"Withdraw within %sH from the latest deposit,Convenience fee will be deducted %s",
    "shixiaomianshou":"Withdraw within %sH from the latest deposit,free of charge",
    "cichijiheshijian":"Withdraw Audit Time:",
    "meidongshijian_":"Eastern Time (EST) :%s",
    "jixutixian":"Continue",
    "tijiaochenggong":"Submit successfully",
    "tixianxiangqing":"Withdrawal details",
    "tixianzhanghu":"Withdrawal account",
    "tijiaoshijian":"Submission time",
    "shouxufei_":"(Convenience fee:%s)",
    "daozhangjine":"Amount received",
    "zhanghuyue":"Account Balance",
    "wancheng":"Done",
    "shezhi":"Settings",
    "gerenziliao":"Personal details",
    "shezhidenglumima":"Set Login Password",
    "shezhijianyimima":"Set simple password",
    "zhongwen":"中文",
    "quankai":"On all",
    "tuichudenglu":"Log out",
    "wanshanziliao":"Complete Profile",
    "nicheng":"Nickname:",
    "shoujihaoma":"Mobile:",
    "qqhaoma":"QQ:",
    "weixin":"Wechat:",
    "shuruweixinhao":"Enter Wechat ID",
    "shuruqqhaoma":"Enter QQ number",
    "shuruzhenshiyouxiao":"Enter mobile number",
    "shurudianziyouxiang":"Enter Email address",
    "shurunicheng":"Enter a nickname",
    "shezhitixianmima":"Set Withdrawal Password",
    "yuanmima":"Current Password：",
    "shuruyuantixianmima":"Enter current password",
    "xinmima":"New Password:",
    "shuruxintixianmima":"4-12 letters and numbers",
    "zaiciqueren":"Confirm New Password:",
    "chongfushuru":"Re-enter new password",
    "querenjianyimima":"确认简易密码",
    "shurujianyimima":"Enter a simple password",
    "shezhichenggong":"设置成功",
    "shuruneirongbuyizhi":"输入内容不一致，请重试",
    "wenxintishi_jianyimima":"温馨提示:\n一些说明文字一些说明文字一些说明文字一些说明文字一些说明文字",
    "shuruyuandenglumima":"Enter current password",
    "shuruxindenglumima":"8-12 letters and numbers",
    "chongfushuruxindenglumima":"Re-enter new password",
    "genghuantouxiang":"Edit Profile Image",
    "moren":"Default",
    "qq":"QQ",
    "jingxuan":"Featured",
    "gezhanghumingxi":"Details of each account balance",
    "huazhuanjilu":"Transfer record",
    "dailizhuce":"Join Affiliate",
    "querenmima":"Confirm Password:",
    "dianziyouxiang":"Email:",
    "wenxintishi_zhuce":"Reminder:\n1.* The field is required\n2.By submitting above, you agree to our Terms and Conditions, privacy policy, and cookies.",
    "jieshaorenxinxi":"Referrer Profile",
    "daima":"Code：",
    "fuzhi":"Copy",
    "lianjie":"Link：",
    "tuiguangerweima":"QR Code",
    "baocuntupian":"Save Image",
    "baocunchenggong":"Copied",
    "fuzhilianjie":"Copy Link",
    "huiyuanliebiao":"Distributor List",
    "riqi":"Date",
    "xiaxiancunkuan":"Distributor Deposit",
    "zhuanquhongli":"Commission",
    "xianxiayonghu":"Downline Distributor",
    "zhu_beijingshijian":" * Current Time (CST)= Eastern Time (EST)+12:00",
    "riqi_meidong":"Date (EST)",
    "jiaoyileibie": "Transaction Type",
    "jiaoyiedu":"Credit Amount",
    "xianyouedu":"Available Balance",
    "xiazhujifenjiangli":"下注积分奖励",
    "fuyinglifanshui":"Loss Rebate",
    "youxileixing":"Game Type",
    "youxiaotouzhu":"Valid Bet",
    "shuying":"Win",
    "fanshui":"Rebate",
    "touzhuliangfanshui":"Bet Rebate",
    "jinrizuhezhanbilv":"Today's Bet Combo Rate",
    "qitayouxi_":"Others ( %s to %s )",
    "huishui":"Rebate",
    "yinlifanshui":"Rebate",
    "zuhezhanbilv":"Bet Combo Rate",
    "jinri":"Today",
    "day_7":"Last 7 days",
    "day_15":"Last 15 days",
    "day_30":"Last 30 days",
    "youxipingtai":"Game Provider",
    "bishu":"No. of Entries",
    "touzhue":"Bet Amount",
    "youxiaotouzhu_":"Valid Bet: %s Bet Amount: %s",
    "touzhuriqi":"Bet Date&Time (EST)",
    "wodeyinhangka_":"My Bank Card:Enrolled %s pc(more can be enrolled %s pc)",
    "wodeshuzhiqianbao_":"My USDT Wallet:Enrolled %s pc(more can be enrolled %s pc)",
    "tianjiayinhangka":"Add Card",
    "zuiduoketianjia_":"(Maximum up to %s)",
    "wenxintixing_yinhangka":"Reminder:\n1.Cardholder's name should be exactly same as the full name submitted when sign up, otherwise the withdraw will be denied.;\n2.Each user can enroll maximum up to 3 bank cards;\n3.Cannot be changed once enrolled,For any modification, please kindly approach",
    "tianjiashuziqianbao":"Add USDT Wallet",
    "wenxintixing_usdt":"Reminder:\n1.Each user can enroll maximum up to 3 USDT Wallets (Up to 1 wallet per Network.);\n2.Cannot be changed once enrolled.For any modification, please kindly approach",
    "dizhi":"Wallet Address",
    "suoshuxieyi":"Network",
    "hongbao":"Red Pocket",
    "jine":"Amount",
    "youxiaoqi":"Validity",
    "xuyaodamaliang":"Minimum Bet Amount",
    "yitiqu":"Claimed",
    "weijihuo":"Inactivated",
    "yijihuo":"Activated",
    "yishixiao":"Expired",
    "tiqu":"Claim",
    "tiquchenggong":"Sucessfully",
    "duihuan":"Submit",
    "huilv_":"Exchange rates: %s",
    "cong_from":"from",
    "zhi_to":"to",
    "zhuanru":"IN",
    "huazhuanjine":"Transfer amount",
    "querenhuazhuan":"Confirm transfer",
    "yijianguiji":"Collect All to Main Currency",
    "xuanzheriqi":"Select Date",
    "shaixuan":"筛选",
    "cunqukuan":"Deposit/Withdraw",
    "zhuanzhang":"Transfer",
    "zhichu":"支出",
    "shouru":"收入",
    "qingxuanzhe":"Please select",
    "qing3fenzhonghoushuaxin":"Please wait up to 3 mins then refresh the page for the transaction status",
    "chongzhixiangqing":"Details",
    "chongzhixingming":"Username",
    "dingdanbianhao":"Transaction Number",
    "chongzhijine":"Amount of Deposit",
    "zhongwenjianti":"中文简体",
    "yingyu":"English",
    "yuenanyu":"Tiếng Việt",
    "jintian":"Today",
    "zuijin7tain":"Last 7 days",
    "zuijin30tian":"Last 30 days",
    "quanbuzhuangtai":"All Status",
    "chenggong":"Done",
    "chulizhong":"Processing",
    "yiquxiao":"Canceled",
    "quanbufangshi":"All Methods",
    "fuzhichenggong": "Copied",
    "qiehuanquanjuqianbao":"切换全局钱包",
    "tuijianyouli":"Recommend Reward",
    "qianghongbao":"Red envelopes",
    "zanwuyouxi":"No record in here",
    "fanshuishuoming":"Rebate Instructions",
    "jiazaizhong":"Loading...",
    "weikaishi":"Start soon",
    "jinxingzhong":"On-going",
    "yijieshu":"Over",
    "hongbaohuodong":"Red Pocket game",
    "xiangqing":"Details",
    "qingxiandenglu":"Please log in first.",
    "jingqingqidai":"Coming Soon",
    "denglugengjingcai":"welcome",
    "gengduo":"More",
    "huishou":"OUT",
    "sishiershuzihuozimu":"4-12 letters and numbers",
    "bashiershuzihuozimu":"8-12 letters and numbers",
    "zhenshixingmingbunengkong":"Full name cannot be empty",
    "yanzhengmabunengkong":"Verification code cannot be empty",
    "mimashurubuyizhi":"The two entered passwords do not match",
    "usdt_coin":"USDT",
    "lianxizaixiankefu":"Please kindly approach Help Center",
    "shuruzhuanzhangqianbao":"Enter your deposit address",
    "yiwanchengtijiaorukuan":"Submit",
    "qianbaodizhi":"Deposit Address",
    "shifoujinxingzhuanzhang":"Transaction completed?",
    "tishi":"Reminder",
    "yinhangmingcheng":"Bank Name:",
    "xuanzhezhifuyinhang":"Please select the bank of deposit",
    "zhifutiaozhuan":"Click here if done with the transaction %s",
    "quedingtijiaodingdan":"Ready to submit?",
    "caozuochenggong":"Sucessfully",
    "zhuzhanghao":"Main Currency",
    "qingxuanzhezhuanru":"Select an account to convert in",
    "qingxuanzhezhuanchu":"Select an account to convert out",
    "qingxuanzhetikuanzhanghu":"Select withdrawal account",
    "dianjitianjiazhanghu":"Add Withdrawl Accounts",
    "ninhaimeibangdingyhkzhanghu":"You have not enrolled for a Bank Card yet",
    "ninhaimeibangdingusdtzhanghu":"You have not enrolled for a USDT Wallet yet",
    "ninhaimeibangdingqianbao":"You have not bound this type of wallet yet",

    "qubangding":"Enroll",
    "chukuanzhanghu":"Bank Card Number:",
    "chukuanyinhang":"Bank Name:",
    "kaihudizhi":"Bank Address:",
    "yanzhengchukuanmima":"Withdrawal Password：",
    "shuruyinhangkakaihudizhi":"Enter bank address",
    "liudao12weishuzihuozimu":"6-12 characters (accept only numbers and letters)",
    "yigezhanghaosanzhangyinhangka":"1.Each user can enroll maximum up to 3 bank cards of withdraw;\n2.For any modification, please kindly approach Cutomer Support",
    "qingshuruqianbaodizhi":"Enter the Wallet address",
    "qingshuruqukuanmima":"Enter withdrawal password",
    "qianbaoxieyi":"Wallet Network:",
    "yanzhengzijinmima":"Withdrawal Password:",
    "shuruyinhangzhanghao":"Bank account number cannot be empty",
    "qingxuanzhechukuanyinhang":"Select bank name",
    "qingshuruchukuanmima":"Withdrawal password cannot be empty",
    "trc20_show":"TRC20 (TRON Network)",
    "erc20_show":"ERC20 (Ethereum)",
    "omni_show":"OMNI (Bitcoin Network)",
    "tuiguanghongli":"Commission",
    "sidao12shuzihuozimu":"4-12 letters and numbers",
    "mimacuowu":"The password is incorrect",
    "zhanghaomimadenglu":"Account password login",
    "chongzhijymm":"Reset simple password",
    "chongzhijymmtishi":"After resetting the simple password, the simple password you set will be cleared, please use your username and password to log in. After successful login, the simple password will be erased automatically.",
    "qingzaiciyanzhenghaxizhi":"Please enter or paste the hash value here to verify",
    "geshangqi":"No-show",
    "jinrikai":"Show today",
    "wodeshoucang":"Favorites",
    "lianxiwomen":"Contact Us",
    "2023guojizhan_dw":"@2023 DW International",
    "2023guojizhan_boya":"@2023 boya casino",
    "2023guojizhan_shouxin":"@2023 shouxin",
    "2023guojizhan_aomen":"@2023 aomen",
    "2023guojizhan_fuyuan":"@2023 fuyuan",
    "2023guojizhan_gdvip":"@2023 gdvip",
    "2023guojizhan_leyou":"@2023 Leyou Casino",
    "2023guojizhan_jsgj":"@2023 JIANGSHAN CASINO",
    "2023guojizhan_longmen":"@2023 LONGMEN CASINO",
    "yingyongneijiazai":"Light in-app loading",
    "liulanqidakai":"Use the default browser",
    "biaozhunshijian":"The website standard time is subject to Eastern Time\nCurrent Time (CST)= Eastern Time (EST)+12:0",
    "zhuninxiacizdj":"Better luck next time",
    "jiangjinfengfu":"Login everyday to get bigger bonuses!",
    "weihuzhong":"Under maintenance",
    "yiguanpan":"Unavailable",
    "yixiushi":"Closed",
    "yichenggongqiehuan_":"Successfully switched to %s wallet,\nIn the game, you will use %s",
    "jifenbuzu":"No enough credits",
    "xianlu1":"线路1",
    "xianlu2":"线路2",
    "xianlu3":"线路3",
    "xianlu4":"线路4",
    "xianlu5":"线路5",
    "xianlu6":"线路6",
    "julifengpan":"The game will end in",
    "miao":"s",
    "kaishixiazhu":"Place your bets",
    "bangdingqitaqianbao":"Enroll Other Wallet",
    "wodeqitaqianbao":"My Other Wallets：enrolled %s pc(more can be enrolled %s pc)",
    "zuiduoketianjiaqianbao":"(Maximum up to %s)",
    "qitaqianbaowenxintis":"Reminder：\n1.The maximum number of other wallet accounts that each user can bind is:10(Different types can be bound to one respectively)\n2.Cannot be changed once enrolled.For any modification, please kindly approach",
    "qianbaoleixing":"Wallet type",
    "tixianfangshi":"Withdrawal method",
    "yhk":"Bank card",
    "xqianbao":"%s wallet",
    "xianlu_":"Access %s",
    "julifengpanshijian":"The game will end in %s",
    "dixqi":"No.%s",
    "no":"No.",
    "fengpanxinxi":"Closing Details",
    "kaishifengpan":"开始封盘",
    "lianjiefuwushibai":"链接服务失败，稍后再试",
    "kaijiangzhong":"Revealing",
    "qiandaochenggong":"Sucessfully",
    "benyueleijiqiandao":"The days of this month sucessfully logged in：",
    "jiajifen":"，+",
    "zaiqiandao":"days more loggin：",
    "kehuode":"，can earn",
    "gentou":"To call",
    "zhongjiangjieguodongxiao":"Winning result animation",
    "qingxuanzhetouzhuxm":"Place your bets",
    "xiazhujinewk":"Amount cannot be empty",
    "danmu":"Barrage",
    "changqihuodong":"Ongoing",
    "jiehzhiriqizhi":"Expired by",
    "dao":"to",
    "zanwuxiazhujilu":"No record in here",
    "xuanzheleixing":"Select Category",
    "touzhuchenggong":"Submit successfully",
    "kaihuxieyi":"Terms and Conditions",
    "jieshaoren":"Referrer Code:",
    "shurujieshaoren":"Enter Referrer Code",
    "yuebuzhuqingxianchongzhi":"Your balance is too low to pay. Deposit now?",
    "qingkaitongzhanghu":"Please activate one of the following accounts",
    "huodongweikaiqi":"The event is not started",
    "qingquerenzhudan":"Confirm your bets",
    "xuanzhonghaoma":"Selected",
    "peilv":"Payout",
    "ruozhongjiang":"Prize",
    "yinli":", win",
    "zongjine":", total",
    "zunjingdekehu":", Dear Players：\n Our system is currently under maintenance, sorry for the inconvenience, thank you for understanding.",
    "xitonggonggao":", notifications",
    "yibangding":"Enrolled",
    "xuanzhenindemorenqianbao":"Select your default wallet",
    "morenqianbaotishi1":"1.Select your default wallet, and the corresponding currency will be used for settlement when entering the game.",
    "morenqianbaotishi2":"2.The exchange operation between the balances of the two wallets can be performed on the [Exchange] page.",
    "zuida":"All",
    "shuruyinhangmingcheng":"Please enter bank name",
    "yicizhinengfasong3tiao":"Up to 3 texts can be sent each time.",
    "shuruneirongchaoguozuidaxianzhi":"The content entered has exceeded the maximum limit.",
    "guanbijianyimima":"After closing the simple password, the simple password you set will be cleared. Please use the username and password to log in. After successful login, the simple password will be automatically erased.",
    "wolaishuoliangju":"Say something...",
    "fanshuixiangqing":"Rebate History",
    "faxianxinbanben":"New version",
    "xiacizaishuo":"Later",
    "lijigengxin":"Now",
    "jianchagengxin":"Check for updates",
    "yijingshizuixinl":"It's the latest version",
    "weishouxuanzhuangquanxian":"Installation permission was not granted and the update has been cancelled",
    "denglumima":"Password:",
    "zhucetishiyu":"1.* The field is required\n2.By submitting above, you agree to our Terms and Conditions, privacy policy, and cookies.",
    "huiyuanchukuanjinedayuzhuzhanghu":"The amount of the member's contribution is greater than the main account balance",
    "bet_tema":"Special No.",
    "bet_jida":"Max",
    "bet_jixiao":"Min",
    "bet_hongbo":"Red",
    "bet_lanbo":"Blue",
    "bet_lvbo":"Green",
    "bet_sunzi":"Straight",
    "bet_baozi":"Trips",
    "bet_duizi":"Pair",
    "hello_you": "Good day, %s",
    "zuotian":"Yesterday",
    "ti_confirm":"Submit",
    "ruoxuxiugaitixianzhanghu":"1.For any modification, please kindly approach Customer Support\n2.The withdrawal process will take 3-5 mins.",
    "shibieshibai":"Recognition failure!",
    "kaiqishengwushibie":"Biometric identification",
    "qingzaixitongshezhifaceidzhuce":"Please do FaceID or fingerprint registration in system Settings",
    "qingyanzhengshenfen":"Please authenticate to login",
    "wangluocuowu":"Network error!",
    "qiehuanchenggong":"Switch successful",
    "jiesaorenbunengkong":"Referrer Code cannot be empty",
    "emailbunengkong":"Email address cannot be empty",
    "wechatbunengkong":"Wechat ID cannot be empty",
    "qqbunengkong":"QQ number cannot be empty",

  };

}
