class EN{
  static const Map<String, String> map ={
    "theme":"Theme",
    "home":"Home",
    "preferential": "Preferential",
    "into_money": "IN",
    "wheel_jiangjinfengfu": "Login everyday to get bigger bonuses!",
    "all_status_suc": "Done",
    "all_status_weichuli": "Processing",
    "all_status_yiquxiao": "Canceled",
    "thirty_day": "Last 30 days",
    "wheel_zhongjiang": "中奖：",
    "wheel_zhongjiang_yuan": "Bonus: %1\$s %2\$s",
    "wheel_jiangjin": "Bonus:",
    "plan_close": "Bet closed",
    "plan_waiting": "Start soon",
    "ko_str": "韩国",
    "ind_str": "印度",
    "with_sys_str": "跟随系统",
    "hui_water": "Rebate",
    "h_hui_water": "Rebate",
    "tz_num": "Bet Amount",
    "tz_time": "Bet Date",
    "home_show_game_hide": "Hide panel",
    "home_home": "Home",
    "home_discount": "Promos",
    "home_recharge": "Deposit",
    "home_kefu": "Customer",
    "home_mine": "Account",
    "mine_name": "My Account",
    "mine_eduzhuanhuanu": "Balance Convert",
    "mine_zijinjiaoyi": "Transactions History",
    "mine_touzhujilu": "Bet History",
    "mine_jifenjilu": "Credit Records",
    "mine_huiyuanfanshui": "Rebate History",
    "mine_hongbaohejiangjin": "Red Pocket \u0026 Bonus",
    "mine_tuiguangzhuanqian": "Earn With Us",
    "mine_setting": "Settings",
    "mine_tixian": "Withdraw",
    "mine_rukuan": "Deposit",
    "mine_tixian_other": "Withdraw from %s Wallet",
    "mine_tixian_usdt": "Withdraw from USDT Wallet",
    "mine_main_account": "Main Currency",
    "mine_jiangjin": "Bonus",
    "mine_jifen": "Credit",
    "kefu_kefu": "Help Center",
    "discount_discount": "Promotions",
    "discount_discount_detail": "Promotion",
    "discount_coming": "Read More",
    "discount_back": "Back",
    "sure": "Submit",
    "nick": "Nickname:",
    "phone": "Mobile:",
    "qq_number": "QQ:",
    "wx_number": "Wechat:",
    "e_mail": "Email:",
    "e_mail_tip": "Enter Email address",
    "wx_number_tip": "Enter Wechat ID",
    "qq_number_tip": "Enter QQ number",
    "phone_tip": "Enter mobile number",
    "home_show_game": "Show All",
    "home_start_game": "Play Now",
    "game_room_odds_message": "Game Odds",
    "dialog_see_more": "Confirm",
    "dialog_text_switch_money": "Please select a wallet",
    "back": "Back",
    "no_more": "- You\\\u0027ve reached the end -",
    "empty_no_data": "No one in here:-(",
    "account_setting": "Settings",
    "setting_banding_bank_str": "Enroll Bank Card (Withdraw)",
    "setting_banding_usdt_str": "Enroll USDT Wallet",
    "setting_banding_cgp_str": "Enroll CGPay Wallet",
    "setting_set_tixian_password_str": "Set Withdrawal Password",
    "setting_set_login_password_str": "Set Login Password",
    "account_please_input_bank_name": "Enter Bank Account Name",
    "account_bank_account_acc": "Bank Card Number:",
    "account_bank_account_bank": "Bank Name",
    "account_please_input_bank_number": "Enter the account number including 10-19 numbers",
    "account_bank_address": "Bank Address:",
    "account_please_select": "Please select",
    "account_bank_password": "Withdrawal Password:",
    "account_bank_chukuan_password": "Enter the password of withdraw",
    "account_usdt_trc20": "USDT-TRC20(TRON):",
    "account_usdt_ERC20": "USDT-ERC20:",
    "account_usdt_Omini": "USDT-Omini:",
    "account_banding_cgp": "CGPay:",
    "account_banding_cgp_tip": "Enter your deposit address",
    "account_set_password_old": "Current Password:",
    "account_set_password_old_tip": "Enter current password",
    "account_set_password_old_tip_2": "Enter current password",
    "account_set_password_new": "New Password:",
    "account_set_password_new_tip": "6-12 letters and numbers",
    "account_set_password_new_tip_2": "8-12 letters and numbers",
    "account_set_password_new_sure": "Confirm New Password:",
    "account_set_password_new_sure_tip": "Re-enter new password",
    "account_set_password_new_sure_tip_2": "Re-enter new password",
    "message_center": "News",
    "message_notice": "Notice",
    "message_message": "Messages",
    "sp_daima": "Affiliate:",
    "sp_link": "Link:",
    "sp_user_message": "Referrer Profile",
    "sp_promotion_qr": "QR Code",
    "qur_promotion_recode": "Check Earning Statement",
    "copy_link": "Copy Link",
    "save_img": "\tSave Image",
    "down_which_qur_time": "Please select date \u0026 time below",
    "pro_time_tip": "Current Time (CST)\u003d Eastern Time (EST)+12:00",
    "time_meifong": "Date (EST)",
    "time_meifong_2": "Bet Date \u0026 Time (EST)",
    "jiaoyi_leibie": "Transaction",
    "jiaoyi_edu": "Transaction Amount",
    "xianyou_edu": "Balance",
    "mine_fu_return_water": "Loss Rebate",
    "mine_fu_water_tip": "Rebate Instructions",
    "game_type": "Game Type",
    "effective_tz": "Valid Bet",
    "win_or_fail": "Result",
    "return_water": "Rebate",
    "xiaoji": "Total",
    "other_game_type": "Rebate",
    "mine_tz_return_water": "Bet Rebate",
    "zongji": "Total",
    "todata_tz_zh": "Today\\\u0027s Bet Combo Rate",
    "pc_28": "PC28",
    "agent_user_name": "Username",
    "agent_user_password": "Password:",
    "really_name": "Full Name:",
    "really_name2": "Cardholder\\\u0027s Name::",
    "agent_user_tip": "4-12 letters and numbers",
    "agent_password_tip": "8-12 letters and numbers",
    "agent_really_tip": "Same as per your bank account",
    "agent_phone_tip": "Enter a verified mobile number",
    "agent_qq_tip": "Enter QQ number",
    "agent_email_tip": "Enter Email address",
    "agent_bank_tip": "Please select",
    "agent_bank_address_tip": "Please select",
    "hongbao": "Red Pocket",
    "jiangjin": "Bonus",
    "cny_money_type": "CNY Wallet",
    "recycling_money": "OUT",
    "game_th": "TH",
    "game_ag": "AG",
    "show_all_type": "Show All",
    "close_all_type": " Hide Panel",
    "game_bbin": "BBIN",
    "edu_all_type_tip": "\tAll Accounts Balance",
    "edu_into_and_out_tip": "Select account and enter amounts to convert",
    "input_chance_money": "enter amounts to convert",
    "input_chance_money_no_e": "The current transfer out account amount is insufficient ",
    "start_chance": "Start Convert",
    "start_chance2": "Submit",
    "yijina_guiji": "Collect All to Main Currency",
    "xiaz_detail": "Bet Details",
    "mine": "My Account",
    "night_theme": "Dark Mode",
    "day_theme": "Light Mode",
    "out_app": "Log out",
    "china_str": "中文",
    "vi_str": "Việt Nam",
    "open_music": "Sound ON",
    "close_music": "Sound OFF",
    "open_tip_misic": "Tones ON",
    "close_tip_misic": "Tones OFF",
    "online": "Automatic",
    "downline": "Manual",
    "zf_cz_account": "Username:",
    "zf_normal_online_edt_tip": "Enter manually or select from below amounts",
    "zf_cz_history": "Deposit History",
    "zf_huikuan_name": "Remitter\\\u0027s Name:",
    "zf_huikuan_name_tip": "Enter the name of the Remitter",
    "zf_huikuan_money": "Amount of Deposit :",
    "zf_huikuan_money_tip": "Enter the amount to deposit",
    "zf_yinhang_name": "Bank Name:",
    "zf_yinhang_name_tip": "Please select the bank of deposit",
    "zf_yinhang_huikuan_type": "Deposit Method:",
    "zf_yinhang_huikuan_type_tip": "Please select a method to deposit",
    "bill_detail": "Transaction INFO",
    "zf_commit_ok_tip": "Please wait up to 3 mins then refresh the page for the transaction status.",
    "zf_cz_name": "Username",
    "zf_cz_name2": "Sender\\\u0027s Account:",
    "zf_cz_bill_number": "Transaction Number",
    "zf_cz_commit_time": "Submit Date/Time",
    "zf_cz_money_number": "Amount of Deposit",
    "commit_ok": "successfully",
    "all_way": "\tAll Methods",
    "all_status": "All Status",
    "today": "Today",
    "fast": "Fast",
    "normal": "Normal",
    "slow": "Slow",
    "do_no_use": "Unavailable",
    "entry": "Enter",
    "please_game_name": "Search for games",
    "modify_data": "Complete Profile",
    "sure_jihe_message": "Audit Info Confirmation",
    "sure_tixian_message": "Withdrawal Account Info",
    "continue_tixian": "Submit",
    "tx_money": "Amount of Withdraw",
    "tx_password": "Withdrawal Password:",
    "tx_input_money": "Withdrawal Amount",
    "sure_money": "Confirm Amount",
    "tx_money_tip": "Enter amount of withdraw",
    "other_money": "Convenience Fee",
    "realy_get_money": "Actual Withdrawal withdraw",
    "change_avater": "Change the avatar",
    "about_us": "About Us",
    "play_tip_message": "How To Play",
    "mine_tuiguanghistory": "Earning Statement",
    "tuiguanghongli": "Commission",
    "downline_user": "Downline Distributor",
    "downline_user_money": "Distributor Deposit",
    "gethongli": "Commission",
    "huiyuanlist": "Distributor",
    "up_page": "previous page",
    "down_page": "next page",
    "nodata_promation": "No promotion bonus",
    "mine_agent": "Join Affiliates",
    "kaijiang_trend": "Tendency",
    "sign_in_get_money": "Reward",
    "point_lot": "Spin",
    "go_play": "Bet Now",
    "trend_chart": "Trend chart",
    "history_result": "History lottery",
    "point_sign_in": "Reward",
    "point_wheel": "Spin To Win",
    "loading": "Loading...",
    "please_input_old_password": "Please enter your old password",
    "please_input_new_password": "Please enter a new password",
    "please_input_new_again_password": "Please enter the confirmation password",
    "new_err_password": "The two entered passwords do not match",
    "notice_please": "Attention, please",
    "wallet": "wallet",
    "select_in_acc": "Select an account to convert in",
    "rate": "Exchange Rate",
    "account": "Account",
    "record_all": "All",
    "record_cun_ti": "Deposit \u0026 Withdraw",
    "record_zhuanzhang": "Transfer",
    "yesterday": "Yesterday",
    "seven_day": "Last 7 days",
    "shi_wu_day": "Last 15 days",
    "san_shi_day": "Last 30 days",
    "app_brvah_loading": "Loading...",
    "app_brvah_load_end": "No more data",
    "app_brvah_load_failed": "Loading failed...",
    "app_brvah_load_complete": "Click load more",
    "en_str": "English",
    "hello_welcome": "Hello, good luck",
    "please_input_addr": "Enter Bank address",
    "please_sele_bank": "Please select a bank card",
    "please_hua_dong": "Please slide to verify",
    "user_mess_is_empty": "User information cannot be empty",
    "please_login": "Please log in first",
    "card_number": "Card Number",
    "has_card_user": "Cardholder Name",
    "click_bank_band": "Add bank card",
    "max_three_card": "(Maximum up to 3 pc)",
    "bank_message_tip": "  ",
    "wallet_addr": "Wallet   Address : ",
    "xieyi_o": "Affiliated agreement",
    "us_message_tip": " ",
    "wa_yixie": "Wallet Network",
    "xieyi": "Network",
    "click_bank_band_us": "Add Cryptocurrency Wallet",
    "wa_mu": "Exchange",
    "change_money": "Amount of Exchange ",
    "input_money_change": "Enter the amount of the transfer",
    "rate_maybe": "Reference Exchange Rate:  ",
    "realy_get_money_2": "Actual Amount of Exchange:  ",
    "copy_suc": "Copy succeeded",
    "all_day_service": "Serving you for more fun",
    "hello": "Hi, ",
    "defult_av": "Default Avatar",
    "ava_qq": "QQ Avatar",
    "ava_good": "Selected Avatar",
    "pay_to": " Deposit to  ",
    "zf_jump": "Click here if done with the transaction",
    "pa_tip": "Payment Instructions: ",
    "mark": "remarks",
    "bank_branch": "bank branch",
    "has_card_name": "Cardholder",
    "password_no_same": "The two passwords are inconsistent",
    "promotion_sp_tip": " ",
    "sele_wa_agreement": "Please select network",
    "look_message_and_pay": "Check the Payee\\\u0027s INFO, and proceed to transfer:",
    "need_input_message_about_me": "Please complete the info after transaction",
    "hongbao_ad": "Red envelope activity",
    "reminder": "Reminder:",
    "online_remark_tip_one": "1.Click the link and follow the instructions.",
    "online_remark_tip_two_or_three": "2.Convenience fee %1\$s ,Speed Withdraw!",
    "down_tip_one": "1. Please complete the transfer within the time limit.",
    "sure_commit_order": "Are you sure you want to submit the order?",
    "com_tip": "Notice",
    "com_cancel": "cancel",
    "sure2": "Submit",
    "sure_zhuangzhang": "Have you made a transfer to the collection account?",
    "switch_zf_way": "Change deposit method",
    "wheel_fail": "Lottery failure",
    "point_wheel_integral": "  ",
    "cur_m_has_num": "days logged in. %1\$s , Total credits:%2\$s",
    "with_bank_tip": "Withdrawal Account",
    "click_to_bank": "Click bind bank card",
    "sele_tix_wa": "Select withdrawal Wallet",
    "sele_tix_bank": "Select withdrawal bank card",
    "click_to_usdt": "Click bind wallet address",
    "with_u_tip": "Withdrawal Wallet :",
    "date": "Date(EST)",
    "effective_betting_water": "Valid Bet",
    "win_or_lose_water": "Result",
    "combinbetradio": "Combo Rate",
    "hasCardUser": "Cardholder Name",
    "my_fav": "Favorites",
    "game_name": "game name",
    "num_all": "Number of transactions",
    "all": "all",
    "hongbao_number": "Red Pocket Amount",
    "need_dama": "Minimum Bet Amount",
    "has_av_time": "Validity",
    "status": "Status",
    "jiangjin_number": "Bonus amount",
    "open_plat": "Activate",
    "main_money": "Main Currency",
    "mine_about": "About",
    "about": "About",
    "home_mianze_notice": "Terms and Conditions",
    "home_jishu_sur": "Technical Support",
    "home_fang_jijie": "Anti-Hijacking Guide",
    "copy_number": "Copy",
    "once_to_chat": "Chat now",
    "go_banding": "Enroll",
    "please_banding_bank": "You have not enrolled for a Bank Card yet",
    "please_banding_usdt": "You have not enrolled for a USDT Wallet yet",
    "houdong_longtime": "Ongoing",
    "houdong_off": "Activity time: deadline to",
    "tourist": "tourist",
    "hongbao_weijihuo": "Inactivated",
    "hongbao_tiqu": "Activated",
    "hongbao_tiqu2": "Claim",
    "hongbao_yitiqu": "Extracted",
    "hongbao_yishixiao": "Invalid",
    "home_hongbao_no_login": "Please log in with your account. If you log in successfully, you can participate",
    "home_hongbao_wei_kaishi": "Not started",
    "homn_hongbao_jinxing": "On-going",
    "home_hongbao_yijishu": "Has ended",
    "home_huiodong_rule": "Spin Guide",
    "home_jiangjin_tiqu": "Claim Bonus",
    "jihe_tip1": "Valid bet amount after withdraw and the first deposit:",
    "jihe_tip_2_1": "Clear, no deposit bonus to be deducted!",
    "jihe_tip_2_2": "Faild to pass promotion audit, bonus will be deducted:",
    "jihe_tip_3_1": "Clear, no administration fee to be charged!",
    "jihe_tip_3_2": "Fail to pass normal audit, adminstration fee will be deducted :",
    "jihe_changtai": "Promotion audit:",
    "jihe_youhui": "Promotion audit:",
    "jihe_duocitixian": "Multi- withdraw convenience fee:",
    "jihe_shixiao": "Timeliness Service Charge",
    "jihe_tip_4_1": "Free of charge!",
    "jihe_tip_5": "Withdraw Audit Time: ET ",
    "jihe_tip_7_1": "%2\$s  of the withdrawal amount will be deducted if to withdraw within %1\$sH from the latest deposit.",
    "jihe_tip_6_1": "No more than %2\$s times withdraw within %1\$sH, will be deducted: %3\$s ",
    "jihe_tip_6_2": " Free of charge if no more than %2\$s times withdraw within %1\$sH. \"",
    "tikuan_tip_1": "Withdrawal Amount",
    "tikuan_tip_2": "Enter the password of withdraw",
    "tikuan_tip_3": "Withdrawal Account Info",
    "tikuan_tip_4": "Actual Withdrawal Amount must be greater than 0",
    "zf_yh_down_tip_2": "Please complete the remmittance details once the transaction has been made",
    "zf_shuoming": "Payment Instructions:",
    "zf_shuoming_content": "\\n1. Please enter the amount to deposit or other amounts, select the bank and click to submit\\n2.The system will automatically redirect to the payment webpage, please follow the instructions and select payment method\\n3.You can pay by means of Online Banking, Scan to Pay, etc\\n4.Once the transaction was sucessfully proceeded, please back in the APP manually\\n5.5.The deposit amount will be automatically added to your account. Should you have any inquiry or meet any failure, please contact Customer Support at any time",
    "zf_online_tip_1": "Please click the link below and follow the instructions",
    "zf_online_tip_2": "Enter the amount( %1\$s -  %2\$s )click to submit",
    "wheel_5x": "5x",
    "wheel_10x": "10x",
    "wheel_15x": "15x",
    "wheel_20x": "20x",
    "wheel_congratulations": "Congratulations",
    "wheel_next_zhongjaing": "Better luck next time",
    "close": "close",
    "wheel_di_ci": "Spin %1\$s",
    "wheel_keep_it": "Keep it up",
    "room_tema": "Special",
    "room_diyiqiu": "1st",
    "room_dierqiu": "2nd",
    "room_disanqiu": "3rd",
    "point_click_checkin": "Daily Login Reward",
    "discount_time_tip": "Activity time: %1\$s - %2\$s ",
    "user_password_resure": "Confirm Password",
    "agent_reg_tip_1": "1.* The field is required",
    "agent_reg_tip_2": "2. By submitting above, you agree to our Terms and Conditions, privacy policy, and cookies.",
    "agent_reg_tip_3": "Terms and Conditions",
    "ust_tip_1": "1.Each user can enroll maximum up to 3 USDT Wallets (Up to 1 wallet per Network.)",
    "usd_tip_2": "2.Cannot be changed once enrolled.For any modification, please kindly approach",
    "link_kefu": "Customer Support;",
    "tingyong_termi": "Terminated",
    "trc20_show": "TRC20 (TRON Network)",
    "erc20_show": "ERC20 (Ethereum)",
    "omni_show": "OMNI (Bitcoin Network)",
    "bank_tip_1": "1.Cardholder\\\u0027s name should be exactly same as the full name submitted when sign up, otherwise the withdraw will be denied.",
    "bank_tip_2": "2.Each user can enroll maximum up to 3 bank cards",
    "bank_tip_3": "3.Cannot be changed once enrolled  For any modification, please kindly approach %1\$s",
    "bank_tip_3_2": "2.Cannot be changed once enrolled  For any modification, please kindly approach %1\$s",
    "bank_tip_4": " 1.Each user can enroll maximum up to 3 bank cards \\n2.For any modification, please kindly approach Cutomer Support",
    "bank_set_passw": "Set Withdrawal Password:",
    "bank_yanz_passw": "Withdrawal Password:",
    "bank_chukuan_mima_tip": "6-12 letters and numbers",
    "long_pre_to_copy": "1.Long press to copy",
    "checkin_tip_1": "The days of this month successfully logged in %1\$s, + %2\$s credits",
    "mod_user_tip1": "1.Please refer to feature \"Account - Settings - Enroll Bank Card\" to complete bank profile and withdrawal password setting before withdraw",
    "mod_user_tip2": "2.Should you have any inquiry, please contact Cutomer Support at any time",
    "edu_main_money": "Main Currency",
    "select_out_acc": "Select an account to convert out",
    "trend_qishu_tip": " ",
    "point_bot_tip": "The website standard time is subject to Eastern Time\\n Current Time (CST)\u003d Eastern Time (EST)+12",
    "sun" :"Sun",
    "mon": "Mon",
    "tue": "Tue",
    "wed": "Wed",
    "thur": "Thur",
    "fri": "Fri",
    "sat": "Sat",
    "tixian_tip_1": "1, For any modification, please kindly approach Cutomer Support",
    "tixian_tip_2": "2, The withdrawal process will take 3-5 mins.",
    "ust_online_tip": "  ",
    "us_shoukuan_a": "Receiver\\\u0027s Account:",
    "updateapk_tip1": "正在安装程序",
    "updateapk_tip2": "更新内容：",
    "updateapk_tip3": "Update Now",
    "updateapk_tip4": "Later",
    "updateapk_tip5": "最新版本：",
    "updateapk_tip6": "New version available",
    "close_app": "Want to quit the game?",
    "checkin_tip_2": "days more loggin ",
    "checkin_tip_3": ", can earn ",
    "checkin_tip_4": " Credits",
    "jdc_out_tip": "Want to quit Classic Lottery?",
    "gfc_out_tip": "Want to quit Official Lottery?",
    "out_game_tip": "Want to quit the game?",
    "line_heard_tip1": "Pull down to obtain lines.",
    "line_heard_tip2": "Obtaining links...",
    "line_heard_tip3": "Successfully obtained",
    "line_heard_tip5": "Fail to obtain, please retry",
    "line_heard_tip6": "Retry",
    "line_heard_status1": "Fast",
    "line_heard_status2": "Fast",
    "line_heard_status3": "Slow",
    "line_heard_status4": "time out",
    "home_line_2": "Pull down to obtain lines.",
    "home_line_5": "Fail to obtain, please retry",
    "home_line_4": "Successfully obtained",
    "home_line_7": "Line switching...",
    "home_line_8": " Successfully switched. ",
    "home_line_9": "Select",
    "home_line_10": "Obtaining...",
    "home_line_11": "Line ",
    "jdc_loading": "loading",
    "limit_money": "limit",
    "mine_about_update": "Update",
    "mine_about_help": "Help",
    "yiqiandao": "Signed in",


    "day_yi":"one",
    "day_er":"two",
    "day_san":"three",
    "day_si":"four",
    "day_wu":"five",
    "day_liu":"six",
    "day_ri":"seven",

    "bet_da":"big",
    "bet_xiao":"small",
    "bet_dan":"single",
    "bet_shuang":"double",
    "di":"in",
    "qi":"term",
    "shifoutuichudenglu":"Do you want to log out",

    "huizhijiesuo":"Do you want to redraw the unlock pattern",
    "chonxinshezhi":"reset",
    "huizhisige":"Please draw at least four points",
    "huizhibuyiyang":"Inconsistent with previous drawing, please redraw",
    "zaicihuizhi":"Please draw the unlock pattern again",
    "shifouchongxinhuizhi":"Do you want to redraw the unlock pattern？",


    "fangwenluxian":"Access route selection",
    "kuai":"fast",
    "yiban":"normal",
    "henman":"slow",
    "bukeyong":"unable",



    "gaunyuwomen": "about us",
    "guanwangjieshao": "Official website introduction",
    "xiazhaiyingyong": "Download applications",
    "pingtaifuwu": "Platform Services",
    "yonghuzhongxin": "User Center",
    "huiyuan": "member",
    "chongzhijilu": "Recharge records",
    "qiandaochoujiang": "Sign in lottery",
    "jishuzhichi": "technical support",
    "fangjiechijiaocheng": "Anti hijacking tutorial",
    "fangjiechi": "Anti hijacking",
    "shiyongbangzhu": "Help",
    "xuanzeyuyan":"Choose language",


    "changyongduanyu":"Useful",
    "qitaduanyu":"Other",
    "biaoqing":"Emoji",
    "gif":"Gif",

    "yue_":"balance：",
    "charge": "Recharge",
    "tixian": "Withdrawal",
    "choujiang": "draw a lottery or raffle",
    "zoushi": "trend",
    "customer_service": "customer service",
    "pick_time": "Timing",
    "remen": "Popular",
    "zuijin": "recently",
    "shoucang": "collect",
    "shedingyuyan":"* Please choose the default language, you can set it later in More or My Settings",
    "morenyuyan":"default language",
    "tiaoguo":"skip",
    "queren":"confirm",
    "xuanzeqianbao":"Please select a wallet",
    "morenqianbao":"Default Wallet",
    "shedingqianbao":"* Please select the default wallet, you can set it later in More or My Wallet",
    "rmb":"RMB（CNY）",
    "dollar":"dollar（US）",
    "thb":"Thai baht（Thai Baht）",
    "vnd":"VND（VND）",
    "hyld":"Welcome to xxxx",
    "qqzlxd":"The world's leading xxxx",
    "register":"register",
    "login":"log on",
    "grzx":"Personal Center",
    "rmbqb":"RMB wallet",
    "edzh":"Limit conversion",
    "pcxq":"PC details",
    "tzjl":"Betting record",
    "jymm":"Simple password",
    "dyy":"Multilingual",
    "bjyy":"Background Music",
    "tsy":"sound",
    "wgys":"Appearance/Color",
    "qs":"light colour",
    "dx":"Dynamic effect",
    "qk":"Full open",
    "fxghy":"Share with friends",
    "ycfx":"One sharing, unlimited commission",
    "xzapp":"Download APP",
    "lxjbhb":"Lixiang 888 Gold Coin Red Envelope",
    "logout":"exit",
    "xzndyy":"select your language",
    "sszcbz":"Search for supported currencies",
    "zxndbz":"Choose your currency",
    "bbdh":"Currency exchange",
    "lxkf":"custom service",
    "yhm":"user name",
    "qsryhm":"enter one user name",
    "mm":"password",
    "qsrmm":"Please enter password",
    "wjmm":"forgot password?",
    "cjygzxh":"Create a new account",
    "kfzx":"Customer Service Center",
    "xszxkf":"24-hour online customer service",
    "qthwnfw":"24/7 online service for you",
    "djjr":"Click to enter",
    "dxtxsz":"Dynamic reminder settings",
    "fpdx":"Sealing effect",
    "cksl":"View examples",
    "kjjgdx":"Dynamic effect of lottery results",
    "djsdx":"Countdown effect",
    "wgsz":"Appearance Settings",
    "qzb":"Temperament White",
    "kxh":"Cool Black",
    "cjzh":"create an account",
    "wszhzm":"8-12 digit numbers or letters",
    "zsxm":"true name",
    "yzm":"Code",
    "qsrzcyzm":"Please enter the verification code on the right side",
    "wywdbty":"Registration means that you have agreed",
    "yhtk":"《User Terms》",
    "and":"gentle",
    "ysxy":"《Privacy Agreement》",
    "yyzh":"Existing account?",
    "ytxyhkhmyz":"Consistent with withdrawal bank account name",
    "tab_pcfj":"PC room",
    "tab_cp":"lottery ticket",
    "tab_zr":"A real person",
    "tab_ty":"physical culture",
    "tab_by":"catch fish",
    "tab_dz":"electron",
    "card_ptf":"Common room",
    "card_gjf":"Superior Room",
    "card_gbf":"VIP Room",
    "dangqianzaixian":"%s|%s",
    "peilvshuoming":"Odds statement",
    "wanfaguizhe":"Gameplay rules",
    "youxishuyu":"Game terminology",
    "xiazhujiqiao":"Betting techniques",
    "wanfaguizhe_jieshao":"Let me introduce the gameplay rules to everyone, in order to play…",
    "youxishuyu_jieshao":"Improve game effectiveness by understanding commonly used terminology…",
    "xiazhujiqiao_jieshao":"Here are some betting techniques, such as…",
    "haoyuan":"Source",
    "zhudan":"Note",
    "mipai":"Mipai",
    "qushi":"trend",
    "juelidixqi":"Distance from %s period",
    "zongyue":"Total balance",
    "touzhu":"Betting",
    "zhudan_":"Note：",
    "zongji_":"，total：",
    "qiehuanfangjian":"Switch rooms",
    "confirm":"confirm",
    "cancel":"cancel",
    "tema":"Special code",
    "diyiqiu":"1st",
    "dierqiu":"2nd",
    "disanqiu":"3rd",
    "qingshurujine":"Please enter the amount",
    "end":"end",
    "xiazhuxiangqing":"Betting details",
    "quanbujilu":"Betting details",
    "xiazhujine":"Betting amount",
    "keyingjine":"Winning amount",
    "xbi":"%s pen",
    "qihao_":"issue:%s",
    "wallet_cny":"CNY Wallet",
    "wallet_usdt":"USDT  Wallet",
    "danhao":"odd numbers",
    "neirong":"content",
    "guanfanghaoyuan":"Official account source",
    "jianghaozhanshi":"Award number display",
    "jianghaoshuoming":"Award number description",
    "gongjujiaoyan":"Tool verification",
    "daojishi":"countdown",
    "qihao":"issue",
    "kaijianghaoma":"Lottery number",
    "haoyuanjinqi":"Source (Recent",
    "wanzhenghaoyuanzhanshi":"Complete source display",
    "zhuaqushijian":"Grab time：%s",
    "shuominghaoyuan":"Explanation: Clicking on a single number source can copy it",
    "bitebipc28quhaojizhi":"Bitcoin PC28 Number Retrieval Mechanism",
    "zhuahaoyuan":"Capture source and obtain unconfirmed transactions (random seeds)",
    "sha256zhuanhua":"SHA256 conversion",
    "shijinzhizhuanhua":"10 base conversion",
    "shengchengzuihzhonghaoma":"Generate final lottery number",
    "zhuahaoyuan_jieshao":"Multiple bet refers to a lottery where the number of selected numbers exceeds the number of single bet numbers, and the selected numbers can be combined into multiple bets for each single bet method. Duo Tuo Bet refers to selecting numbers that are less than the number of single bet numbers as the bile code for each bet, and then selecting numbers other than the bile code as the drag code. The sum of the bile code and the drag code must be more than the number of single bet numbers. Each combination of the bile code and the drag code forms a multi bet lottery bet in a single bet manner.",
    "sha256zhuanhua_jieshao":"The random seed obtained through step one is a summary of all transaction information at a certain point in time, which is a combination of N 64 bit hexadecimal digits. Assuming X is the total transaction amount that occurred at a certain point in time, we can combine these numbers through string concatenation to obtain a 64 bit hexadecimal number, which is counted as Y. By using the SHA256 algorithm to convert Y, it can be converted into a new 64 bit hash value Z and used for the next mathematical operation.",
    "shijinzhizhuanhua_jieshao":"After obtaining Z in step 2, taking its first 16 bits, we can use the decimal conversion formula to obtain a number A in the range of 0-2 ^ 64, which is used to generate the final lottery number.",
    "shengchengzuihzhonghaoma_jieshao":"After obtaining A through step three, divide it by 2 ^ 64 and take the first 3 decimal places of the result to obtain the winning number.",
    "shuruduiyinghaoyuan":"Enter the corresponding number source",
    "jiaoyan":"check",
    "jiaoyanjieguo":"Verification results",
    "sha256zhuanhuahzi":"SHA256 conversion value",
    "quqianshiliuwei":"Take the first 16 digits",
    "shijinweizhuanhuan":"10 carry conversion",
    "chuyierde64cifang":"Divide by two to the power of 64",
    "zuizhongkaijianghaoma":"Final lottery number",
    "shuoming":"illustrate",
    "shuoming_jieshao":"Users can use the relevant online SHA256 function to query websites, repeat all the hash value strings mentioned above, and perform queries. The following provides the query website:",
    "haoyuanchaxun":"Number source query",
    "dianjifuzhi":"Click to copy",
    "nowChat":"Click to negotiate",
    "jiaoyanshuoming":"Verification instructions",
    "jiaoyanshuoming1":"1.Verification instructions",
    "jiaoyanshuoming2":"2.Convert the above string to SHA256",
    "jiaoyanshuoming3":"3.The conversion rules are as follows through mathematical formulas:",
    "jiaoyanshuoming4":"4.Based on the conversion result, select 3 decimal places as the winning number",
    "dixqitouzhu":"Issue%s, Bet:%s",
    "dixqikaijiang":"Issue% s, draw:% s",
    "fengpanzhong":"Under lockdown",
    "dengdaikaipan":"Waiting for opening",
    "shuaxin":"Refresh",
    "kaijiangjieguo":"Lottery results",
    "xitongxiaoxi":"System messages",
    "shujufenxi":"Data analysis",
    "shuangmianchanglong":"Double sided dragon",
    "danshuangluzhu":"Single and double dewdrops",
    "daxiaoluzhu":"Dewdrops of different sizes",
    "haomazhoushi":"Number trend",
    "lx_tongji":"%s statistics",
    "xianshiqishu_":"Display number of periods：%s",
    "zhi":"value",
    "jixiao":"minimum",
    "jida":"extremity",
    "bet_long":"dragon",
    "bet_hu":"tiger",
    "bet_he":"sum",
    "dalu":"main road",
    "zhupanlu":"Zhupan Road",
    "hao_value":"number{value}",
    "qingshuruyouximingcheng":"Please enter the game name",
    "xuanzhe":"select",
    "xuanzhexl":"Select line",
    "quanbuyouxi":"All Games",
    "shoucangla":"Collect it now",
    "qiandaoyouli":"Sign in with courtesy",
    "jifen":"integral",
    "benyueyiqian":"Signed in %s times this month",
    "zongjifen":"Total Score",
    "lijiqiandao":"Sign in immediately",
    "jifenyaojiang":"Points lottery",
    "jifenmeici":"Points:% s (5 points per time)",
    "lianyao5":"Shake 5 times in a row",
    "lianyao10":"Shake 10 times in a row",
    "lianyao15":"Shake 15 times in a row",
    "lianyao20":"Shake 20 times in a row",
    "huodongguizhe":"Activity Rules",
    "jiangjintiqu":"Bonus withdrawal",
    "nianyueri":"YYYY MM DD",
    "bencijiangli":"This reward",
    "gongxiwancheng":"Congratulations on completing the task",
    "xiaciqiandao":"The next check-in reward is% s, which can earn% s points",
    "mingtianjixue":"Continue tomorrow",
    "gongxininhuode":"Congratulations on obtaining",
    "cishu":"Times",
    "lishikaijiang":"Historical lottery",
    "kaijiangzhoushi":"Lottery trend",
    "qugoucai":"Go buy lottery",
    "goucai":"Purchase lottery",
    "xiaoxi":"message",
    "gonggao":"Notice",
    "gonggaoxiangqing":"Announcement details",
    "youhuizhongxin":"Discount Center",
    "chongzhi":"Recharge",
    "quanbu":"All",
    "qita":"Other",
    "fanhui":"Back",
    "wenxintishi_fuzhi":"Kind reminder: \n Long press the number to copy to the clipboard",
    "chongzhizhongxin":"Voucher Center",
    "chongzhizhanghu_":"Recharge account: %s",
    "dangqianmoren":"%s(Current default)",
    "xianshang":"Online (automatic receipt)",
    "xianxia":"Offline (manual deposit)",
    "diyibu_chakanshoukuanxinxi":"The first step is to view the payment information below and proceed with the transfer and recharge:",
    "wenxintishi_zhifuyoushijian":"Kind reminder: There is a time limit for payment, please complete the transfer operation within the specified time",
    "dierbu_tianchongdingdan":"Step 2, fill in the order (remittance information during recharge)",
    "chongzhizhanghu":"Recharge account",
    "huikuanxingming":"Remittance Name",
    "huikuanjine":"Remittance amount",
    "qingshuruhuikuanren":"Please enter the name of the remitter",
    "qingshuruhuikuanjine":"Please enter the remittance amount",
    "tijiao":"submit",
    "bibiduihuan":"Currency exchange",
    "eduzhuanhuan":"Limit conversion",
    "zhifushuoming_rmb":"Payment instructions: \n1. How can company account funds be received from personal accounts? Regulations on the management of RMB bank settlement accounts. \n2. How can company account funds be received from personal accounts? Regulations on the management of RMB bank settlement accounts",
    "zhifushuoming_wallet":"Payment Instructions :\n1. Please select the amount you want to recharge or other amount select the bank you want to use and click Recharge \n2 now. The system will automatically switch to the payment interface, please select the payment method \n3 according to the interface prompt. You can choose online banking or payment by scanning code. After successful payment, please manually return to the APP interface. The amount you recharge will be automatically added to your member account. If you find that the account has not arrived or have any problems, please contact customer service",

    "kahao":"Card number",
    "cikaren":"Cardholder",
    "beizhu":"notes",
    "dianjixiafangzhifu":"Click on the payment redirect link below and read the prompt message",
    "wenxintishi_":"Tips:",
    "wenxintishi_1":"1、The system will automatically open a webpage. Please follow the prompts to continue the operation",
    "wenxintishi_2":"2、Handling fee% s%, high arrival rate!",
    "wenxintishi_3":"%s、%s",
    "tianrujine":"Fill in the amount (1-0) and click OK",
    "shoudongshuruhuoxuanzhe":"Manually enter or select the amount below",
    "diyibu_xuanzhezhifuxieyi":"The first step is to select a payment agreement",
    "dierbu_chakanshoukuanxinxi":"Step 2, check the payment information and proceed with the transfer and recharge",
    "shoukuanzhanghu":"Receiving account",
    "disanbu_tianxierukuanxinxi":"Step 3, fill in the payment information after completing the transfer",
    "fanhuishouye":"homepage",
    "zhifushuoming_":"Payment instructions:",
    "zhifushuoming_1":"1. Minimum deposit :1USDT, maximum deposit: 10000 USDT; \n2. Please use the ",
    "zhifushuoming_2":" protocol to transfer to the receiving account, if you use other virtual currency payment, there may be a loss of funds; \n3. This address is your exclusive address, can be used several times, it is recommended to save",
    "nicheng_":"nickname：%s",
    "wodeqianbao":"my wallet",
    "tixianmima":"Withdrawal password",
    "zijinmingxi":"Financial transactions",
    "bangdingyinhangka":"Bind bank card",
    "bangdingusdt":"Bind USDT",
    "wodetouzhu":"My Bets",
    "touzhujilu":"Betting record",
    "jifenjilu":"Integral record",
    "huiyuanfanshui":"Member return",
    "hongbaohejiangjin":"Red envelopes and bonuses",
    "wodeyinli":"My profit",
    "tuiguangzhuanqian":"Promote and earn money",
    "dializhuce":"Proxy registration",
    "tongyongshezhi":"setting",
    "bangzhuzhongxin":"Help",
    "guanyuwomen":"About Us",
    "tixianzhongxin":"Withdrawal Center",
    "tixianzhanghu_":"Withdrawal account:%s",
    "congcnyqianbaotichu":"Withdrawal from CNY wallet",
    "congusdtqianbaotichu":"Withdrawal from USDT wallet",
    "tixianxinxi":"Withdrawal information",
    "querentixianxinxi":"Confirm withdrawal information",
    "tixianjine":"Withdrawal amount",
    "qingshurutixianmima":"Please enter the withdrawal password",
    "qingshurutixianjine":"Please enter the withdrawal password",
    "querenjine":"Confirm amount",
    "shouxufei":"commission",
    "kedaozhangjine":"Amount that can be credited",
    "qingxuanzhetixianzhanghu":"Please select a withdrawal account",
    "querenjihexinxi":"Confirm audit information",
    "zitixianhouzongtouzhu_":"Total effective bets after the first deposit after self withdrawal: %s",
    "youhuijihe":"Preferential audit",
    "meiyoutongguoyouhui":"Failed to pass the discount audit, discount %s needs to be deducted",
    "tongguoyouhuijihe":"Through preferential audit, there is no need to deduct deposit discounts",
    "changtaixingjihe":"Normal audit",
    "tongguochangtaixing":"Through regular audits, no administrative fees will be charged!",
    "meiyoutongguochangtaixing":"Failure to pass regular audits requires deduction of administrative expenses %s",
    "duocitixian":"Multiple withdrawal handling fees",
    "yixiaoshineimian":"Withdrawals made%s times within%s hours,%s",
    "xukouchushouxufei":"Deduction of handling fees required%s",
    "shixiaoshouxufei":"Time limit handling fee",
    "mianshoushouxufei":"Free of handling fees!",
    "shixiaokouchu":"Withdrawal within %s hours of the last deposit will result in a deduction of%s of the transaction fee for the withdrawal amount",
    "shixiaomianshou":"Withdrawal within%s hours of last deposit, no handling fee charged!",
    "cichijiheshijian":"Date of this audit",
    "meidongshijian_":"US Eastern Time:%s",
    "jixutixian":"Continue to withdraw",
    "tijiaochenggong":"Submitted successfully",
    "tixianxiangqing":"Withdrawal details",
    "tixianzhanghu":"Withdrawal account",
    "tijiaoshijian":"Submission time",
    "shouxufei_":"(commission:%s)",
    "daozhangjine":"Received amount",
    "zhanghuyue":"Account balance",
    "wancheng":"complete",
    "shezhi":"set up",
    "gerenziliao":"personal data",
    "shezhidenglumima":"Set login password",
    "shezhijianyimima":"Set simple password",
    "zhongwen":"Set simple password",
    "quankai":"Full open",
    "tuichudenglu":"Log out and log in",
    "wanshanziliao":"Improve information",
    "nicheng":"nickname",
    "shoujihaoma":"phone number",
    "qqhaoma":"qq number",
    "weixin":"WeChat",
    "shuruweixinhao":"Please enter your WeChat ID",
    "shuruqqhaoma":"Please enter your QQ number",
    "shuruzhenshiyouxiao":"Please enter a real and valid phone number ",
    "shurudianziyouxiang":"Please enter your email address",
    "shurunicheng":"Enter nickname",
    "shezhitixianmima":"Set withdrawal password",
    "yuanmima":"Original password",
    "shuruyuantixianmima":"Enter the original withdrawal password ",
    "xinmima":"Password",
    "shuruxintixianmima":"Enter 4-12 digit new withdrawal password",
    "zaiciqueren":"Reconfirm",
    "chongfushuru":"Repeatedly entering the new withdrawal password",
    "querenjianyimima":"Confirm simple password",
    "shurujianyimima":"Enter a simple password",
    "shezhichenggong":"Set successfully",
    "shuruneirongbuyizhi":"The input content is inconsistent, please try again",
    "wenxintishi_jianyimima":"Kind reminder: \n Some explanatory text, some explanatory text, some explanatory text, some explanatory text",
    "shuruyuandenglumima":"Enter the original login password",
    "shuruxindenglumima":"Enter a new login password of 8-12 digits",
    "chongfushuruxindenglumima":"Repeatedly entering the new login password",
    "genghuantouxiang":"Change avatar",
    "moren":"default",
    "qq":"QQ",
    "jingxuan":"selected",
    "gezhanghumingxi":"Details of credit limits for each account",
    "huazhuanjilu":"Transfer Record",
    "dailizhuce":"Proxy registration",
    "querenmima":"Confirm password",
    "dianziyouxiang":"email",
    "wenxintishi_zhuce":"Reminder: \n1. Marked with an * indicates that the item must be filled out. \n2. Registration means that you have agreed to all \"account opening agreements\"”",
    "jieshaorenxinxi":"Referee Information",
    "daima":"code",
    "fuzhi":"copy",
    "lianjie":"link",
    "tuiguangerweima":"Promote QR codes",
    "baocuntupian":"Save Picture",
    "baocunchenggong":"Successfully saved",
    "fuzhilianjie":"copy link",
    "huiyuanliebiao":"Member List",
    "riqi":"date",
    "xiaxiancunkuan":"Offline deposit",
    "zhuanquhongli":"Earning dividends",
    "xianxiayonghu":"Offline users",
    "zhu_beijingshijian":"Note: Beijing time=US Eastern time+12 hours",
    "riqi_meidong":"Date (US East)",
    "jiaoyileibie":"Transaction category",
    "jiaoyiedu":"Transaction limit",
    "xianyouedu":"Existing integrals",
    "xiazhujifenjiangli":"Rewards for betting points",
    "fuyinglifanshui":"Negative profit return",
    "youxileixing":"Game Type",
    "youxiaotouzhu":"Effective betting",
    "shuying":"Win or lose",
    "fanshui":"rakeback",
    "touzhuliangfanshui":"Betting volume return water",
    "jinrizuhezhanbilv":"Today's betting portfolio ratio",
    "qitayouxi_":"Other games (% s to% s)",
    "huishui":"Refund money",
    "yinlifanshui":"Profit return water",
    "zuhezhanbilv":"Combination proportion",
    "jinri":"today",
    "day_7":"Last 7 days",
    "day_15":"Last 15 days",
    "day_30":"Last 30 days",
    "youxipingtai":"Game platform",
    "bishu":"Number of transactions",
    "touzhue":"Betting amount",
    "youxiaotouzhu_":"Effective Bet:%s Bet Amount:%s",
    "touzhuriqi":"Betting Date (Eastern Time)",
    "wodeyinhangka_":"My bank card:%s cards have been bound (%s cards can still be bound)",
    "wodeshuzhiqianbao_":"My digital wallet:%s bound (can still be bound to%s)",
    "tianjiayinhangka":"Add bank card",
    "zuiduoketianjia_":"(Up to%s sheets can be added)",
    "wenxintixing_yinhangka":"Reminder: \n1. The name of the bank card account holder must match the name entered during registration, otherwise withdrawal cannot be applied for; \n2. Each user can bind up to 3 bank cards; \n3. Once bound, it cannot be modified without authorization. If modification is required, please",
    "tianjiashuziqianbao":"Add a digital wallet",
    "wenxintixing_usdt":"Kind reminder: \n1. Each user can bind up to 3 USDT wallet accounts (one can be bound to different protocols). \n2. Once bound, it cannot be modified without authorization. If modification is needed, please",
    "dizhi":"address",
    "suoshuxieyi":"Agreement",
    "jine":"amount of money",
    "youxiaoqi":"period of validity",
    "xuyaodamaliang":"Required coding quantity",
    "yitiqu":"Extracted",
    "weijihuo":"Not active",
    "yijihuo":"Active",
    "yishixiao":"Expired",
    "tiqu":"Extract",
    "tiquchenggong":"Extraction successful",
    "duihuan":"Exchange",
    "huilv_":"Exchange rate: %s",
    "cong_from":"from",
    "zhi_to":"to",
    "zhuanru":"to change into",
    "huazhuanjine":"Transfer amount",
    "querenhuazhuan":"Confirm transfer",
    "yijianguiji":"One click collection",
    "xuanzheriqi":"Select Date",
    "shaixuan":"screen",
    "cunqukuan":"Deposit/Withdrawal",
    "zhuanzhang":"transfer accounts",
    "zhichu":"expenditure",
    "shouru":"income",
    "qingxuanzhe":"Please select",
    "qing3fenzhonghoushuaxin":"Please refresh this page in 3 minutes to check progress",
    "chongzhixiangqing":"Recharge details",
    "chongzhixingming":"Recharge Name",
    "dingdanbianhao":"Order number",
    "chongzhijine":"Recharge amount",
    "zhongwenjianti":"Simplified Chinese",
    "yingyu":"English",
    "yuenanyu":"Vietnamese",
    "jintian":"today",
    "zuijin7tain":"Last 7 days",
    "zuijin30tian":"Last 30 days",
    "quanbuzhuangtai":"All statuses",
    "chenggong":"Success",
    "chulizhong":"Processing",
    "yiquxiao":"Canceled",
    "quanbufangshi":"All methods",
    "fuzhichenggong":"Replicating Success",
    "qiehuanquanjuqianbao":"Switch Global Wallet",
    "tuijianyouli":"Recommended gifts",
    "qianghongbao":"Snatching red envelopes",
    "zanwuyouxi":"No Game~",
    "fanshuishuoming":"Return water instructions",
    "jiazaizhong":"Loading...",
    "weikaishi":"Not started",
    "jinxingzhong":"In progress",
    "yijieshu":"Ended",
    "hongbaohuodong":"Red envelope activity",
    "xiangqing":"Details",
    "qingxiandenglu":"You haven't logged in yet, please log in first~",
    "jingqingqidai":"Stay tuned~",
    "denglugengjingcai":"More exciting login",
    "gengduo":"More",
    "huishou":"Recovery",
    "sishiershuzihuozimu":"Please enter 4-12 digits or letters for username",
    "bashiershuzihuozimu":"Please enter 8-12 digits or letters for the password",
    "zhenshixingmingbunengkong":"Please enter your real name",
    "yanzhengmabunengkong":"Please enter the verification code",
    "mimashurubuyizhi":"The two password inputs are inconsistent",
    "usdt_coin":"USDT coin",
    "lianxizaixiankefu":"Please contact online customer service",
    "shuruzhuanzhangqianbao":"Please enter the wallet address you used for the transfer",
    "yiwanchengtijiaorukuan":"The transfer has been completed and the payment application has been submitted",
    "qianbaodizhi":"Wallet address",
    "shifoujinxingzhuanzhang":"Have you made a transfer to your receiving account",
    "tishi":"Tips",
    "yinhangmingcheng":"Bank Name",
    "xuanzhezhifuyinhang":"Select payment bank",
    "zhifutiaozhuan":"Payment jump%s",
    "quedingtijiaodingdan":"Are you sure you want to submit the order？",
    "caozuochenggong":"Operation successful",
    "zhuzhanghao":"Main balance",
    "qingxuanzhezhuanru":"Please select the transfer account",
    "qingxuanzhezhuanchu":"Please select the account to transfer out",
    "qingxuanzhetikuanzhanghu":"Please select a withdrawal account",
    "dianjitianjiazhanghu":"Please select a withdrawal account",
    "ninhaimeibangdingyhkzhanghu":"You haven't linked your bank card account yet",
    "ninhaimeibangdingusdtzhanghu":"You haven't linked your USDT account yet",
    "ninhaimeibangdingqianbao":"You have not tied this type of wallet",

    "qubangding":"Unbind",
    "chukuanzhanghu":"Disbursement account",
    "chukuanyinhang":"Disbursement Bank",
    "kaihudizhi":"Account opening address",
    "yanzhengchukuanmima":"Verify payment password",
    "shuruyinhangkakaihudizhi":"Enter the bank card account opening address",
    "liudao12weishuzihuozimu":"6-12 digit numbers or letters",
    "yigezhanghaosanzhangyinhangka":"1. One account can only be linked to three withdrawal bank cards; \n2. If modifications are needed, please contact customer service",
    "qingshuruqianbaodizhi":"Please enter the wallet address",
    "qingshuruqukuanmima":"Please enter the withdrawal password",
    "qianbaoxieyi":"Wallet Protocol",
    "yanzhengzijinmima":"Verify fund password",
    "shuruyinhangzhanghao":"Enter bank account number",
    "qingxuanzhechukuanyinhang":"Please select the issuing bank",
    "qingshuruchukuanmima":"Please enter the withdrawal password",
    "sidao12shuzihuozimu":"4-12 digit numbers or letters",
    "mimacuowu":"Password error",
    "zhanghaomimadenglu":"Account password login",
    "chongzhijymm":"Reset Simple Password",
    "chongzhijymmtishi":"After resetting the simple password, the one you set will be cleared. Please log in with your username and password. After successful login, the simple password will be automatically erased.",
    "qingzaiciyanzhenghaxizhi":"Please enter or paste the hash value you want to verify here",
    "geshangqi":"Interphase",
    "jinrikai":"Open today",
    "wodeshoucang":"My Collection",
    "lianxiwomen":"Contact Us",
    "2023guojizhan":"@2023 International Station",
    "yingyongneijiazai":"Light loading within the application",
    "liulanqidakai":"Open using the default browser of the system",
    "biaozhunshijian":"The standard time on this website is based on US Eastern Time \ n US Eastern Time=Beijing Time -12 hours",
    "zhuninxiacizdj":"Wishing you a big prize next time",
    "jiangjinfengfu":"Get rich bonuses and make a profit",
    "weihuzhong":"Under Maintenance",
    "yiguanpan":"Closed disk",
    "yixiushi":"Closed",
    "yichenggongqiehuan_":"Successfully switched to%s wallet, \ n entering the game will use%s",
    "jifenbuzu":"Insufficient points",
    "xianlu1":"Line 1",
    "xianlu2":"Line 2",
    "xianlu3":"Line 3",
    "xianlu4":"Line 4",
    "xianlu5":"Line 5",
    "xianlu6":"Line 6",
    "julifengpan":"There is still time to close the disk",
    "miao":"second",
    "hyzc":"Member registration",
    "kaishixiazhu":"Start betting",
    "bangdingqitaqianbao":"Bind other wallets",
    "wodeqitaqianbao":"My other wallets: %s bound (%s can still be bound)",
    "zuiduoketianjiaqianbao":"(Up to %s can be added)",
    "qitaqianbaowenxintis":"Tips: \n1. Each user can bind to a maximum of 10 other wallet accounts (one for different types)\n2. Once binding cannot be modified without authorization, if necessary, please modify",
    "qianbaoleixing":"Type of wallet",
    "tixianfangshi":"Withdrawal channel",
    "yhk":"bank card",
    "xqianbao":"%s Wallet",
    "xianlu_":"line %s",
    "julifengpanshijian":"%s to go",
    "dixqi":"No.%s",
    "no":"No.",
    "fengpanxinxi":"Sealing information",
    "kaishifengpan":"Open closing",
    "lianjiefuwushibai":"Link service failed, try again later",
    "kaijiangzhong":"Drawing",
    "qiandaochenggong":"Sign in successfully",
    "benyueleijiqiandao":"The total number of check-ins in this month: ",
    "jiajifen":", +",
    "zaiqiandao":"Number of re-sign-in:",
    "kehuode":", can obtain:",
    "gentou":"follow",
    "zhongjiangjieguodongxiao":"The winning result is dynamic",
    "qingxuanzhetouzhuxm":"Please select a bet",
    "xiazhujinewk":"The bet is short",
    "danmu":"barrage",
    "changqihuodong":"Long-term activity",
    "jiehzhiriqizhi":"The deadline is ",
    "dao":" to ",
    "zanwuxiazhujilu":"No bets recorded",
    "xuanzheleixing":"Select the type",
    "touzhuchenggong":"Successful bet",
    "kaihuxieyi":"Account opening agreement",
    "jieshaoren":"Introducer",
    "shurujieshaoren":"Enter introducer",
    "yuebuzhuqingxianchongzhi":"The balance is insufficient and the bet fails. Whether to go to top up",
    "qingkaitongzhanghu":"请开通任一帐户",
    "huodongweikaiqi":"活动未开启",
    "qingquerenzhudan":"请确认注单",
    "xuanzhonghaoma":"选中号码",
    "peilv":"赔率",
    "ruozhongjiang":"若中奖, 奖金",
    "yinli":", 盈利",
    "zongjine":", 总金额",
    "zunjingdekehu":", 尊敬的客户：\n系统正在维护中，给您造成的不便，还请谅解",
    "xitonggonggao":", 系统公告",
    "yibangding":"已绑定",
    "xuanzhenindemorenqianbao":"Select your default wallet",
    "morenqianbaotishi1":"1.Select your default wallet, and the corresponding currency will be used for settlement when entering the game.",
    "morenqianbaotishi2":"2.The exchange operation between the balances of the two wallets can be performed on the [Exchange] page.",
    "zuida":"最大",
    "shuruyinhangmingcheng":"请输入银行名称",
    "yicizhinengfasong3tiao":"一次只能发送3条语句哦",
    "shuruneirongchaoguozuidaxianzhi":"您输入的内容数量已经超过了最大限制",


  };

}