class VI{
  static const Map<String, String> map ={
    "app_name": "GJZ",
    "pro_time_tip": "Lưu ý giờ Bắc Kinh là 12 giờ miền đông (EST)",
    "other_game_type": "Trò chơi khác",
    "input_chance_money_no_e": "Số dư tài khoản chuyển ra hiện tại không đủ",
    "please_input_old_password": "Vui lòng nhập mật khẩu cũ",
    "please_input_new_password": "Vui lòng nhập mật khẩu mới",
    "please_input_new_again_password": "Vui lòng nhập mật khẩu xác nhận",
    "notice_please": "Vui lòng chú ý",
    "app_brvah_load_failed": "Tải không thành công...",
    "app_brvah_load_complete": "Bấm để tải thêm",
    "user_mess_is_empty": "Thông tin người dùng không được để trống",
    "hongbao_ad": "chương trình nhận lì xì",
    "online_remark_tip_one": "1. APP sẽ tự động mở một trang, vui lòng làm theo lời nhắc để tiếp tục thao tác.",
    "click_to_usdt": "Nhấp để đăng ký địa chỉ ví",
    "with_u_tip": "Ví rút tiền：",
    "tikuan_tip_4": "Số tiền sẽ được chuyển khoản phải lớn hơn 0",
    "wheel_zhongjiang_yuan": "Trúng thưởng: %1\$s %2\$s",
    "discount_time_tip": "Thời gian chương trình: %1\$s 至 %2\$s  ",
    "mod_user_tip1": "1. Bạn cần điền đầy đủ thông tin ngân hàng khi rút tiền, vui lòng vào [Của tôi-cài đặt-đăng ký thẻ ngân hàng] để điền đầy đủ thông tin ngân hàng và đặt mật khẩu rút tiền.",
    "point_bot_tip": "giờ chuẩn của trang web này dựa trên giờ miền đông (EST)\\ giờ miền đông (EST)\u003d北京时间-12小时",
    "home_home": "trang chủ",
    "home_discount": "khuyến mãi",
    "home_recharge": "gửi tiền",
    "home_kefu": "hỗ trợ",
    "home_mine": "của tôi",
    "mine_name": "thông tin cá nhân",
    "mine_eduzhuanhuanu": "chuyển khoản",
    "mine_zijinjiaoyi": "lịch sử qiao dịch",
    "mine_touzhujilu": "lịch sử đặt cược",
    "mine_jifenjilu": "lịch sử điểm thưởng",
    "mine_huiyuanfanshui": "lịch sử hoàn trả",
    "mine_hongbaohejiangjin": "lì xì và tiền thưởng",
    "mine_tuiguangzhuanqian": "kiếm tiền giới thiệu",
    "mine_setting": "cài đặt",
    "mine_tixian": "rút tiền",
    "mine_rukuan": "gửi tiền",
    "mine_tixian_other": "rút tiền từ ví %s",
    "mine_tixian_usdt": "rút tiền từ ví USDT",
    "mine_main_account": "tài khoản chính",
    "mine_jiangjin": "tiền thưởng",
    "mine_jifen": "điểm thưởng",
    "kefu_kefu": "trung tâm chăm sóc khách hàng",
    "discount_discount": "trung tâm khuyến mãi",
    "discount_discount_detail": "chi tiết",
    "discount_coming": "truy cập",
    "discount_back": "trở về",
    "sure": "xác định",
    "nick": "tên nick:",
    "phone": "số điện thoại:",
    "qq_number": "số QQ:",
    "wx_number": "số wechat:",
    "e_mail": "địa chỉ email:",
    "e_mail_tip": "nhập địa chỉ email",
    "wx_number_tip": "nhập số wechat",
    "qq_number_tip": "nhập số QQ",
    "phone_tip": "nhập số điện thoạ thực và hợp lệ",
    "home_show_game": "hiển xổ số",
    "home_start_game": "chơi ngay",
    "game_room_odds_message": "giải thích tỷ lệ cược",
    "dialog_see_more": "xác nhận",
    "dialog_text_switch_money": "chọn ví tiền để chuyển đổi",
    "back": "trở về",
    "no_more": "- không có nhiều hơn -",
    "empty_no_data": "không có nhiều hơn",
    "account_setting": "cài đặt",
    "setting_banding_bank_str": "đăng ký thẻ ngân hàng",
    "setting_banding_usdt_str": "đăng ký USDT",
    "setting_banding_cgp_str": "đăng ký CGPay",
    "setting_set_tixian_password_str": "cài đặt mật khẩu rút tiền",
    "setting_set_login_password_str": "cài đặt mật khẩu đăng nhập",
    "account_please_input_bank_name": "vui lòng nhập họ và tên",
    "account_bank_account_acc": "số tài khoản ngân hàng：",
    "account_bank_account_bank": "tên ngân hàng",
    "account_please_input_bank_number": "vui lòng nhập số tài khoản ngân hàng",
    "account_bank_address": "địa chỉ mở tài khoản：",
    "account_please_select": "vui lòng chọn",
    "account_bank_password": "cài đặt mật khẩu rút tiền：",
    "account_bank_chukuan_password": "cài đặt mật khẩu rút tiền",
    "account_usdt_trc20": "USDT-TRC20(TRON):",
    "account_usdt_ERC20": "USDT-ERC20:",
    "account_usdt_Omini": "USDT-Omini:",
    "account_banding_cgp": "CGPay:",
    "account_banding_cgp_tip": "vui lòng nhập địa chỉ ví",
    "account_set_password_old": "mật khẩu cũ:",
    "account_set_password_old_tip": "nhập mật khẩu cũ",
    "account_set_password_old_tip_2": "nhập mật khẩu đăng nhập cũ",
    "account_set_password_new": "mật khẩu mới:",
    "account_set_password_new_tip": "nhập mật khẩu rút tiền mới 6-12 chữ số hoặc chữ cái",
    "account_set_password_new_tip_2": "nhập mật khẩu đăng nhập mới 8-12 chữ số hoặc chữ cái",
    "account_set_password_new_sure": "xác nhận lần hai:",
    "account_set_password_new_sure_tip": "nhập lại mật khẩu rút tiền mới",
    "account_set_password_new_sure_tip_2": "nhập lại mật khẩu đăng nhập mới",
    "message_center": "trung tâm tin tức",
    "message_notice": "thông báo",
    "message_message": "thông tin",
    "sp_daima": "mã Code:",
    "sp_link": "đường link:",
    "sp_user_message": "thông tin người giới thiệu",
    "sp_promotion_qr": "mã QR",
    "qur_promotion_recode": "tra cứu lịch sử giới thiệu",
    "copy_link": "sao chép đường link",
    "save_img": "lưu ảnh",
    "down_which_qur_time": "chọn thời gian tra cứu bên dưới",
    "time_meifong": "ngày（giờ miền đông (EST)）",
    "time_meifong_2": "ngày đặt cược（giờ miền đông (EST)）",
    "jiaoyi_leibie": "loại giao dịch",
    "jiaoyi_edu": "số tiền giao dịch",
    "xianyou_edu": "số dư hiện tại",
    "mine_fu_return_water": "hoàn trả cược thua",
    "mine_fu_water_tip": "chi tiết hoàn trả",
    "game_type": "loại game",
    "effective_tz": "cược hợp lệ",
    "win_or_fail": "thắng thua",
    "return_water": "hoàn trả",
    "mine_tz_return_water": "hoàn trả số lượng cược",
    "todata_tz_zh": "tỷ lệ cược tổ hợp hôm nay",
    "pc_28": "PC28",
    "agent_user_name": "tên đăng nhập",
    "agent_user_password": "mật khẩu：",
    "really_name": "họ và tên：",
    "really_name2": "họ và tên：",
    "agent_user_tip": "4-12 chữ số hoặc chữ cái",
    "agent_password_tip": "8-12 chữ số hoặc chữ cái",
    "agent_really_tip": "phải trùng với tên tài khoản ngân hàng rút tiền",
    "agent_phone_tip": "nhập số điện thoạ thực và hợp lệ",
    "agent_qq_tip": "số QQ",
    "agent_email_tip": "nhập địa chỉ email",
    "agent_bank_tip": "vui lòng chọn",
    "agent_bank_address_tip": "\u003evui lòng chọn",
    "cny_money_type": "ví CNY",
    "into_money": "chuyển vào",
    "recycling_money": "thu hồi",
    "game_th": "TH",
    "game_ag": "AG",
    "show_all_type": "mở ra tất cả các tài khoản",
    "close_all_type": "thu lại",
    "game_bbin": "BBIN",
    "edu_all_type_tip": "bản xem trước số tiền mỗi tài khoản",
    "edu_into_and_out_tip": "chọn tài khoản chuyển đổi và nhập số tiền chuyển đổi",
    "input_chance_money": "nhập số tiền chuyển đổi",
    "start_chance": "bắt đầu chuyển khoản",
    "start_chance2": "bắt đầu chuyển khoản",
    "yijina_guiji": "quy tụ",
    "xiaz_detail": "chi tiết đặt cược",
    "night_theme": "chế độ ban đêm",
    "day_theme": "chế độ ban ngày",
    "out_app": "đăng xuất",
    "china_str": "中文",
    "vi_str": "Việt Nam",
    "open_music": "bật nhạc",
    "close_music": "đã tắt nhạc",
    "open_tip_misic": "bật âm báo",
    "close_tip_misic": "đã tắt âm báo",
    "online": "trực tuyến",
    "downline": "bình thường",
    "zf_cz_account": "tài khoản gửi tiền：",
    "zf_normal_online_edt_tip": "hập thủ công hoặc chọn số tiền bên dưới",
    "zf_cz_history": "lịch sử gửi tiền",
    "zf_huikuan_name": "tên chuyển tiền：",
    "zf_huikuan_name_tip": "nhập tên của người gửi",
    "zf_huikuan_money": "số tiền chuyển：",
    "zf_huikuan_money_tip": "nhập số tiền chuyển",
    "zf_yinhang_name": "tên ngân hàng：",
    "zf_yinhang_name_tip": "chọn ngân hàng thanh toán",
    "zf_yinhang_huikuan_type": "phương thức chuyển tiền：",
    "zf_yinhang_huikuan_type_tip": "chọn phương thức chuyển tiền",
    "bill_detail": "chi tiết giao dịch",
    "zf_commit_ok_tip": "vui lòng làm mới kiểm tra sau 3 phút",
    "zf_cz_name": "tên gửi tiền",
    "zf_cz_name2": "tên gửi tiền",
    "zf_cz_bill_number": "mã giao dịch",
    "zf_cz_commit_time": "thời gian gửi",
    "zf_cz_money_number": "số tiền gửi",
    "commit_ok": "gửi thành công",
    "all_way": "tất cả phương thức",
    "all_status": "tất cả trạng thái",
    "today": "hôm nay",
    "fast": "nhanh",
    "normal": "bình thường",
    "slow": "chậm",
    "do_no_use": "không khả dụng",
    "entry": "truy cập",
    "please_game_name": "vui lòng nhập tên game",
    "modify_data": "hoàn thiện thông tin",
    "sure_jihe_message": "xác nhận thông tin kiểm toán",
    "sure_tixian_message": "thông tin tài khoản rút tiền",
    "continue_tixian": "tiếp tục rút tiền",
    "tx_money": "số tiền rút",
    "tx_password": "mật khẩu rút tiền：",
    "tx_input_money": "điền số tiền rút",
    "sure_money": "xác nhận số tiền",
    "tx_money_tip": "vui lòng nhập số tiền rút",
    "other_money": "phí thủ tục",
    "realy_get_money": "số tiền sẽ được chuyển khoản",
    "change_avater": "thay đổi hình đại diện",
    "about_us": "về",
    "play_tip_message": "luật chơi",
    "mine_tuiguanghistory": "lịch sử giới thiệu",
    "downline_user": "bạn bè đã giới thiệu",
    "downline_user_money": "bạn bè đã gửi tiền",
    "gethongli": "tiền thưởng nhận được",
    "huiyuanlist": "danh sách giới thiệu",
    "up_page": "trang trước",
    "down_page": "trang sau",
    "nodata_promation": "không tìm thấy thông tin",
    "mine_agent": "đăng ký đại lý",
    "kaijiang_trend": "xu hướng xổ số",
    "sign_in_get_money": "đánh dấu",
    "point_lot": "quay thưởng",
    "go_play": "mua ngay",
    "trend_chart": "biểu đồ xu hướng",
    "history_result": "lịch sử xổ số",
    "point_sign_in": "đánh dấu",
    "point_wheel": "quay thưởng điểm thưởng",
    "loading": "đang tải...",
    "new_err_password": "xác nhận lại mật khẩu không khớp với mật khẩu của bạn",
    "wallet": "ví",
    "plan_close": "cược đang đóng",
    "plan_waiting": "cược chờ",
    "select_in_acc": "vui lòng chọn tài khoản chuyển vào",
    "rate": "tỷ giá tham chiếustring\u003e",
    "account": "tài khoản",
    "record_all": "tất cả lịch sử",
    "record_cun_ti": "gửi rút tiền",
    "record_zhuanzhang": "chuyển khoản",
    "yesterday": "hôm qua",
    "seven_day": "7 ngày gần đây",
    "shi_wu_day": "15 ngày gần đây\"",
    "san_shi_day": "30 ngày gần đây\"",
    "app_brvah_loading": "đang tải...",
    "app_brvah_load_end": "không có nhiều hơn",
    "en_str": "英文",
    "ko_str": "韩国",
    "ind_str": "印度",
    "with_sys_str": "跟随系统",
    "hello_welcome": "chào mừng",
    "please_input_addr": "vui lòng nhập địa chỉ mở tài khoản",
    "please_sele_bank": "vui lòng chọn ngân hàng rút tiền",
    "please_hua_dong": "vui lòng trượt sang phải để xác minh",
    "please_login": "bạn chưa đăng nhập, vui lòng đăng nhập",
    "card_number": "số thẻ",
    "has_card_user": "chủ thẻ",
    "click_bank_band": "thêm thẻ ngân hàng",
    "max_three_card": "(nhiều nhất có thể thêm 3 số lượng)",
    "bank_message_tip": "  ",
    "wallet_addr": "địa chỉ ví： ",
    "xieyi_o": "giao thức",
    "us_message_tip": " ",
    "wa_yixie": "giao thức ví",
    "xieyi": "giao thức",
    "click_bank_band_us": "thêm ví tiền ảo",
    "wa_mu": "chuyển khoản ví tiền",
    "change_money": "số tiền chuyển khoản ",
    "input_money_change": "vui lòng nhập số tiền cần chuyển khoản",
    "rate_maybe": "tỷ giá tham chiếu：  ",
    "realy_get_money_2": "số tiền nhận được：  ",
    "copy_suc": "sao chép thành công",
    "all_day_service": "chăm sóc khách hàng trực tuyến 24/7",
    "hello": "chào, ",
    "defult_av": "hình đại diện mặc định",
    "ava_qq": "hình đại diện QQ",
    "ava_good": "hình đại diện đặc sắc",
    "pay_to": "gửi tiền đến",
    "zf_jump": "liên kết thanh toán",
    "pa_tip": "hướng dẫn thanh toán：",
    "mark": "ghi chú",
    "bank_branch": "chi nhánh ngân hàng",
    "has_card_name": "chủ thẻ",
    "password_no_same": "xác nhận lại mật khẩu không khớp với mật khẩu của bạn",
    "promotion_sp_tip": " ",
    "sele_wa_agreement": "chọn giao thức thanh toán",
    "look_message_and_pay": "kiểm tra thông tin thanh toán để chuyển khoản gửi tiền",
    "need_input_message_about_me": "điền thông tin gửi tiền sau khi hoàn tất chuyển khoản",
    "reminder": "lời nhắc nhở：",
    "online_remark_tip_two_or_three": "2.phí thủ tục %1\$s,tỉ lệ nhận tiền cao!",
    "down_tip_one": "1.có thời hạn thanh toán, vui lòng hoàn tất chuyển khoản trong thời gian quy định。",
    "sure_commit_order": "xác định muốn đặt lệnh giao dịch?",
    "com_tip": "lời nhắc nhở",
    "com_cancel": "hủy",
    "sure2": "xác định",
    "sure_zhuangzhang": "bạn đã chuyển khoản đến tài khoản nhận tiền chưa？",
    "switch_zf_way": "chuyển đổi phương thức gửi tiền",
    "wheel_fail": "dị thường ",
    "point_wheel_integral": "  ",
    "cur_m_has_num": "số lần đã đánh dấu tháng này%1\$s，tổng điểm thưởng %2\$s",
    "with_bank_tip": "tài khoản rút tiền",
    "click_to_bank": "đăng ký thẻ ngân hàng",
    "sele_tix_wa": "vui lòng chọn tài khoản rút tiền",
    "sele_tix_bank": "vui lòng chọn tài khoản rút tiền",
    "date": "ngày",
    "effective_betting_water": "cược hợp lệ",
    "win_or_lose_water": "thắng thua",
    "hui_water": "hoàn trả cược thua",
    "combinbetradio": "tỷ lệ cược tổ hợp",
    "h_hui_water": "hoàn trả cược thua",
    "hasCardUser": "chủ thẻ",
    "my_fav": "sưu tập của tôi",
    "game_name": "tên game",
    "num_all": "số lượng",
    "tz_num": "tiền cược",
    "tz_time": "ngày cược",
    "all": "tất cả",
    "hongbao_number": "số tiền lì xì",
    "need_dama": "lượng cược phải đặt",
    "has_av_time": "thời hạn",
    "status": "trạng thái",
    "jiangjin_number": "tiền thưởng",
    "open_plat": "kích hoạt",
    "main_money": "tài khoản chính",
    "mine_about": "về",
    "about": "về",
    "home_show_game_hide": "ẩn xổ số",
    "home_mianze_notice": "điều kiện và điều khoản",
    "home_jishu_sur": "hỗ trợ kỹ thuật",
    "home_fang_jijie": "hướng dẫn chống tấn công",
    "copy_number": "sao chép",
    "once_to_chat": "chat ngay",
    "go_banding": "đăng ký",
    "please_banding_bank": "bạn chưa đăng ký tài khoản ngân hàng",
    "please_banding_usdt": "bạn chưa đăng ký tài khoản USDT",
    "houdong_longtime": "chương trình lâu dài",
    "houdong_off": "thời hạn đến",
    "tourist": "tài khoản khách",
    "hongbao_weijihuo": "chưa kích hoạt",
    "hongbao_tiqu": "đã kích hoạt",
    "hongbao_tiqu2": "nhận thưởng",
    "hongbao_yitiqu": "đã nhận thưởng",
    "hongbao_yishixiao": "đã hết hạn",
    "home_hongbao_no_login": "vui lòng đăng nhập tài khoản, đăng nhập thành công để tham gia chương trình",
    "home_hongbao_wei_kaishi": "chưa bắt đầu",
    "homn_hongbao_jinxing": "đang tiến hành",
    "home_hongbao_yijishu": "đã kết thúc",
    "home_huiodong_rule": "quy tắc chương trình",
    "home_jiangjin_tiqu": "nhận tiền thưởng",
    "jihe_tip1": "sau khi rút tiền, tổng số tiền cược hợp lệ kể từ lần gửi tiền đầu tiên：",
    "jihe_tip_2_1": "thông qua kiểm toán khuyến mãi, không cần khấu trừ khuyến mãi tiền gửi！",
    "jihe_tip_2_2": "chưa thông qua kiểm toán khuyến mãi, khấu trừ khuyến mãi tiền gửi:",
    "jihe_tip_3_1": "thông qua kiểm toán thông thường, không thu phí hành chính！",
    "jihe_tip_3_2": "chưa thông qua kiểm toán thông thường, khấu trừ phí hành chính :",
    "jihe_changtai": "kiểm toán thông thường:",
    "jihe_youhui": "kiểm toán khuyến mãi:",
    "jihe_duocitixian": "phí thủ tục nhiều lần rút tiền:",
    "jihe_shixiao": "phí thủ tục thời hạn rút tiền",
    "jihe_tip_4_1": "miễn thu phí thủ tục！",
    "jihe_tip_5": "thời gian kiểm toán lần này：giờ miền đông (EST)",
    "jihe_tip_7_1": "rút tiền trong vòng 24 giờ kể từ lần gửi tiền cuối cùng %1\$s rút tiền trong vòng giờ，số tiền rút sẽ bị trừ %2\$s phí thủ tục",
    "jihe_tip_6_1": "%1\$strong vòng giờ %2\$s lần rút tiền，phí thủ tục sẽ được khấu trừ: %3\$s",
    "jihe_tip_6_2": "%1\$s strong vòng giờ %2\$s lần rút tiền ，miễn thu phí thủ tục!",
    "tikuan_tip_1": "vui lòng nhập số tiền rút",
    "tikuan_tip_2": "vui lòng nhập mật khẩu rút tiền",
    "tikuan_tip_3": "vui lòng chọn tài khoản rút tiền",
    "zf_yh_down_tip_2": "điền vào mã giao dịch gửi tiền sau khi hoàn thành các thao tác trên",
    "zf_shuoming": "hướng dẫn thanh toán：",
    "zf_shuoming_content": "\\n 1.vui lòng chọn số tiền bạn muốn gửi hoặc số tiền khác \\n2hệ thống sẽ tự động chuyển đến giao diện thanh toán \\n3.bạn có thể chọn ngân hàng trực tuyến hoặc phương thức thanh toán bằng mã quét \\n 4.sau khi thanh toán thành công\\n5.số tiền gửi sẽ tự động được thêm vào tài khoản thành viên của bạn.",
    "zf_online_tip_1": "nhấp vào đường link thanh toán bên dưới và đọc thông tin nhắc nhở",
    "zf_online_tip_2": "điền số tiền( %1\$s -  %2\$s )và bấm xác định",
    "all_status_suc": "thành công",
    "all_status_weichuli": "đang xử lý",
    "all_status_yiquxiao": "đã hủy",
    "thirty_day": "30 ngày gần đây",
    "wheel_5x": "5x",
    "wheel_10x": "10x",
    "wheel_15x": "15x",
    "wheel_20x": "20x",
    "wheel_congratulations": "chúc mừng bạn",
    "wheel_zhongjiang": "chúc mừng bạn：",
    "wheel_next_zhongjaing": "chúc mừng bạn",
    "wheel_jiangjinfengfu": "tiền thưởng phong phú",
    "wheel_jiangjin": "tiền thưởng：",
    "close": "đóng",
    "wheel_di_ci": "%1\$s số lần ",
    "wheel_keep_it": "tiếp tục cố gắng",
    "room_tema": "số đặc biệt",
    "room_diyiqiu": "số thứ nhất",
    "room_dierqiu": "số thứ hai",
    "room_disanqiu": "số thứ ba",
    "point_click_checkin": "đánh dấu",
    "user_password_resure": "xác nhận mật khẩu",
    "agent_reg_tip_1": "1.mục có dấu*là thông tin bắt buộc",
    "agent_reg_tip_2": "2. đăng ký có nghĩa là bạn chấp nhận điều khoản và điều kiện của trang web",
    "agent_reg_tip_3": "“điều khoản và điều kiện”",
    "ust_tip_1": "1.\"mỗi khách hàng có thể đăng ký tối đa 3 ví tiền ảo；",
    "usd_tip_2": "2.sau khi đã đăng ký không được tự ý sửa đổi,nếu cần sửa đổi, vui lòng",
    "link_kefu": "liên hệ với chăm sóc khách hàng",
    "tingyong_termi": "ngừng sử dụng",
    "bank_tip_1": "1.tên chủ tài khoản ngân hàng phải khớp với tên đã nhập khi đăng ký；",
    "bank_tip_2": "2.mỗi khách hàng có thể đăng ký tối đa 3 thẻ ngân hàng；",
    "bank_tip_3": "3.sau khi đã đăng ký không được tự ý sửa đổi,nếu cần sửa đổi, vui lòng %1\$s",
    "bank_tip_3_2": "2.sau khi đã đăng ký không được tự ý sửa đổi,nếu cần sửa đổi, vui lòng %1\$s",
    "bank_tip_4": "1.mỗi khách hàng chỉ có thể đăng ký 3 thẻ ngân hàng；\\n2.nếu cần sửa đổi, vui lòng liên hệ với chăm sóc khách hàng。",
    "bank_set_passw": "cài đặt mật khẩu rút tiền:",
    "bank_yanz_passw": "xác nhận mật khẩu rút tiền:",
    "bank_chukuan_mima_tip": "6-12 chữ số hoặc chữ cái",
    "long_pre_to_copy": "1.nhấn và giữ số để sao chép；",
    "checkin_tip_1": "số lần đánh dấu tích lũy trong tháng này %1\$s，+ %2\$s điểm thưởng",
    "mod_user_tip2": "2.nếu bạn có bất kỳ câu hỏi nào, vui lòng liên hệ chăm sóc khách hàng",
    "edu_main_money": "số dư chính",
    "select_out_acc": "vui lòng chọn tài khoản chuyển ra",
    "trend_qishu_tip": " ",
    "sun": "Bả",
    "mon": "CN",
    "tue": "T2",
    "wed": "T3",
    "thur": "Tư",
    "fri": "Năm",
    "sat": "Sáu",
    "tixian_tip_1": "1、nếu bạn cần sửa đổi thông tin tài khoản rút tiền, vui lòng liên hệ chăm sóc khách hàng",
    "tixian_tip_2": "2、nếu không có trường hợp đặc biệt, sẽ mất khoảng 3 đến 5 phút để đến tài khoản。",
    "ust_online_tip": "  ",
    "us_shoukuan_a": "tài khoản nhận tiền：",
    "home_line_1": "Kéo xuống để lấy địa chỉ",
    "home_line_2": "Buông ra để lấy địa chỉ ngay",
    "home_line_3": "Đang lấy địa chỉ",
    "home_line_4": "Lấy địa chỉ thành công, vui lòng chọn địa chỉ",
    "home_line_5": "Không lấy được địa chỉ, vui lòng thử lại",
    "home_line_7": "Đang chuyển đổi địa chỉ",
    "home_line_8": "Chuyển đổi địa chỉ thành công",
    "home_line_9": "Chọn",
    "home_line_10": "Đang lấy...",
    "home_line_11": "địa chỉ",
    "updateapk_tip1": "Đang cài đặt chương trình",
    "updateapk_tip2": "Cập nhật nội dung：",
    "updateapk_tip3": "Cập nhật ngay lập tức",
    "updateapk_tip4": "Lần sau hãy nói",
    "updateapk_tip5": "Phiên bản mới nhất：",
    "updateapk_tip6": "Phát hiện phiên bản mới",
    "close_app": "Không chơi thêm một lúc sao?",
    "checkin_tip_2": "Đánh dấu lại",
    "checkin_tip_3": "lần, bạn có thể nhận được",
    "jdc_out_tip": "Có chắc chắn muốn rời khỏi Xổ số Kinh Điển không?",
    "gfc_out_tip": "Có chắc chắn muốn rời khỏi Xổ số Chính Thức không?",
    "out_game_tip": "Có chắc chắn muốn rời khỏi trò chơi không?",
    "line_heard_tip1": "Kéo xuống để lấy địa chỉ",
    "line_heard_tip2": "Đang lấy địa chỉ...",
    "line_heard_tip3": "Lấy địa chỉ thành công",
    "line_heard_tip5": "Không lấy được địa chỉ, vui lòng thử lại",
    "line_heard_tip6": "Thử lại",
    "line_heard_status1": "Tốt",
    "line_heard_status2": "Bình thường",
    "line_heard_status3": "Hơi kém",
    "line_heard_status4": "Quá giờ",
    "jdc_loading": "Đang tải",
    "limit_money": "hạn mức",
    "mine_about_update": "Kiểm tra cập nhật",
    "mine_about_help": "Sử dụng trợ giúp",

    "day_yi":"Một",
    "day_er":"Hai",
    "day_san":"Ba",
    "day_si":"Bốn.",
    "day_wu":"Năm.",
    "day_liu":"Sáu",
    "day_ri":"Bảy",


    "bet_da":"Lớn",
    "bet_xiao":"Nhỏ",
    "bet_dan":"Độc thân",
    "bet_shuang":"Đôi",
    "di":"Số",
    "qi":"Giai đoạn",
    "shifoutuichudenglu":"Thoát đăng nhập",

    "huizhijiesuo":"Vẽ mẫu mở khóa",
    "chonxinshezhi":"Đặt lại",
    "huizhisige":"Vẽ ít nhất 4 điểm",
    "huizhibuyiyang":"Không phù hợp với bản vẽ trước Vui lòng vẽ lại",
    "zaicihuizhi":"Vui lòng vẽ lại mẫu mở khóa",
    "shifouchongxinhuizhi":"Bạn có muốn vẽ lại mẫu mở khóa không？",




    "fangwenluxian":"Lựa chọn lộ trình truy cập",
    "kuai":"Nhanh lên!",
    "yiban":"Tổng quan",
    "henman":"Chậm thôi.",
    "bukeyong":"Không có sẵn",


    "gaunyuwomen": "Về chúng tôi",
    "guanwangjieshao": "Giới thiệu website",
    "xiazhaiyingyong": "Tải ứng dụng",
    "pingtaifuwu": "Dịch vụ nền tảng",
    "yonghuzhongxin": "Trung tâm người dùng",
    "huiyuan": "Thành viên",
    "chongzhijilu": "Hồ sơ nạp tiền",
    "qiandaochoujiang": "Đăng ký rút thăm trúng thưởng",
    "jishuzhichi": "Hỗ trợ kỹ thuật",
    "fangjiechijiaocheng": "Hướng dẫn Anti-Hijacking",
    "fangjiechi": "Chống cướp",
    "shiyongbangzhu": "Sử dụng trợ giúp",
    "xuanzeyuyan":"Chọn ngôn ngữ",


    "changyongduanyu":"Cụm từ thường dùng",
    "qitaduanyu":"Các cụm từ khác",
    "biaoqing":"Biểu tượng",
    "gif":"gif",
    "dixqi":"%s",






  };
}