class VI{
  static const Map<String, String> map = {
    "home_home": "trang chủ",
    "home_discount": "khuyến mãi",
    "home_recharge": "gửi tiền",
    "home_kefu": "hỗ trợ",
    "home_mine": "của tôi",
    "mine_name": "Thông tin cá nhân",
    "mine_eduzhuanhuanu": "chuyển khoản",
    "mine_zijinjiaoyi": "lịch sử giao dịch",
    "mine_touzhujilu": "Lịch sử đặt cược",
    "mine_jifenjilu": "lịch sử điểm thưởng",
    "mine_huiyuanfanshui": "lịch sử hoàn trả",
    "mine_hongbaohejiangjin": "lì xì và tiền thưởng",
    "mine_tuiguangzhuanqian": "kiếm tiền giới thiệu",
    "mine_setting": "cài đặt",
    "mine_tixian": "rút tiền",
    "mine_rukuan": "gửi tiền",
    "mine_tixian_other": "rút tiền từ ví %s",
    "mine_tixian_usdt": "rút tiền từ ví USDT",
    "mine_main_account": "TK chính",
    "mine_jiangjin": "tiền thưởng",
    "mine_jifen": "điểm thưởng",
    "kefu_kefu": "trung tâm chăm sóc khách hàng",
    "discount_discount": "trung tâm khuyến mãi",
    "discount_discount_detail": "优惠内容",
    "discount_coming": "truy cập",
    "discount_back": "trở về",
    "sure": "xác định",
    "nick": "tên nick:",
    "phone": "số điện thoại:",

    "qq_number": "số QQ:",
    "wx_number": "số wechat:",
    "e_mail": "địa chỉ email:",
    "e_mail_tip": "nhập địa chỉ email",
    "wx_number_tip": "nhập số wechat",
    "qq_number_tip": "nhập số QQ",
    "phone_tip": "nhập số điện thoạ thực và hợp lệ",
    "home_show_game": "hiển xổ số",
    "home_start_game": "chơi ngay",
    "game_room_odds_message": "giải thích tỷ lệ cược",
    "dialog_see_more": "xác nhận",
    "dialog_text_switch_money": "选择要切换的钱包",
    "back": "trở về",
    "no_more": "- không có nhiều hơn -",
    "empty_no_data": "空空如也",
    "account_setting": "cài đặt",
    "setting_banding_bank_str": "đăng ký thẻ ngân hàng",
    "setting_banding_usdt_str": "đăng ký ví USDT",
    "setting_banding_cgp_str": "绑定CGPay",
    "setting_set_tixian_password_str": "cài đặt mật khẩu rút tiền",
    "setting_set_login_password_str": "cài đặt mật khẩu đăng nhập",
    "account_please_input_bank_name": "请输入银行卡姓名",
    "account_bank_account_acc": "số tài khoản ngân hàng:",
    "account_bank_account_bank": "tên ngân hàng",
    "account_please_input_bank_number": "vui lòng nhập số tài khoản ngân hàng",
    "account_bank_address": "địa chỉ mở tài khoản:",
    "account_please_select": "vui lòng chọn",
    "account_bank_password": "mật khẩu rút tiền：",
    "account_bank_chukuan_password": "请输入出款密码",
    "account_usdt_trc20": "USDT-TRC20(TRON):",
    "account_usdt_ERC20": "USDT-ERC20:",
    "account_usdt_Omini": "USDT-Omini:",
    "account_banding_cgp": "CGPay:",
    "account_banding_cgp_tip": "vui lòng nhập địa chỉ ví",
    "account_set_password_old": "mật khẩu cũ:",
    "account_set_password_old_tip": "nhập mật khẩu cũ",
    "account_set_password_old_tip_2": "Enter current password",
    "account_set_password_new": "New Password:",
    "account_set_password_new_tip": "输入6-12位新提现密码",
    "account_set_password_new_tip_2": "8-12 chữ số hoặc chữ cái",
    "account_set_password_new_sure": "xác nhận lần hai:",
    "account_set_password_new_sure_tip": "nhập lại mật khẩu rút tiền mới",
    "account_set_password_new_sure_tip_2": "nhập lại mật khẩu đăng nhập mới",
    "message_center": "trung tâm tin tức",
    "message_notice": "thông báo",
    "message_message": "thông tin",
    "sp_daima": "mã Code",
    "sp_link": "đường link",
    "sp_user_message": "thông tin người giới thiệu",
    "sp_promotion_qr": "mã QR",
    "qur_promotion_recode": "tra cứu lịch sử giới thiệu",
    "copy_link": "sao chép",
    "save_img": "lưu ảnh",
    "down_which_qur_time": "chọn thời gian tra cứu bên dưới",
    "pro_time_tip": "lưu ý giờ Bắc Kinh là 12 giờ miền đông (EST)",
    "time_meifong": "日期（美东）",
    "time_meifong_2": "投注日期（美东时间）",
    "jiaoyi_leibie": "giao dịch",
    "jiaoyi_edu": "số tiền",
    "xianyou_edu": "số dư",
    "mine_fu_return_water": "hoàn trả cược thua",
    "mine_fu_water_tip": "chi tiết hoàn trả",
    "game_type": "loại game",
    "effective_tz": "cược hợp lệ",
    "win_or_fail": "thắng thua",
    "return_water": "hoàn trả",
    "other_game_type": "其他游戏",
    "mine_tz_return_water": "hoàn trả số lượng cược",
    "todata_tz_zh": "tỷ lệ cược tổ hợp hôm nay",
    "pc_28": "PC28蛋蛋",
    "agent_user_name": "tên đăng nhập",
    "agent_user_password": "mật khẩu",
    "really_name": "họ và tên",
    "really_name2": "họ và tên",
    "agent_user_tip": "số hoặc chữ cái: 4-12",
    "agent_password_tip": "8-12 chữ số hoặc chữ cái",
    "agent_really_tip": "phải trùng với tên tài khoản ngân hàng rút tiền",
    "agent_phone_tip": "nhập số điện thoạ thực và hợp lệ",
    "agent_qq_tip": "nhập số QQ",
    "agent_email_tip": "nhập địa chỉ email",
    "agent_bank_tip": "vui lòng chọn",
    "agent_bank_address_tip": "Please select",
    "cny_money_type": "ví CNY",
    "into_money": "chuyển vào",
    "recycling_money": "thu hồi",
    "game_th": "TH",
    "game_ag": "AG",
    "show_all_type": "mở rộng",
    "close_all_type": "thu lại",
    "game_bbin": "BBIN",
    "edu_all_type_tip": "bản xem trước số tiền mỗi tài khoản",
    "edu_into_and_out_tip": "选择转账账户 和 输入转账金额",
    "input_chance_money": "输入转换金额",
    "start_chance": "bắt đầu chuyển khoản",
    "start_chance2": "bắt đầu chuyển khoản",
    "yijina_guiji": "quy tụ",
    "xiaz_detail": "chi tiết đặt cược",
    "night_theme": "chế độ ban đêm",
    "day_theme": "chế độ ban ngày",
    "out_app": "đăng xuất",
    "china_str": "中文",
    "vi_str": "Việt Nam",
    "open_music": "bật nhạc",
    "close_music": "đã tắt nhạc",
    "open_tip_misic": "bật âm báo",
    "close_tip_misic": "đã tắt âm báo",
    "online": "trực tuyến",
    "downline": "bình thường",
    "zf_cz_account": "tài khoản gửi tiền",
    "zf_normal_online_edt_tip": "nhập thủ công hoặc chọn số tiền bên dưới",
    "zf_cz_history": "lịch sử gửi tiền",
    "zf_huikuan_name": "tên chuyển tiền",
    "zf_huikuan_name_tip": "nhập tên của người gửi",
    "zf_huikuan_money": "số tiền chuyển",
    "zf_huikuan_money_tip": "nhập số tiền chuyển",
    "zf_yinhang_name": "tên ngân hàng",
    "zf_yinhang_name_tip": "chọn ngân hàng thanh toán",
    "zf_yinhang_huikuan_type": "phương thức chuyển tiền",
    "zf_yinhang_huikuan_type_tip": "chọn phương thức chuyển tiền",
    "bill_detail": "chi tiết giao dịch",
    "zf_commit_ok_tip": "vui lòng làm mới kiểm tra sau 3 phút",
    "zf_cz_name": "tên gửi tiền",
    "zf_cz_name2": "tên gửi tiền",
    "zf_cz_bill_number": "mã giao dịch",
    "zf_cz_commit_time": "thời gian gửi",
    "zf_cz_money_number": "số tiền gửi",
    "commit_ok": "Gửi thành công",
    "all_way": "phương thức",
    "all_status": "trạng thái",
    "today": "hôm nay",
    "fast": "nhanh",
    "normal": "thường",
    "slow": "chậm",
    "do_no_use": "yếu",
    "entry": "truy cập",
    "please_game_name": "nhập tên game",
    "modify_data": "hoàn thiện thông tin",
    "sure_jihe_message": "xác nhận thông tin kiểm toán",
    "sure_tixian_message": "确认提现账户信息",
    "continue_tixian": "tiếp tục rút tiền",
    "tx_money": "số tiền rút",
    "tx_password": "mật khẩu rút tiền",
    "tx_input_money": "điền số tiền rút",
    "sure_money": "xác nhận số tiền",
    "tx_money_tip": "vui lòng nhập số tiền rút",
    "other_money": "phí thủ tục",
    "realy_get_money": "số tiền sẽ được chuyển khoản",
    "change_avater": "thay đổi hình đại diện",
    "about_us": "về",
    "play_tip_message": "luật lệ",
    "mine_tuiguanghistory": "lịch sử giới thiệu",
    "downline_user": "bạn bè đã giới thiệu",
    "downline_user_money": "bạn bè đã gửi tiền",
    "gethongli": "tiền thưởng nhận được",
    "huiyuanlist": "danh sách giới thiệu",
    "up_page": "trang trước",
    "down_page": "trang sau",
    "nodata_promation": "không tìm thấy thông tin",
    "mine_agent": "đăng ký đại lý",
    "kaijiang_trend": "biểu đồ",
    "sign_in_get_money": "đánh dấu",
    "point_lot": "quay số",
    "go_play": "mua ngay",
    "trend_chart": "biểu đồ",
    "history_result": "lịch sử",
    "point_sign_in": "đánh dấu",
    "point_wheel": "quay số",
    "loading": "加载中...",
    "please_input_old_password": "请输入旧密码",
    "please_input_new_password": "请输入新密码",
    "please_input_new_again_password": "请输入确认密码",
    "new_err_password": "xác nhận lại mật khẩu không khớp với mật khẩu của bạn",
    "notice_please": "敬请注意",
    "wallet": " Ví",
    "plan_close": "cược đang đóng",
    "plan_waiting": "cược chờ mở",
    "select_in_acc": "vui lòng chọn tài khoản chuyển vào",
    "rate": "Tỷ giá：",
    "account": "tài khoản",
    "record_all": "tất cả lịch sử",
    "record_cun_ti": "gửi rút tiền",
    "record_zhuanzhang": "chuyển khoản",
    "yesterday": "hôm qua",
    "seven_day": "7 ngày gần đây",
    "shi_wu_day": "15 ngày gần đây",
    "app_brvah_loading": "正在加载中...",
    "app_brvah_load_end": "没有更多数据",
    "app_brvah_load_failed": "加载失败...",
    "app_brvah_load_complete": "点击加载更多",
    "en_str": "英文",
    "ko_str": "韩国",
    "ind_str": "印度",
    "with_sys_str": "跟随系统",
    "hello_welcome": "您好，欢迎光临",
    "please_input_addr": "请输入开户地址",
    "please_sele_bank": "请选择银行卡",
    "please_hua_dong": "请滑动验证",
    "user_mess_is_empty": "用户信息不能为空",
    "please_login": "bạn chưa đăng nhập, vui lòng đăng nhập",
    "card_number": "số thẻ",
    "has_card_user": "chủ thẻ",
    "click_bank_band": "thêm thẻ ngân hàng",
    "max_three_card": "(nhiều nhất có thể thêm 3)",
    "bank_message_tip": "  ",
    "wallet_addr": "địa chỉ ví",
    "xieyi_o": "giao thức",
    "us_message_tip": " ",
    "wa_yixie": "giao thức ví",
    "xieyi": "giao thức",
    "click_bank_band_us": "thêm ví tiền ảo",
    "wa_mu": "钱包额度互转",
    "change_money": "số tiền chuyển",
    "input_money_change": "nhập số tiền",
    "rate_maybe": "tỷ giá tham chiếu",
    "realy_get_money_2": "số tiền nhận",
    "copy_suc": "sao chép thành công",
    "all_day_service": "chăm sóc khách hàng trực tuyến 24/7",
    "hello": "chào ",
    "defult_av": "hình đại diện mặc định",
    "ava_qq": "hình đại diện QQ",
    "ava_good": "hình đại diện đặc sắc",
    "pay_to": "充值到",
    "zf_jump": "liên kết thanh toán",
    "pa_tip": "hướng dẫn thanh toán",
    "mark": "ghi chú",
    "bank_branch": "chi nhánh ngân hàng",
    "has_card_name": "chủ thẻ",
    "password_no_same": "xác nhận lại mật khẩu không khớp với mật khẩu của bạn",
    "promotion_sp_tip": " ",
    "sele_wa_agreement": "chọn giao thức thanh toán",
    "look_message_and_pay": "kiểm tra thông tin nhận bên dưới để chuyển khoản gửi tiền",
    "need_input_message_about_me": "điền thông tin gửi tiền sau khi hoàn tất chuyển khoản",
    "hongbao_ad": "红包活动",
    "reminder": "lời nhắc nhở",
    "online_remark_tip_one": "1.APP会自动打开一个页面，请按提示继续操作。",
    "online_remark_tip_two_or_three": "2.phí thủ tục %1\$s,tỉ lệ nhận tiền cao",
    "down_tip_one": "có thời hạn thanh toán, vui lòng hoàn tất chuyển khoản trong thời gian quy định",
    "sure_commit_order": "xác định muốn đặt lệnh giao dịch?",
    "com_tip": "lời nhắc nhở",
    "com_cancel": "hủy",
    "sure2": "xác định",
    "sure_zhuangzhang": "bạn đã chuyển khoản đến tài khoản nhận tiền chưa",
    "switch_zf_way": "chuyển đổi phương thức gửi tiền",
    "wheel_fail": "摇奖失败",
    "point_wheel_integral": "  ",
    "cur_m_has_num": "本月已签到%1\$s次，剩余积分%2\$s",
    "with_bank_tip": "提现银行卡",
    "click_to_bank": "点击绑定银行卡",
    "sele_tix_wa": "选择提现钱包",
    "sele_tix_bank": "选择提现银行卡",
    "click_to_usdt": "点击绑定钱包地址",
    "with_u_tip": "提现钱包：",
    "date": "ngày",
    "effective_betting_water": "cược hợp lệ",
    "win_or_lose_water": "thắng thua",
    "hui_water": "hoàn trả cược thua",
    "combinbetradio": "tỷ lệ cược tổ hợp",
    "h_hui_water": "hoàn trả cược thua",
    "hasCardUser": "chủ thẻ",
    "my_fav": "sưu tập của tôi",
    "game_name": "tên game",
    "num_all": "số lượng",
    "tz_num": "tiền cược",
    "tz_time": "ngày cược",
    "all": "tất cả",
    "hongbao_number": "số tiền",
    "need_dama": "lượng cược phải đặt",
    "has_av_time": "thời hạn",
    "status": "trạng thái",
    "jiangjin_number": "tiền thưởng",
    "open_plat": "kích hoạt",
    "main_money": " TK chính",
    "mine_about": "về",
    "about": "về",
    "home_show_game_hide": "ẩn xổ số",
    "home_mianze_notice": "điều kiện và điều khoản",
    "home_jishu_sur": "hỗ trợ kỹ thuật",
    "home_fang_jijie": "hướng dẫn chống tấn công",
    "copy_number": "sao chép",
    "once_to_chat": "chat ngay",
    "go_banding": "đăng ký",
    "please_banding_bank": "bạn chưa đăng ký tài khoản ngân hàng",
    "please_banding_usdt": "bạn chưa đăng ký tài khoản USDT",
    "houdong_longtime": "chương trình lâu dài",
    "houdong_off": "thời hạn đến",
    "tourist": "tài khoản khách",
    "hongbao_weijihuo": "chưa kích hoạt",
    "hongbao_tiqu": "đã kích hoạt",
    "hongbao_tiqu2": "nhận thưởng",
    "hongbao_yitiqu": "đã nhận thưởng",
    "hongbao_yishixiao": "đã hết hạn",
    "home_hongbao_no_login": "vui lòng đăng nhập tài khoản, đăng nhập thành công để tham gia chương trình",
    "home_hongbao_wei_kaishi": "chưa bắt đầu",
    "homn_hongbao_jinxing": "đang tiến hành",
    "home_hongbao_yijishu": "đã kết thúc",
    "home_huiodong_rule": "quy tắc chương trình",
    "home_jiangjin_tiqu": "nhận tiền thưởng",
    "jihe_tip1": "sau khi rút tiền, tổng số tiền cược hợp lệ kể từ lần gửi tiền đầu tiên",
    "jihe_tip_2_1": "thông qua kiểm toán khuyến mãi, không cần khấu trừ khuyến mãi tiền gửi",
    "jihe_tip_2_2": "chưa thông qua kiểm toán khuyến mãi, khấu trừ khuyến mãi tiền gửi",
    "jihe_tip_3_1": "thông qua kiểm toán thông thường, không thu phí hành chính",
    "jihe_tip_3_2": "chưa thông qua kiểm toán thông thường, khấu trừ phí hành chính",
    "jihe_changtai": "kiểm toán thông thường",
    "jihe_youhui": "kiểm toán khuyến mãi",
    "jihe_duocitixian": "phí thủ tục nhiều lần rút tiền",
    "jihe_shixiao":"phí thủ tục thời hạn rút tiền",
    "jihe_tip_4_1": "miễn thu phí thủ tục",
    "jihe_tip_5": "thời gian kiểm toán lần này：giờ miền đông (EST)",
    "jihe_tip_7_1": "rút tiền trong vòng %1\$s giờ kể từ lần gửi tiền cuối cùng,số tiền rút sẽ bị trừ %2\$s phí thủ tục",
    "jihe_tip_6_1": "%1\$s giờ %2\$s lần rút tiền,phí thủ tục sẽ được khấu trừ: %3\$s",
    "jihe_tip_6_2": "%1\$s giờ %2\$s lần rút tiền,miễn thu phí thủ tục",
    "tikuan_tip_1": "请输入提款金额",
    "tikuan_tip_2": "请输入提款密码",
    "tikuan_tip_3": "请选择提款账号",
    "tikuan_tip_4": "可到账金额必须大于0",
    "zf_yh_down_tip_2": "điền vào mã giao dịch gửi tiền sau khi hoàn thành các thao tác trên",
    "zf_shuoming": "hướng dẫn thanh toán",
    "zf_shuoming_content": "\\n vui lòng chọn số tiền bạn muốn gửi hoặc số tiền khác \\nhệ thống sẽ tự động chuyển đến giao diện thanh toán \\nbạn có thể chọn ngân hàng trực tuyến hoặc phương thức thanh toán bằng mã quét \\n sau khi thanh toán thành công \\nsố tiền gửi sẽ tự động được thêm vào tài khoản thành viên của bạn",
    "zf_online_tip_1": "nhấp vào đường link thanh toán bên dưới và đọc thông tin nhắc nhở",
    "zf_online_tip_2": "điền số tiền ( %1\$s -  %2\$s ) và bấm xác định",
    "user_password_resure": "xác nhận mật khẩu",
    "agent_reg_tip_1": "1.mục có dấu * là thông tin bắt buộc",
    "agent_reg_tip_2": "2.đăng ký có nghĩa là bạn chấp nhận điều khoản và điều kiện của trang web",
    "agent_reg_tip_3": "điều khoản và điều kiện",
    "ust_tip_1": "mỗi khách hàng có thể đăng ký tối đa 3 ví tiền ảo",
    "link_kefu": "liên hệ với chăm sóc khách hàng",
    "tingyong_termi": "ngừng sử dụng",
    "bank_tip_1": "tên chủ tài khoản ngân hàng phải khớp với tên đã nhập khi đăng ký",
    "bank_tip_2": "mỗi khách hàng có thể đăng ký tối đa 3 thẻ ngân hàng",
    "bank_tip_3": "sau khi đã đăng ký không được tự ý sửa đổi,nếu cần sửa đổi, vui lòng %1\$s",
    "bank_tip_3_2": "sau khi đã đăng ký không được tự ý sửa đổi,nếu cần sửa đổi, vui lòng %1\$s",
    "bank_set_passw": "cài đặt mật khẩu rút tiền",
    "bank_yanz_passw": "xác nhận mật khẩu rút tiền",
    "bank_chukuan_mima_tip": "6-12 chữ số hoặc chữ cái",
    "long_pre_to_copy": "nhấn và giữ số để sao chép",
    "checkin_tip_1": "ố lần đánh dấu tích lũy trong tháng này %1\$s lần,+ %2\$s điểm thưởng",
    "mod_user_tip1": "điền đầy đủ thông tin ngân hàng để rút tiền",
    "mod_user_tip2": "nếu bạn có bất kỳ câu hỏi nào, vui lòng liên hệ chăm sóc khách hàng",
    "edu_main_money": "số dư chính",
    "select_out_acc": "vui lòng chọn tài khoản chuyển ra",
    "us_shoukuan_a": "Receiver's Account",





    "day_yi":"T2",
    "day_er":"T3",
    "day_san":"T4",
    "day_si":"T5",
    "day_wu":"T6",
    "day_liu":"T7",
    "day_ri":"CN",
    "bet_da":"tài",
    "bet_xiao":"xỉu",
    "bet_dan":"lẻ",
    "bet_shuang":"chẵn",
    "di":"No.",
    "qi":"",
    "shifoutuichudenglu":"Có đăng xuất hay không",

    "huizhijiesuo":"Vẽ mẫu mở khóa",
    "chonxinshezhi":"Cài đặt lại",
    "huizhisige":"Hãy vẽ ít nhất 4 điểm",
    "huizhibuyiyang":"Không phù hợp với bản vẽ cuối cùng xin vui lòng vẽ lại",
    "zaicihuizhi":"Xin vẽ lại mẫu mở khóa",
    "shifouchongxinhuizhi":"Bạn có muốn vẽ lại mẫu mở khóa không?",


    "fangwenluxian":"lựa chọn địa chỉ truy cập",
    "kuai":"nhanh",
    "yiban":"thường",
    "henman":"chậm",
    "bukeyong":"yếu",





    "gaunyuwomen": "về",
    "guanwangjieshao": "官网介绍",
    "xiazhaiyingyong": "Tải xuống ứng dụng",
    "pingtaifuwu": "平台服务",
    "yonghuzhongxin": "Trung tâm khách hàng",
    "huiyuan": "会员",
    "chongzhijilu": "Lịch sử gửi tiền",
    "qiandaochoujiang": "Đánh dấu Quay số",
    "jishuzhichi": "hỗ trợ kỹ thuật",
    "fangjiechijiaocheng": "hướng dẫn chống tấn công",
    "fangjiechi": "Chống cướp",
    "shiyongbangzhu": "Trợ giúp sử dụng",
    "xuanzeyuyan":"Chọn ngôn ngữ",
    "duanyu":"cụm từ",
    "changyong":"thường dùng",
    "zayu":"杂语",
    "biaoqing":"biểu cảm",
    "gif":"GIF",

    "yue_":"Số dư: ",
    "home": "trang chủ",
    "mine": "của tôi",
    "preferential": "khuyến mãi",
    "charge": "gửi tiền",
    "tixian": "rút tiền",
    "choujiang": "quay số",
    "zoushi": "biểu đồ",
    "customer_service": "hỗ trợ",
    "theme": "主题",
    "pick_time": "Lựa chọn thời gian",
    "remen": "Hấp dẫn",
    "zuijin": "Gần đây",
    "shoucang": "Sưu tập",
    "shedingyuyan":'*Vui lòng chọn ngôn ngữ mặc định: "*Vui lòng chọn ngôn ngữ mặc định, bạn có thể đặt ngôn ngữ này sau trong "Thêm" hoặc "Cài đặt của tôi',
    "morenyuyan":"Ngôn ngữ mặc định",
    "tiaoguo":"Bỏ qua",
    "queren":"Xác nhận",
    "xuanzeqianbao":"chọn ví tiền để chuyển đổi",
    "morenqianbao":"Ví mặc định",
    "shedingqianbao":'*Vui lòng chọn ví mặc định: "*Vui lòng chọn ví mặc định, bạn có thể đặt ví này sau trong "Thêm" hoặc "Ví của tôi',
    "rmb":"人民币（CNY）",
    "dollar":"美元（US）",
    "thb":"泰铢（Thai Baht）",
    "vnd":"越南盾（VND）",
    "hyld_boya":"Welcome to BOYA CASINO",
    "hyld_dw":"Welcome to DW International",
    "qqzlxd":"Website giải trí hàng đầu thế giới",
    "register":"Đăng ký",
    "login":"Đăng nhập",
    "grzx":"Thông tin cá nhân",
    "rmbqb":"人民币钱包",
    "edzh":"chuyển khoản",
    "pcxq":"Chi tiết PC",
    "tzjl":"Lịch sử đặt cược",
    "jymm":"Mật khẩu đơn giản",
    "dyy":"Đa ngôn ngữ",
    "bjyy":"Nhạc nền",
    "tsy":"Âm báo",
    "wgys":"Giao diện/Màu sắc",
    "qs":"Màu nhạt",
    "dx":"Hoạt hình",
    "qk":"Mở hoàn toàn",
    "fxghy":"Chia sẻ cùng bạn bè",
    "ycfx":"Chia sẻ một lần, hoa hồng không giới hạn",
    "xzapp":"Tải xuống ứng dụng",
    "lxjbhb":"Tận hưởng ngay lì xì 888 xu vàng",
    "logout":"Thoát",
    "xzndyy":"Chọn ngôn ngữ của bạn",
    "sszcbz":"搜索支持币种",
    "zxndbz":"选择您的币种",
    "bbdh":"Trao đổi tiền tệ",
    "lxkf":"Liên hệ với chăm sóc khách hàng",
    "yhm":"tên đăng nhập",
    "qsryhm":"请输入用户名",
    "mm":"mật khẩu",
    "qsrmm":"请输入密码",
    "wjmm":"quên mật khẩu",
    "cjygzxh":"创建一个新账户",
    "kfzx":"trung tâm chăm sóc khách hàng",
    "xszxkf":"24小时在线客服",
    "qthwnfw":"chăm sóc khách hàng trực tuyến 24/7",
    "djjr":"点击进入",
    "dxtxsz":"Cài đặt hoạt hình nhắc nhở",
    "fpdx":"Cài đặt hoạt hình nhắc nhở",
    "cksl":"Xem ví dụ",
    "kjjgdx":"Hoạt hình kết quả xổ số",
    "djsdx":"Hoạt hình đếm ngược",
    "wgsz":"Cài đặt giao diện",
    "qzb":"Thuần trắng",
    "kxh":"Đen ngầu",
    "cjzh":"创建账户",
    "hyzc":"đăng ký thành viên",
    "wszhzm":"8-12 chữ số hoặc chữ cái",
    "zsxm":"họ và tên",
    "yzm":"mã xác nhận",
    "qsrzcyzm":"nhập mã xác nhận",
    "wywdbty":"đăng ký có nghĩa là bạn chấp nhận điều khoản và điều kiện của trang web",
    "yhtk":"《用户条款》",
    "and":"和",
    "ysxy":"《隐私协议》",
    "yyzh":"已有账户?",
    "ytxyhkhmyz":"phải trùng với tên tài khoản ngân hàng rút tiền",
    "tab_pcfj":"PC房间",
    "tab_cp":"彩票",
    "tab_zr":"真人",
    "tab_ty":"体育",
    "tab_by":"捕鱼",
    "tab_dz":"电子",
    "card_ptf":"普通房",
    "card_gjf":"高级房",
    "card_gbf":"贵宾房",
    "dangqianzaixian":"%s|%s",
    "peilvshuoming":"giải thích tỷ lệ cược",
    "wanfaguizhe":"luật lệ",
    "youxishuyu":"Thuật ngữ chơi game",
    "xiazhujiqiao":"Mẹo cá cược",
    "wanfaguizhe_jieshao":"给大家介绍下玩法规则,为了游…",
    "youxishuyu_jieshao":"了解常用的术语后提高游戏效…",
    "xiazhujiqiao_jieshao":"以下是一些下注的技巧,例如…",
    "haoyuan":"nguồn",
    "zhudan":"đơn cược",
    "mipai":"cào số",
    "qushi":"biểu đồ",
    "juelidixqi":"lượt xổ %s",
    "zongyue":"số dư",
    "touzhu":"đặt cược",
    "zhudan_":"đơn cược",
    "zongji_":"，tổng cộng：",
    "qiehuanfangjian":"切换房间",
    "confirm":"xác định",
    "cancel":"hủy",
    "tema":"số đặc biệt",
    "diyiqiu":"số thứ nhất",
    "dierqiu":"số thứ hai",
    "disanqiu":"số thứ ba",
    "qingshurujine":"Vui lòng nhập số tiền",
    "zongji":"tổng cộng",
    "end":"đã kết thúc",
    "xiazhuxiangqing":"chi tiết đặt cược",
    "quanbujilu":"tất cả lịch sử",
    "xiazhujine":"tiền cược",
    "keyingjine":"lợi nhuận",
    "xiaoji":"tổng",
    "xbi":"%s số lượng",
    "qihao_":"số lượt xổ:%s",
    "wallet_cny":"ví CNY",
    "wallet_usdt":"ví USDT",
    "danhao":"đơn cược",
    "neirong":"chi tiết",
    "guanfanghaoyuan":"nguồn gốc kết quả",
    "jianghaozhanshi":"hiển thị",
    "jianghaoshuoming":"giải thích",
    "gongjujiaoyan":"kiểm nghiệm",
    "daojishi":"đếm ngược",
    "qihao":"số lượt xổ",
    "kaijianghaoma":"kết quả",
    "haoyuanjinqi":"nguồn(gần đây",
    "wanzhenghaoyuanzhanshi":"hiển thị toàn bộ nguồn gốc kết quả",
    "zhuaqushijian":"thời gian thu thập：%s",
    "shuominghaoyuan":"để sao chép nhấp vào nguồn gốc kết quả",
    "bitebipc28quhaojizhi":"cơ chế chọn số Bitcoin PC28",
    "zhuahaoyuan": "thu thập số từ nguồn để lấy mẫu ngẫu nhiên của các giao dịch chưa được xác nhận",
    "sha256zhuanhua":"mã hoá SHA256",
    "shijinzhizhuanhua":"mã hoá thập phân",
    "shengchengzuihzhonghaoma":"hình thành kết quả xổ số cuối cùng",
    "zhuahaoyuan_jieshao":"hệ thống mạng tài nhất thế giới blockchain của bitcoin",
    "sha256zhuanhua_jieshao":"mẫu ngẫu nhiên thu được qua bước 1 là tổng hợp tất cả các thông tin giao dịch tại một thời điểm nhất định,sau khi kết hợp các số này thông qua thao tác kết hợp chuỗi,chuyển đổi Y bằng thuật toán SHA256",
    "shijinzhizhuanhua_jieshao":"sau khi thu thập được Z ở bước",
    "shengchengzuihzhonghaoma_jieshao":"sau khi nhận được A ở bước 3",
    "shuruduiyinghaoyuan":"nhập nguồn gốc kết quả tương ứng",
    "jiaoyan":"kiểm nghiệm",
    "jiaoyanjieguo":"kết quả kiểm nghiệm",
    "sha256zhuanhuahzi":"giá trị mã hoá SHA256",
    "quqianshiliuwei":"lấy 16 chữ số đầu tiên",
    "shijinweizhuanhuan":"mã hoá thập phân",
    "chuyierde64cifang":"chia hai cho lũy thừa của 64",
    "zuizhongkaijianghaoma":"kết quả xổ số cuối cùng",
    "shuoming":"người dùng có",
    "shuoming_jieshao":"thể kiểm nghiệm hàm SHA256 thông qua các trang web trực tuyến",
    "haoyuanchaxun":"tìm kiếm nguồn gốc kết quả",
    "dianjifuzhi":"sao chép",
    "nowChat":"chat ngay",
    "jiaoyanshuoming":"giải thích kiểm nghiệm",
    "jiaoyanshuoming1":"1.khi xổ số thu thập các giao dịch trong khoảng thời gian mới nhất của tổ hợp giá trị băm",
    "jiaoyanshuoming2":"2.chuyển chuỗi trên thành SHA256",
    "jiaoyanshuoming3":"3.chuyển đổi theo công thức toán học",
    "jiaoyanshuoming4":"4.theo kết quả chuyển đổi, chọn 3 chữ số thập phân làm kết quả xổ số",
    "dixqitouzhu":"No.%s,đặt cược: %s",
    "dixqikaijiang":"No.%s,xổ số: %s",
    "fengpanzhong":"cược đang đóng",
    "dengdaikaipan":"cược chờ",
    "shuaxin":"làm mới",
    "kaijiangjieguo":"kết quả",
    "xitongxiaoxi":"thông tin hệ thống",
    "shujufenxi":"phân tích",
    "shuangmianchanglong":"rồng, hai mặt",
    "danshuangluzhu":"chẵn lẻ",
    "daxiaoluzhu":"tài xỉu",
    "haomazhoushi":"biểu đồ",
    "lx_tongji":"%s thống kê",
    "xianshiqishu_":"hiển thị lượt xổ：%s",
    "zhi":"giá trị",
    "jixiao":"cực xỉu",
    "jida":"cực tài",
    "bet_long":"rồng",
    "bet_hu":"hổ",
    "bet_he":"hoà",
    "dalu":"đường lớn",
    "zhupanlu":"đường lộ châu",
    "hao_value":"No.{value}",
    "qingshuruyouximingcheng":"nhập tên game",
    "xuanzhe":"vui lòng chọn",
    "xuanzhexl":"选择线路",
    "quanbuyouxi":"tất cả game",
    "shoucangla":"收藏啦",
    "qiandaoyouli":"đánh dấu",
    "jifen":"điểm thưởng",
    "benyueyiqian":"số lần đánh dấu %s",
    "zongjifen":"tổng điểm thưởng",
    "lijiqiandao":"đánh dấu",
    "yiqiandao":"đã đánh dấu",
    "jifenyaojiang":"quay số",
    "jifenmeici":"điểm thưởng：%s(5 điểm thưởng)",
    "lianyao5":"5x",
    "lianyao10":"10x",
    "lianyao15":"15x",
    "lianyao20":"20x",
    "huodongguizhe": "quy tắc chương trình",
    "jiangjintiqu":"nhận tiền thưởng",
    "nianyueri":"yyyy-MM-dd",
    "bencijiangli":"điểm thưởng lần này",
    "gongxiwancheng":"恭喜你完成任务",
    "xiaciqiandao":"下次签到奖励%s,可获得%s积分",
    "mingtianjixue":"明天继续",
    "gongxininhuode":"chúc mừng bạn nhận giải thưởng",
    "jiangjin":"tiền thưởng",
    "cishu":"số lần",
    "lishikaijiang":"lịch sử",
    "kaijiangzhoushi":"biểu đồ",
    "qugoucai":"mua ngay",
    "goucai":"mua ngay",
    "xiaoxi":"thông tin",
    "gonggao":"thông báo",
    "gonggaoxiangqing":"chi tiết thông báo",
    "youhuizhongxin":"trung tâm khuyến mãi",
    "chongzhi":"gửi tiền",
    "quanbu":"tất cả",
    "qita":"khác",
    "fanhui":"trở về",
    "wenxintishi_fuzhi":"lời nhắc nhở：\nnhấn và giữ số để sao chép",
    "chongzhizhongxin":"Trung tâm gửi tiền",
    "chongzhizhanghu_":"Tài khoản gửi tiền: %s",
    "dangqianmoren":"%s(Trạng thái mặc định)",
    "xianshang":"trực tuyến",
    "xianxia":"bình thường",
    "diyibu_chakanshoukuanxinxi":"kiểm tra thông tin nhận bên dưới để chuyển khoản gửi tiền",
    "wenxintishi_zhifuyoushijian":"lời nhắc nhở:có thời hạn thanh toán, vui lòng hoàn tất chuyển khoản trong thời gian quy định",
    "dierbu_tianchongdingdan":"điền vào mã giao dịch gửi tiền sau khi hoàn thành các thao tác trên",
    "chongzhizhanghu":"tài khoản gửi tiền",
    "huikuanxingming":"tên chuyển tiền",
    "huikuanjine":"số tiền chuyển",
    "qingshuruhuikuanren":"nhập tên của người gửi",
    "qingshuruhuikuanjine":"nhập số tiền chuyển",
    "tijiao":"xác định",
    "bibiduihuan":"Trao đổi tiền tệ",
    "eduzhuanhuan":"chuyển khoản",
    "zhifushuoming_rmb":"hướng dẫn thanh toán:\n1.公司帐户资金如何领取到个人帐户 人民币银行结算账户管理方法规定\n2.公司帐户资金如何领取到个人帐户 人民币银行结算账户管理方法规定",
    "zhifushuoming_wallet":"hướng dẫn thanh toán:\n1.vui lòng chọn số tiền bạn muốn gửi hoặc số tiền khác\n2.hệ thống sẽ tự động chuyển đến giao diện thanh toán\n3.bạn có thể chọn ngân hàng trực tuyến hoặc phương thức thanh toán bằng mã quét\n4.sau khi thanh toán thành công\n5.số tiền gửi sẽ tự động được thêm vào tài khoản thành viên của bạn",
    "kahao":"số thẻ",
    "cikaren":"chủ thẻ",
    "beizhu":"ghi chú",
    "dianjixiafangzhifu":"nhấp vào đường link thanh toán bên dưới và đọc thông tin nhắc nhở",
    "wenxintishi_":"lời nhắc nhở",
    "wenxintishi_1":"hệ thống sẽ tự động mở một trang web",
    "wenxintishi_2":"phí thủ tục %s%,tỉ lệ nhận tiền cao",
    "wenxintishi_3":"%s、%s",
    "tianrujine":"điền số tiền (%s-%s) và bấm xác định",
    "shoudongshuruhuoxuanzhe":"nhập thủ công hoặc chọn số tiền bên dưới",
    "diyibu_xuanzhezhifuxieyi":"chọn giao thức thanh toán",
    "dierbu_chakanshoukuanxinxi":"kiểm tra thông tin thanh toán để chuyển khoản gửi tiền",
    "shoukuanzhanghu":"tài khoản nhận tiền",
    "disanbu_tianxierukuanxinxi":"điền thông tin gửi tiền sau khi hoàn tất chuyển khoản",
    "fanhuishouye":"Quay lại trang chủ",
    "zhifushuoming_":"hướng dẫn thanh toán",
    "zhifushuoming_1":"1.số tiền gửi tối thiểu:1USDT，số tiền gửi tối đa: 10000 USDT;\n2.vui lòng sử dụng ",
    "zhifushuoming_2":" giao thức chuyển khoản đến tài khoản nhận tiền;\n3.địa chỉ này là địa chỉ của riêng bạn",
    "nicheng_":"tên nick：%s",
    "wodeqianbao":"Ví của tôi",
    "tixianmima":"mật khẩu rút tiền",
    "zijinmingxi":"lịch sử giao dịch",
    "bangdingyinhangka":"đăng ký thẻ ngân hàng",
    "bangdingusdt":"đăng ký USDT",
    "wodetouzhu":"Đặt cược đặt cược",
    "touzhujilu":"lịch sử đặt cược",
    "jifenjilu":"lịch sử điểm thưởng",
    "huiyuanfanshui":"lịch sử hoàn trả",
    "hongbaohejiangjin":"lì xì và tiền thưởng",
    "wodeyinli":"Lợi nhuận của tôi",
    "tuiguangzhuanqian":"kiếm tiền giới thiệu",
    "dializhuce":"đăng ký đại lý",
    "tongyongshezhi":"Cài đặt chung",
    "bangzhuzhongxin":"Trung tâm trợ giúp",
    "guanyuwomen":"về",
    "tixianzhongxin":"Trung tâm rút tiền",
    "tixianzhanghu_":"Tài khoản rút tiền: %s",
    "congcnyqianbaotichu":"rút tiền từ ví CNY",
    "congusdtqianbaotichu":"rút tiền từ ví USDT",
    "tixianxinxi":"thông tin rút tiền",
    "querentixianxinxi":"Xác nhận thông tin rút tiền",
    "tixianjine":"số tiền rút",
    "qingshurutixianmima":"vui lòng nhập mật khẩu rút tiền",
    "qingshurutixianjine":"vui lòng nhập số tiền rút",
    "querenjine":"xác nhận số tiền",
    "shouxufei":"phí thủ tục",
    "kedaozhangjine":"số tiền sẽ được chuyển khoản",
    "qingxuanzhetixianzhanghu":"vui lòng chọn tài khoản rút tiền",
    "querenjihexinxi":"xác nhận thông tin kiểm toán",
    "zitixianhouzongtouzhu_":"sau khi rút tiền, tổng số tiền cược hợp lệ kể từ lần gửi tiền đầu tiên: %s",
    "youhuijihe":"kiểm toán khuyến mãi",
    "meiyoutongguoyouhui":"chưa thông qua kiểm toán khuyến mãi, khấu trừ khuyến mãi tiền gửi %s",
    "tongguoyouhuijihe":"thông qua kiểm toán khuyến mãi, không cần khấu trừ khuyến mãi tiền gửi",
    "changtaixingjihe": "kiểm toán thông thường",
    "tongguochangtaixing":"thông qua kiểm toán thông thường, không thu phí hành chính",
    "meiyoutongguochangtaixing":"chưa thông qua kiểm toán thông thường, khấu trừ phí hành chính %s",
    "duocitixian":"phí thủ tục nhiều lần rút tiền",
    "yixiaoshineimian":"%s giờ %s lần rút tiền %s",
    "xukouchushouxufei":"phí thủ tục sẽ được khấu trừ %s",
    "shixiaoshouxufei":"phí thủ tục thời hạn rút tiền",
    "mianshoushouxufei":"miễn thu phí thủ tục",
    "shixiaokouchu":"rút tiền trong vòng %s giờ kể từ lần gửi tiền cuối cùng,số tiền rút sẽ bị trừ %s phí thủ tục",
    "shixiaomianshou":"rút tiền trong vòng %s giờ kể từ lần gửi tiền cuối cùng,miễn thu phí thủ tục",
    "cichijiheshijian":"thời gian kiểm toán lần này",
    "meidongshijian_":"giờ miền đông (EST):%s",
    "jixutixian":"tiếp tục rút tiền",
    "tijiaochenggong":"Gửi thành công",
    "tixianxiangqing":"Chi tiết rút tiền",
    "tixianzhanghu":"Tài khoản rút tiền",
    "tijiaoshijian":"Thời gian gửi",
    "shouxufei_":"(phí thủ tục:%s)",
    "daozhangjine":"số tiền nhận",
    "zhanghuyue":"Số dư tài khoản",
    "wancheng":"Hoàn thành",
    "shezhi":"cài đặt",
    "gerenziliao":"Hồ sơ cá nhân",
    "shezhidenglumima":"cài đặt mật khẩu đăng nhập",
    "shezhijianyimima":"Đặt mật khẩu đơn giản",
    "zhongwen":"中文",
    "quankai":"Mở hoàn toàn",
    "tuichudenglu":"Đăng xuất",
    "wanshanziliao":"hoàn thiện thông tin",
    "nicheng":"tên nick",
    "shoujihaoma":"số điện thoại",
    "qqhaoma":"số QQ",
    "weixin":"số wechat",
    "shuruweixinhao":"nhập số wechat",
    "shuruqqhaoma":"nhập số QQ",
    "shuruzhenshiyouxiao":"nhập số điện thoạ thực và hợp lệ",
    "shurudianziyouxiang":"nhập địa chỉ email",
    "shurunicheng":"nhập biệt hiệu",
    "shezhitixianmima":"cài đặt mật khẩu rút tiền",
    "yuanmima":"mật khẩu cũ",
    "shuruyuantixianmima":"nhập mật khẩu cũ",
    "xinmima":"mật khẩu mới",
    "shuruxintixianmima":"4-12 chữ số hoặc chữ cái",
    "zaiciqueren":"xác nhận lần hai",
    "chongfushuru":"nhập lại mật khẩu rút tiền mới",
    "querenjianyimima":"确认简易密码",
    "shurujianyimima": "Nhập mật khẩu đơn giản",
    "shezhichenggong":"设置成功",
    "shuruneirongbuyizhi":"输入内容不一致，请重试",
    "wenxintishi_jianyimima":"温馨提示:\n一些说明文字一些说明文字一些说明文字一些说明文字一些说明文字",
    "shuruyuandenglumima":"nhập mật khẩu đăng nhập cũ",
    "shuruxindenglumima":"8-12 chữ số hoặc chữ cái",
    "chongfushuruxindenglumima":"nhập lại mật khẩu đăng nhập mới",
    "genghuantouxiang":"thay đổi hình đại diện",
    "moren":"hình đại diện mặc định",
    "qq":"hình đại diện QQ",
    "jingxuan":"hình đại diện đặc sắc",
    "gezhanghumingxi":"Chi tiết số dư mỗi tài khoản",
    "huazhuanjilu":"Lịch sử chuyển đổi",
    "dailizhuce":"đăng ký đại lý",
    "querenmima":"xác nhận mật khẩu",
    "dianziyouxiang":"địa chỉ email",
    "wenxintishi_zhuce":"lời nhắc nhở\n1.mục có dấu * là thông tin bắt buộc\n2.đăng ký có nghĩa là bạn chấp nhận điều khoản và điều kiện của trang web",
    "jieshaorenxinxi":"thông tin người giới thiệu",
    "daima":"mã Code",
    "fuzhi":"Sao chép",
    "lianjie":"đường link",
    "tuiguangerweima":"mã QR",
    "baocuntupian":"lưu ảnh",
    "baocunchenggong":"đã sao chép",
    "fuzhilianjie":"sao chép",
    "huiyuanliebiao":"danh sách giới thiệu",
    "riqi":"ngày",
    "xiaxiancunkuan":"bạn bè đã gửi tiền",
    "zhuanquhongli":"tiền thưởng nhận được",
    "xianxiayonghu":"bạn bè đã giới thiệu",
    "zhu_beijingshijian":"lưu ý giờ Bắc Kinh là 12 giờ miền đông (EST)",
    "riqi_meidong":"ngày (EST)",
    "jiaoyileibie":"giao dịch",
    "jiaoyiedu":"số tiền",
    "xianyouedu":"số dư",
    "xiazhujifenjiangli":"下注积分奖励",
    "fuyinglifanshui":"hoàn trả cược thua",
    "youxileixing":"loại game",
    "youxiaotouzhu":"cược hợp lệ",
    "shuying":"thắng thua",
    "fanshui":"hoàn trả",
    "touzhuliangfanshui":"hoàn trả số lượng cược",
    "jinrizuhezhanbilv":"tỷ lệ cược tổ hợp hôm nay",
    "qitayouxi_":"khác ( %s đến %s )",
    "huishui":"hoàn trả cược thua",
    "yinlifanshui":"hoàn trả",
    "zuhezhanbilv":"tỷ lệ cược tổ hợp",
    "jinri":"hôm nay",
    "day_7":"7 ngày gần đây",
    "day_15":"15 ngày gần đây",
    "day_30":"30 ngày gần đây",
    "youxipingtai":"nền tảng game",
    "bishu":"số lượng",
    "touzhue":"tiền cược",
    "youxiaotouzhu_":"cược hợp lệ: %s tiền cược: %s",
    "touzhuriqi":"ngày đặt cược (EST)",
    "wodeyinhangka_":"thẻ ngân hàng của tôi:đã đăng ký %s(vẫn có thể đăng ký %s)",
    "wodeshuzhiqianbao_":"ví USDT của tôi:đã đăng ký %s(vẫn có thể đăng ký %s)",
    "tianjiayinhangka": "thêm thẻ ngân hàng",
    "zuiduoketianjia_":"(nhiều nhất có thể thêm %s)",
    "wenxintixing_yinhangka":"lời nhắc nhở:\n1.tên chủ tài khoản ngân hàng phải khớp với tên đã nhập khi đăng ký;\n2.mỗi khách hàng có thể đăng ký tối đa 3 thẻ ngân hàng;\n3.sau khi đã đăng ký không được tự ý sửa đổi,nếu cần sửa đổi, vui lòng",
    "tianjiashuziqianbao":"thêm ví tiền ảo",
    "wenxintixing_usdt":"lời nhắc nhở:\n1.mỗi khách hàng có thể đăng ký tối đa 3 ví tiền ảo;\n2.sau khi đã đăng ký không được tự ý sửa đổi, nếu cần sửa đổi, vui lòng",
    "dizhi":"địa chỉ ví",
    "suoshuxieyi":"giao thức",
    "hongbao":"lì xì",
    "jine":"số tiền",
    "youxiaoqi":"thời hạn",
    "xuyaodamaliang":"lượng cược phải đặt",
    "yitiqu":"đã nhận thưởng",
    "weijihuo":"chưa kích hoạt",
    "yijihuo":"đã kích hoạt",
    "yishixiao":"đã hết hạn",
    "tiqu":"nhận thưởng",
    "tiquchenggong":"thành công",
    "duihuan":"Trao đổi",
    "huilv_":"Tỷ giá: %s",
    "cong_from":"từ",
    "zhi_to":"đến",
    "zhuanru":"chuyển vào",
    "huazhuanjine":"Số tiền chuyển đổi",
    "querenhuazhuan":"Xác nhận chuyển đổi",
    "yijianguiji":"quy tụ",
    "xuanzheriqi":"Lựa chọn ngày",
    "shaixuan":"筛选",
    "cunqukuan":"gửi rút tiền",
    "zhuanzhang":"chuyển khoản",
    "zhichu":"支出",
    "shouru":"收入",
    "qingxuanzhe":"vui lòng chọn",
    "qing3fenzhonghoushuaxin":"vui lòng làm mới kiểm tra sau 3 phút",
    "chongzhixiangqing":"chi tiết",
    "chongzhixingming":"tên gửi tiền",
    "dingdanbianhao":"mã giao dịch",
    "chongzhijine":"số tiền gửi",
    "zhongwenjianti":"中文简体",
    "yingyu":"English",
    "yuenanyu":"Tiếng Việt",
    "jintian":"hôm nay",
    "zuijin7tain":"7 ngày gần đây",
    "zuijin30tian":"30 ngày gần đây",
    "quanbuzhuangtai":"trạng thái",
    "chenggong":"thành công",
    "chulizhong":"đang xử lý",
    "yiquxiao":"đã hủy",
    "quanbufangshi":"phương thức",
    "fuzhichenggong":"sao chép thành công",
    "qiehuanquanjuqianbao":"切换全局钱包",
    "tuijianyouli":"Quà tặng giới thiệu",
    "qianghongbao":"Nhận lì xì",
    "zanwuyouxi":"không tìm thấy thông tin",
    "fanshuishuoming":"chi tiết hoàn trả",
    "jiazaizhong":"đang tải...",
    "weikaishi":"chưa bắt đầu",
    "jinxingzhong":"đang tiến hành",
    "yijieshu":"đã kết thúc",
    "hongbaohuodong":"Các hoạt động",
    "xiangqing":"chi tiết",
    "qingxiandenglu":"bạn chưa đăng nhập, vui lòng đăng nhập",
    "jingqingqidai":"sắp ra mắt",
    "denglugengjingcai":"Chào mừng",
    "gengduo":"Thêm nữa",
    "huishou":"thu hồi",
    "sishiershuzihuozimu":"4-12 chữ số hoặc chữ cái",
    "bashiershuzihuozimu":"8-12 chữ số hoặc chữ cái",
    "zhenshixingmingbunengkong":"họ và tên không được để trống",
    "yanzhengmabunengkong":"nhập mã xác nhận",
    "mimashurubuyizhi":"xác nhận lại mật khẩu không khớp với mật khẩu của bạn",
    "usdt_coin":"USDT",
    "lianxizaixiankefu":"vui lòng liên hệ chăm sóc khách hàng",
    "shuruzhuanzhangqianbao":"nhập địa chỉ ví bạn đã sử dụng khi gửi tiền",
    "yiwanchengtijiaorukuan":"xác định",
    "qianbaodizhi":"địa chỉ ví",
    "shifoujinxingzhuanzhang":"bạn đã chuyển khoản đến tài khoản nhận tiền chưa",
    "tishi":"lời nhắc nhở",
    "yinhangmingcheng":"tên ngân hàng",
    "xuanzhezhifuyinhang":"chọn ngân hàng thanh toán",
    "zhifutiaozhuan":"liên kết thanh toán %s",
    "quedingtijiaodingdan":"xác định muốn đặt lệnh giao dịch?",
    "caozuochenggong":"thành công",
    "zhuzhanghao":"số dư chính",
    "qingxuanzhezhuanru":"vui lòng chọn tài khoản chuyển vào",
    "qingxuanzhezhuanchu":"vui lòng chọn tài khoản chuyển ra",
    "qingxuanzhetikuanzhanghu":"vui lòng chọn tài khoản rút tiền",
    "dianjitianjiazhanghu":"nhấp để thêm tài khoản",
    "ninhaimeibangdingyhkzhanghu":"bạn chưa đăng ký tài khoản ngân hàng",
    "ninhaimeibangdingusdtzhanghu":"bạn chưa đăng ký tài khoản USDT",
    "ninhaimeibangdingqianbao":"Bạn chưa đăng ký loại ví này",

    "qubangding":"đăng ký",
    "chukuanzhanghu":"số tài khoản ngân hàng",
    "chukuanyinhang":"tên ngân hàng",
    "kaihudizhi":"địa chỉ mở tài khoản",
    "yanzhengchukuanmima":"xác nhận mật khẩu rút tiền",
    "shuruyinhangkakaihudizhi":"vui lòng nhập địa chỉ mở tài khoản",
    "liudao12weishuzihuozimu":"6-12 chữ số hoặc chữ cái",
    "yigezhanghaosanzhangyinhangka":"mỗi khách hàng chỉ có thể đăng ký 3 thẻ ngân hàng\nnếu cần sửa đổi, vui lòng liên hệ với chăm sóc khách hàng",
    "qingshuruqianbaodizhi":"vui lòng nhập địa chỉ ví",
    "qingshuruqukuanmima":"vui lòng nhập mật khẩu rút tiền",
    "qianbaoxieyi":"giao thức ví",
    "yanzhengzijinmima":"xác nhận mật khẩu giao dịch",
    "shuruyinhangzhanghao":"số tài khoản ngân hàng không được để trống",
    "qingxuanzhechukuanyinhang":"vui lòng chọn ngân hàng rút tiền",
    "qingshuruchukuanmima":"mật khẩu rút tiền không được để trống",
    "trc20_show":"TRC20 (giao thức TRON)",
    "erc20_show":"ERC20 (giao thức Ethereum)",
    "omni_show":"OMNI (giao thức Bitcoin)",
    "tuiguanghongli":"tiền thưởng giới thiệu",
    "sidao12shuzihuozimu":"4-12 chữ số hoặc chữ cái",
    "mimacuowu":"Mật khẩu đơn là sai",
    "zhanghaomimadenglu":"Đăng nhập bằng tài khoản mật khẩu",
    "chongzhijymm":"Đặt lại mật khẩu đơn giản",
    "chongzhijymmtishi":"Sau khi đặt lại mật khẩu đơn giản, mật khẩu đơn giản bạn đã đặt sẽ bị xóa, vui lòng sử dụng tên đăng nhập và mật khẩu để đăng nhập. Sau khi đăng nhập thành công, mật khẩu đơn giản sẽ tự động bị xóa.",
    "qingzaiciyanzhenghaxizhi":"vui lòng nhập hoặc dán giá trị băm bạn muốn xác minh tại đây",
    "geshangqi":"cách lượt xổ trước",
    "jinrikai":"xổ hôm nay",
    "wodeshoucang":"sưu tập của tôi",
    "lianxiwomen":"Liên hệ chúng tôi",
    "2023guojizhan_boya":"@2024 BOYA CASINO",
    "2023guojizhan_dw":"@2024 DW International",
    "yingyongneijiazai":"Nạp nhẹ trong ứng dụng",
    "liulanqidakai":"Mở bằng trình duyệt mặc định hệ thống",
    "biaozhunshijian":"giờ chuẩn của trang web này dựa trên giờ miền đông (EST)\ngiờ miền đông (EST)",
    "zhuninxiacizdj":"chúc may mắn lần sau",
    "jiangjinfengfu":"tiền thưởng phong phú",
    "weihuzhong":"đang bảo trì",
    "yiguanpan":"đã đóng cược",
    "yixiushi":"thị trường đóng",
    "yichenggongqiehuan_":"Đã chuyển thành công Ví %s Ví,\nTrong game, bạn sẽ sử dụng %s",
    "jifenbuzu":"không đủ điểm thưởng",
    "xianlu1":"线路1",
    "xianlu2":"线路2",
    "xianlu3":"线路3",
    "xianlu4":"线路4",
    "xianlu5":"线路5",
    "xianlu6":"线路6",
    "julifengpan":"The game will end in",
    "miao":"giây",
    "kaishixiazhu":"bắt đầu đặt cược",
    "bangdingqitaqianbao":"Liên kết ví khác",
    "wodeqitaqianbao":"ví tiền ảo của tôi：đã đăng ký %s(ẫn có thể đăng ký %s)",
    "zuiduoketianjiaqianbao":"(nhiều nhất có thể thêm %s)",
    "qitaqianbaowenxintis":"lời nhắc nhở:\n1.Số lượng tài khoản ví khác tối đa mà mỗi người dùng có thể đăng ký là:10(Các loại khác nhau có thể được đăng ký với một loại tương ứng)\n2.sau khi đã đăng ký không được tự ý sửa đổi,nếu cần sửa đổi, vui lòng",
    "qianbaoleixing":"Loại ví",
    "tixianfangshi":"Phương thức rút tiền",
    "yhk":"Thẻ ngân hàng",
    "xqianbao":"%s Ví",
    "xianlu_":"địa chỉ %s",
    "julifengpanshijian":"cách thời gian kết thúc lì xì %s",
    "dixqi":"No.%s",
    "no":"No.",
    "fengpanxinxi":"thông tin cược đóng",
    "kaishifengpan":"开始封盘",
    "lianjiefuwushibai":"链接服务失败，稍后再试",
    "kaijiangzhong":"đang xổ số",
    "qiandaochenggong":"đánh dấu",
    "benyueleijiqiandao":"số lần đánh dấu tích lũy trong tháng này：",
    "jiajifen":"，+",
    "zaiqiandao":"tiếp tục đánh dấu số lần：",
    "kehuode":"，có thể nhận được",
    "gentou":"theo cược",
    "zhongjiangjieguodongxiao":"Hoạt hình kết quả trúng thưởng",
    "qingxuanzhetouzhuxm":"vui lòng chọn mục đặt cược",
    "xiazhujinewk":"số tiền không được để trống",
    "danmu":"Cửa sổ nổi bật",
    "changqihuodong":"chương trình lâu dài",
    "jiehzhiriqizhi":"thời hạn đến",
    "dao":"đến",
    "zanwuxiazhujilu":"không tìm thấy lịch sử đặt cược",
    "xuanzheleixing":"Lựa chọn loại hình",
    "touzhuchenggong":"gửi thành công",
    "kaihuxieyi":"điều khoản và điều kiện",
    "jieshaoren":"người giới thiệu",
    "shurujieshaoren":"nhập người giới thiệu",
    "yuebuzhuqingxianchongzhi":"không đủ số dư để đặt cược, gửi tiền ngay？",
    "qingkaitongzhanghu":"Vui lòng mở bất kỳ tài khoản nào trước",
    "huodongweikaiqi":"Chương trình chưa bắt đầu",
    "qingquerenzhudan":"vui lòng xác nhận đơn cược",
    "xuanzhonghaoma":"số đã chọn",
    "peilv":"ỷ lệ cược",
    "ruozhongjiang":"nếu trúng thưởng tiền thưởng",
    "yinli":", thắng",
    "zongjine":", tổng cộng",
    "zunjingdekehu":", khách hàng thân mến",
    "xitonggonggao":", hệ thống thông báo",
    "yibangding":"đã đăng ký",
    "xuanzhenindemorenqianbao":"Chọn ví mặc định của bạn",
    "morenqianbaotishi1":"1.Chọn ví mặc định của bạn và loại tiền tương ứng sẽ được sử dụng để thanh toán khi vào trò chơi.",
    "morenqianbaotishi2":"2.Hoạt động trao đổi giữa số dư của hai ví có thể được thực hiện trên trang [chuyển khoản].",
    "zuida":"tất cả",
    "shuruyinhangmingcheng":"Vui lòng nhập tên ngân hàng",
    "yicizhinengfasong3tiao":"chỉ có thể gửi 3 câu một lúc",
    "shuruneirongchaoguozuidaxianzhi":"nội dung bạn đã nhập nhiều hơn giới hạn tối đa",
    "guanbijianyimima": "Sau khi đóng mật khẩu đơn giản, mật khẩu đơn giản bạn đã đặt sẽ bị xóa, vui lòng sử dụng tên đăng nhập và mật khẩu để đăng nhập. Sau khi đăng nhập thành công, mật khẩu đơn giản sẽ tự động bị xóa.",
    "wolaishuoliangju":"tôi nói vài câu...",
    "fanshuixiangqing":"chi tiết hoàn trả",
    "faxianxinbanben":"Tìm thấy phiên bản mới",
    "xiacizaishuo":"Sau này",
    "lijigengxin":"Ngay lập tức",
    "jianchagengxin":"Kiểm tra cập nhật",
    "yijingshizuixinl":"Đó là phiên bản mới nhất",
    "weishouxuanzhuangquanxian":"Không cho phép cài đặt, cập nhật đã bị hủy bỏ",
    "denglumima":"mật khẩu đăng nhập",
    "zhucetishiyu":"1.mục có dấu * là thông tin bắt buộc\n2.đăng ký có nghĩa là bạn chấp nhận điều khoản và điều kiện của trang web",
    "huiyuanchukuanjinedayuzhuzhanghu":"Số tiền các thành viên rút ra nhiều hơn số dư tài khoản chính",
    "bet_tema":"số đặc biệt",
    "bet_jida":"cực tài",
    "bet_jixiao":"cực xỉu",
    "bet_hongbo":"bóng đỏ",
    "bet_lanbo":"bóng lam",
    "bet_lvbo":"bóng lục",
    "bet_sunzi":"sảnh",
    "bet_baozi":"báo",
    "bet_duizi":"đôi",
    "hello_you": "chào, %s",
    "zuotian":"hôm qua",
    "ti_confirm":"xác định",
    "ruoxuxiugaitixianzhanghu":"1.nếu bạn cần sửa đổi thông tin tài khoản rút tiền, vui lòng liên hệ chăm sóc khách hàng\n2.nếu không có trường hợp đặc biệt, sẽ mất khoảng 3 đến 5 phút để đến tài khoản",
    "shibieshibai":"Nhận ra thất bại!",


  };
}